/-
# PF.Analytic.RiemannXiBox114Panels.Seg13

OPT-40-TIGHT Stage-2 segment 13: L=11/8 U=45/32 n=10 MHI=9565071000000089/2500000000000000.
Auto-generated by scripts/emit_stage2_segment.py.

Split into 4 panel modules (Seg13P1..P4) for
per-file Interval-computation memory bounds.

  RE_LO_SUM = -777029737/5000000000     RE_HI_SUM = 0
  IM_LO_SUM = 91656821/10000000000     IM_HI_SUM = 23707/2500000
  E_SEG     = 9565071000000089/196608000000000000000000 ≈ 4.8650e-08
  RE_INT_LO = -95490979153560000089/196608000000000000000000 ≈ -4.8569e-04
  RE_INT_HI = 9565071000000089/196608000000000000000000 ≈ 4.8650e-08
  IM_INT_LO = 5621830011239999911/196608000000000000000000 ≈ 2.8594e-05
  IM_INT_HI = 5835797391000000089/196608000000000000000000 ≈ 2.9682e-05

SPDX-License-Identifier: Apache-2.0
-/

import PF.Analytic.RiemannXiThetaRealFormAndBoxes_r331b
import PF.Analytic.RiemannXiBoxParametric
import PF.Numerics.Box114Seg13M
import PF.Analytic.RiemannXiBox114Panels.Seg13P1
import PF.Analytic.RiemannXiBox114Panels.Seg13P2
import PF.Analytic.RiemannXiBox114Panels.Seg13P3
import PF.Analytic.RiemannXiBox114Panels.Seg13P4

namespace PrincipiaTractalis.RiemannXiBox114Panels.Seg13

open scoped Real BigOperators
open PrincipiaTractalis.RiemannXiThetaRealFormAndBoxes
open PrincipiaTractalis.Box114Seg13M
open PrincipiaTractalis.XiQuadrature
open PrincipiaTractalis.RiemannXiBox114Panels.Seg13P1
open PrincipiaTractalis.RiemannXiBox114Panels.Seg13P2
open PrincipiaTractalis.RiemannXiBox114Panels.Seg13P3
open PrincipiaTractalis.RiemannXiBox114Panels.Seg13P4

/-! ## Chunk sum (aggregated from all panels) -/

theorem seg13_chunk_bounds (σ : ℝ)
    (hσ0 : (61/64 : ℝ) ≤ σ) (hσ1 : σ ≤ 31/32) :
    ((-777029737/5000000000 : ℝ)) ≤ realThetaReIntegrandN 3 σ 15 (881/640 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (883/640 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (177/128 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (887/640 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (889/640 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (891/640 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (893/640 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (179/128 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (897/640 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (899/640 : ℝ)
    ∧ realThetaReIntegrandN 3 σ 15 (881/640 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (883/640 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (177/128 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (887/640 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (889/640 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (891/640 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (893/640 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (179/128 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (897/640 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (899/640 : ℝ) ≤ ((0/1 : ℝ))
    ∧ ((91656821/10000000000 : ℝ)) ≤ realThetaImIntegrandN 3 σ 15 (881/640 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (883/640 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (177/128 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (887/640 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (889/640 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (891/640 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (893/640 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (179/128 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (897/640 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (899/640 : ℝ)
    ∧ realThetaImIntegrandN 3 σ 15 (881/640 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (883/640 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (177/128 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (887/640 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (889/640 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (891/640 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (893/640 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (179/128 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (897/640 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (899/640 : ℝ) ≤ ((23707/2500000 : ℝ)) := by
  have hp1 := seg13_p1_chunk_bounds σ hσ0 hσ1
  have hp2 := seg13_p2_chunk_bounds σ hσ0 hσ1
  have hp3 := seg13_p3_chunk_bounds σ hσ0 hσ1
  have hp4 := seg13_p4_chunk_bounds σ hσ0 hσ1
  refine ⟨?_, ?_, ?_, ?_⟩
  · linarith [(hp1).1, (hp2).1, (hp3).1, (hp4).1]
  · linarith [(hp1).2.1, (hp2).2.1, (hp3).2.1, (hp4).2.1]
  · linarith [(hp1).2.2.1, (hp2).2.2.1, (hp3).2.2.1, (hp4).2.2.1]
  · linarith [(hp1).2.2.2, (hp2).2.2.2, (hp3).2.2.2, (hp4).2.2.2]

/-! ## Midpoint sum equality -/

theorem seg13_re_midpoint_sum_eq_raw (σ : ℝ) :
    (∑ i ∈ Finset.range 10, realThetaReIntegrandN 3 σ 15
       ((11/8 : ℝ) + (45/32 - 11/8) / 10 * ((i : ℝ) + 1/2)))
    = realThetaReIntegrandN 3 σ 15 (881/640 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (883/640 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (177/128 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (887/640 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (889/640 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (891/640 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (893/640 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (179/128 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (897/640 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (899/640 : ℝ) := by
  have e0 : ((11/8 : ℝ) + (45/32 - 11/8) / 10 * (1/2)) = (881/640 : ℝ) := by norm_num
  have e1 : ((11/8 : ℝ) + (45/32 - 11/8) / 10 * ((1 : ℝ) + 1/2)) = (883/640 : ℝ) := by norm_num
  have e2 : ((11/8 : ℝ) + (45/32 - 11/8) / 10 * ((2 : ℝ) + 1/2)) = (177/128 : ℝ) := by norm_num
  have e3 : ((11/8 : ℝ) + (45/32 - 11/8) / 10 * ((3 : ℝ) + 1/2)) = (887/640 : ℝ) := by norm_num
  have e4 : ((11/8 : ℝ) + (45/32 - 11/8) / 10 * ((4 : ℝ) + 1/2)) = (889/640 : ℝ) := by norm_num
  have e5 : ((11/8 : ℝ) + (45/32 - 11/8) / 10 * ((5 : ℝ) + 1/2)) = (891/640 : ℝ) := by norm_num
  have e6 : ((11/8 : ℝ) + (45/32 - 11/8) / 10 * ((6 : ℝ) + 1/2)) = (893/640 : ℝ) := by norm_num
  have e7 : ((11/8 : ℝ) + (45/32 - 11/8) / 10 * ((7 : ℝ) + 1/2)) = (179/128 : ℝ) := by norm_num
  have e8 : ((11/8 : ℝ) + (45/32 - 11/8) / 10 * ((8 : ℝ) + 1/2)) = (897/640 : ℝ) := by norm_num
  have e9 : ((11/8 : ℝ) + (45/32 - 11/8) / 10 * ((9 : ℝ) + 1/2)) = (899/640 : ℝ) := by norm_num
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, zero_add,
             Nat.cast_zero, Nat.cast_one, Nat.cast_ofNat,
             e0, e1, e2, e3, e4, e5, e6, e7, e8, e9]

theorem seg13_im_midpoint_sum_eq_raw (σ : ℝ) :
    (∑ i ∈ Finset.range 10, realThetaImIntegrandN 3 σ 15
       ((11/8 : ℝ) + (45/32 - 11/8) / 10 * ((i : ℝ) + 1/2)))
    = realThetaImIntegrandN 3 σ 15 (881/640 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (883/640 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (177/128 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (887/640 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (889/640 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (891/640 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (893/640 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (179/128 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (897/640 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (899/640 : ℝ) := by
  have e0 : ((11/8 : ℝ) + (45/32 - 11/8) / 10 * (1/2)) = (881/640 : ℝ) := by norm_num
  have e1 : ((11/8 : ℝ) + (45/32 - 11/8) / 10 * ((1 : ℝ) + 1/2)) = (883/640 : ℝ) := by norm_num
  have e2 : ((11/8 : ℝ) + (45/32 - 11/8) / 10 * ((2 : ℝ) + 1/2)) = (177/128 : ℝ) := by norm_num
  have e3 : ((11/8 : ℝ) + (45/32 - 11/8) / 10 * ((3 : ℝ) + 1/2)) = (887/640 : ℝ) := by norm_num
  have e4 : ((11/8 : ℝ) + (45/32 - 11/8) / 10 * ((4 : ℝ) + 1/2)) = (889/640 : ℝ) := by norm_num
  have e5 : ((11/8 : ℝ) + (45/32 - 11/8) / 10 * ((5 : ℝ) + 1/2)) = (891/640 : ℝ) := by norm_num
  have e6 : ((11/8 : ℝ) + (45/32 - 11/8) / 10 * ((6 : ℝ) + 1/2)) = (893/640 : ℝ) := by norm_num
  have e7 : ((11/8 : ℝ) + (45/32 - 11/8) / 10 * ((7 : ℝ) + 1/2)) = (179/128 : ℝ) := by norm_num
  have e8 : ((11/8 : ℝ) + (45/32 - 11/8) / 10 * ((8 : ℝ) + 1/2)) = (897/640 : ℝ) := by norm_num
  have e9 : ((11/8 : ℝ) + (45/32 - 11/8) / 10 * ((9 : ℝ) + 1/2)) = (899/640 : ℝ) := by norm_num
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, zero_add,
             Nat.cast_zero, Nat.cast_one, Nat.cast_ofNat,
             e0, e1, e2, e3, e4, e5, e6, e7, e8, e9]

/-! ## Midpoint sum bounds -/

theorem seg13_re_midpoint_sum_lower (σ : ℝ)
    (hσ0 : (61/64 : ℝ) ≤ σ) (hσ1 : σ ≤ 31/32) :
    ((-777029737/5000000000 : ℝ)) ≤ (∑ i ∈ Finset.range 10, realThetaReIntegrandN 3 σ 15
        ((11/8 : ℝ) + (45/32 - 11/8) / 10 * ((i : ℝ) + 1/2))) := by
  rw [seg13_re_midpoint_sum_eq_raw]
  linarith [(seg13_chunk_bounds σ hσ0 hσ1).1]

theorem seg13_re_midpoint_sum_upper (σ : ℝ)
    (hσ0 : (61/64 : ℝ) ≤ σ) (hσ1 : σ ≤ 31/32) :
    (∑ i ∈ Finset.range 10, realThetaReIntegrandN 3 σ 15
        ((11/8 : ℝ) + (45/32 - 11/8) / 10 * ((i : ℝ) + 1/2))) ≤ ((0/1 : ℝ)) := by
  rw [seg13_re_midpoint_sum_eq_raw]
  linarith [(seg13_chunk_bounds σ hσ0 hσ1).2.1]

theorem seg13_im_midpoint_sum_lower (σ : ℝ)
    (hσ0 : (61/64 : ℝ) ≤ σ) (hσ1 : σ ≤ 31/32) :
    ((91656821/10000000000 : ℝ)) ≤ (∑ i ∈ Finset.range 10, realThetaImIntegrandN 3 σ 15
        ((11/8 : ℝ) + (45/32 - 11/8) / 10 * ((i : ℝ) + 1/2))) := by
  rw [seg13_im_midpoint_sum_eq_raw]
  linarith [(seg13_chunk_bounds σ hσ0 hσ1).2.2.1]

theorem seg13_im_midpoint_sum_upper (σ : ℝ)
    (hσ0 : (61/64 : ℝ) ≤ σ) (hσ1 : σ ≤ 31/32) :
    (∑ i ∈ Finset.range 10, realThetaImIntegrandN 3 σ 15
        ((11/8 : ℝ) + (45/32 - 11/8) / 10 * ((i : ℝ) + 1/2))) ≤ ((23707/2500000 : ℝ)) := by
  rw [seg13_im_midpoint_sum_eq_raw]
  linarith [(seg13_chunk_bounds σ hσ0 hσ1).2.2.2]

/-! ## Stage-2 segment-integral bounds via midpoint error + M ≤ MHI -/

private lemma seg13_error_bound_le :
    (2 * ∑ n' ∈ Finset.range 3, thetaPowTermM 15 (63/64) (8001/4096) (11/8) n')
      * ((45/32 : ℝ) - 11/8) ^ 3 / (24 * (10 : ℕ) ^ 2)
      ≤ ((9565071000000089/196608000000000000000000 : ℝ)) := by
  have hM := box114_seg13_M_le_MHI
  set M := 2 * ∑ n' ∈ Finset.range 3, thetaPowTermM 15 (63/64) (8001/4096) (11/8) n' with hM_def
  have hassoc : M * ((45/32 : ℝ) - 11/8) ^ 3 / (24 * (10 : ℕ) ^ 2)
              = M * (((45/32 : ℝ) - 11/8) ^ 3 / (24 * (10 : ℕ) ^ 2)) := by ring
  rw [hassoc]
  have hf : ((45/32 : ℝ) - 11/8) ^ 3 / (24 * (10 : ℕ) ^ 2)
          = ((1/78643200 : ℝ)) := by push_cast; norm_num
  rw [hf]
  have hpos : (0 : ℝ) < (1/78643200 : ℝ) := by norm_num
  calc M * ((1/78643200 : ℝ))
        ≤ ((9565071000000089/2500000000000000 : ℝ)) * ((1/78643200 : ℝ)) :=
          mul_le_mul_of_nonneg_right hM (le_of_lt hpos)
    _ = ((9565071000000089/196608000000000000000000 : ℝ)) := by norm_num

theorem box114_seg13_re_integral_lower (σ : ℝ)
    (hσ0 : (61/64 : ℝ) ≤ σ) (hσ1 : σ ≤ 31/32) :
    ((-95490979153560000089/196608000000000000000000 : ℝ)) ≤ ∫ u in (11/8 : ℝ)..45/32, realThetaReIntegrandN 3 σ 15 u := by
  have hL : (1 : ℝ) ≤ 11/8 := by norm_num
  have hLU : (11/8 : ℝ) ≤ 45/32 := by norm_num
  have hn : 0 < (10 : ℕ) := by decide
  have herr := PrincipiaTractalis.RiemannXiBoxParametric.box_re_midpoint_error_on_segment (N := 3) (σlo := (61/64 : ℝ)) (σhi := (31/32 : ℝ)) (p1 := (63/64 : ℝ)) (p2 := (8001/4096 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) hσ0 hσ1 hL hLU hn
  have hbound := seg13_error_bound_le
  have habs := abs_le.mp (le_trans herr hbound)
  have hmid := seg13_re_midpoint_sum_lower σ hσ0 hσ1
  have hscale : ((45/32 : ℝ) - 11/8) / (10 : ℕ) = ((1/320 : ℝ)) := by push_cast; norm_num
  rw [hscale] at habs
  linarith [habs.1, hmid]

theorem box114_seg13_re_integral_upper (σ : ℝ)
    (hσ0 : (61/64 : ℝ) ≤ σ) (hσ1 : σ ≤ 31/32) :
    (∫ u in (11/8 : ℝ)..45/32, realThetaReIntegrandN 3 σ 15 u) ≤ ((9565071000000089/196608000000000000000000 : ℝ)) := by
  have hL : (1 : ℝ) ≤ 11/8 := by norm_num
  have hLU : (11/8 : ℝ) ≤ 45/32 := by norm_num
  have hn : 0 < (10 : ℕ) := by decide
  have herr := PrincipiaTractalis.RiemannXiBoxParametric.box_re_midpoint_error_on_segment (N := 3) (σlo := (61/64 : ℝ)) (σhi := (31/32 : ℝ)) (p1 := (63/64 : ℝ)) (p2 := (8001/4096 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) hσ0 hσ1 hL hLU hn
  have hbound := seg13_error_bound_le
  have habs := abs_le.mp (le_trans herr hbound)
  have hmid := seg13_re_midpoint_sum_upper σ hσ0 hσ1
  have hscale : ((45/32 : ℝ) - 11/8) / (10 : ℕ) = ((1/320 : ℝ)) := by push_cast; norm_num
  rw [hscale] at habs
  linarith [habs.2, hmid]

theorem box114_seg13_im_integral_lower (σ : ℝ)
    (hσ0 : (61/64 : ℝ) ≤ σ) (hσ1 : σ ≤ 31/32) :
    ((5621830011239999911/196608000000000000000000 : ℝ)) ≤ ∫ u in (11/8 : ℝ)..45/32, realThetaImIntegrandN 3 σ 15 u := by
  have hL : (1 : ℝ) ≤ 11/8 := by norm_num
  have hLU : (11/8 : ℝ) ≤ 45/32 := by norm_num
  have hn : 0 < (10 : ℕ) := by decide
  have herr := PrincipiaTractalis.RiemannXiBoxParametric.box_im_midpoint_error_on_segment (N := 3) (σlo := (61/64 : ℝ)) (σhi := (31/32 : ℝ)) (p1 := (63/64 : ℝ)) (p2 := (8001/4096 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) hσ0 hσ1 hL hLU hn
  have hbound := seg13_error_bound_le
  have habs := abs_le.mp (le_trans herr hbound)
  have hmid := seg13_im_midpoint_sum_lower σ hσ0 hσ1
  have hscale : ((45/32 : ℝ) - 11/8) / (10 : ℕ) = ((1/320 : ℝ)) := by push_cast; norm_num
  rw [hscale] at habs
  linarith [habs.1, hmid]

theorem box114_seg13_im_integral_upper (σ : ℝ)
    (hσ0 : (61/64 : ℝ) ≤ σ) (hσ1 : σ ≤ 31/32) :
    (∫ u in (11/8 : ℝ)..45/32, realThetaImIntegrandN 3 σ 15 u) ≤ ((5835797391000000089/196608000000000000000000 : ℝ)) := by
  have hL : (1 : ℝ) ≤ 11/8 := by norm_num
  have hLU : (11/8 : ℝ) ≤ 45/32 := by norm_num
  have hn : 0 < (10 : ℕ) := by decide
  have herr := PrincipiaTractalis.RiemannXiBoxParametric.box_im_midpoint_error_on_segment (N := 3) (σlo := (61/64 : ℝ)) (σhi := (31/32 : ℝ)) (p1 := (63/64 : ℝ)) (p2 := (8001/4096 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) hσ0 hσ1 hL hLU hn
  have hbound := seg13_error_bound_le
  have habs := abs_le.mp (le_trans herr hbound)
  have hmid := seg13_im_midpoint_sum_upper σ hσ0 hσ1
  have hscale : ((45/32 : ℝ) - 11/8) / (10 : ℕ) = ((1/320 : ℝ)) := by push_cast; norm_num
  rw [hscale] at habs
  linarith [habs.2, hmid]

end PrincipiaTractalis.RiemannXiBox114Panels.Seg13
