/-
# PF.Numerics.Box113Seg30M

M certificate for OPT-40-TIGHT segment 30:  L = 21/8, MHI = 754000000042800000000000000159/10000000000000000000000000000000.
Auto-generated by scripts/emit_stage2_segment.py.

T_0 ≈ 3.7604e-02   B0 = 377/10000
T_1 ≈ 2.1306e-12   B1 = 107/50000000000000
T_2 ≈ 7.9408e-30   B2 = 159/20000000000000000000000000000000
2·(B0+B1+B2) = 754000000042800000000000000159/10000000000000000000000000000000 ≤ 754000000042800000000000000159/10000000000000000000000000000000

SPDX-License-Identifier: Apache-2.0
-/

import PF.Analytic.RiemannXiThetaRealFormAndBoxes_r331b
import PF.Analytic.RiemannXiBoxParametric
import Interval.Interval.Conversion
import Interval.Interval.Exp
import Interval.Interval.Pi
import Interval.Interval.Order
import Interval.Interval.Mul
import Interval.Tactic.Approx

namespace PrincipiaTractalis.Box113Seg30M

open scoped Real
open PrincipiaTractalis.RiemannXiThetaRealFormAndBoxes

theorem seg30_T0_closed :
    thetaPowTermM 15 (125/128) (31625/16384) (21/8) 0
      = Real.exp (-(π * (21/8))) * ((1316105/16384 : ℝ) + π * π + (1085/64 : ℝ) * π) := by
  unfold thetaPowTermM
  have h_abs : |(15 : ℝ)| = 15 := by rw [abs_of_pos]; norm_num
  simp only [Nat.cast_zero, zero_add, h_abs, one_pow]
  ring

theorem seg30_T1_closed :
    thetaPowTermM 15 (125/128) (31625/16384) (21/8) 1
      = Real.exp (-(π * (21/2))) * ((1316105/16384 : ℝ) + 16 * (π * π) + (1085/16 : ℝ) * π) := by
  unfold thetaPowTermM
  have h_abs : |(15 : ℝ)| = 15 := by rw [abs_of_pos]; norm_num
  simp only [Nat.cast_one, h_abs]
  ring

theorem seg30_T2_closed :
    thetaPowTermM 15 (125/128) (31625/16384) (21/8) 2
      = Real.exp (-(π * (189/8))) * ((1316105/16384 : ℝ) + 81 * (π * π) + (9765/64 : ℝ) * π) := by
  unfold thetaPowTermM
  have h_abs : |(15 : ℝ)| = 15 := by rw [abs_of_pos]; norm_num
  simp only [Nat.cast_ofNat, h_abs]
  ring

noncomputable def T0_mirror : _root_.Interval :=
  _root_.Interval.exp (-(_root_.Interval.pi * _root_.Interval.ofRat (21/8))) *
    (_root_.Interval.ofRat (1316105/16384)
     + _root_.Interval.pi * _root_.Interval.pi
     + _root_.Interval.ofRat (1085/64) * _root_.Interval.pi)

noncomputable def T1_mirror : _root_.Interval :=
  _root_.Interval.exp (-(_root_.Interval.pi * _root_.Interval.ofRat (21/2))) *
    (_root_.Interval.ofRat (1316105/16384)
     + (16 : _root_.Interval) * (_root_.Interval.pi * _root_.Interval.pi)
     + _root_.Interval.ofRat (1085/16) * _root_.Interval.pi)

noncomputable def T2_mirror : _root_.Interval :=
  _root_.Interval.exp (-(_root_.Interval.pi * _root_.Interval.ofRat (189/8))) *
    (_root_.Interval.ofRat (1316105/16384)
     + (81 : _root_.Interval) * (_root_.Interval.pi * _root_.Interval.pi)
     + _root_.Interval.ofRat (9765/64) * _root_.Interval.pi)

theorem seg30_T0_lt : thetaPowTermM 15 (125/128) (31625/16384) (21/8) 0 < (377/10000 : ℝ) := by
  rw [seg30_T0_closed]
  refine _root_.Interval.approx_lt
    T0_mirror
    (377/10000 : _root_.Interval)
    (Real.exp (-(π * (21/8))) * ((1316105/16384 : ℝ) + π * π + (1085/64 : ℝ) * π))
    (377/10000 : ℝ)
    ?_
    (by approx)
    ?_
  · unfold T0_mirror
    approx
  · decide +kernel

theorem seg30_T1_lt : thetaPowTermM 15 (125/128) (31625/16384) (21/8) 1 < (107/50000000000000 : ℝ) := by
  rw [seg30_T1_closed]
  refine _root_.Interval.approx_lt
    T1_mirror
    (107/50000000000000 : _root_.Interval)
    (Real.exp (-(π * (21/2))) * ((1316105/16384 : ℝ) + 16 * (π * π) + (1085/16 : ℝ) * π))
    (107/50000000000000 : ℝ)
    ?_
    (by approx)
    ?_
  · unfold T1_mirror
    approx
  · decide +kernel

theorem seg30_T2_lt : thetaPowTermM 15 (125/128) (31625/16384) (21/8) 2 < (159/20000000000000000000000000000000 : ℝ) := by
  rw [seg30_T2_closed]
  refine _root_.Interval.approx_lt
    T2_mirror
    (159/20000000000000000000000000000000 : _root_.Interval)
    (Real.exp (-(π * (189/8))) * ((1316105/16384 : ℝ) + 81 * (π * π) + (9765/64 : ℝ) * π))
    (159/20000000000000000000000000000000 : ℝ)
    ?_
    (by approx)
    ?_
  · unfold T2_mirror
    approx
  · decide +kernel

theorem seg30_M_expand :
    2 * ∑ n ∈ Finset.range 3, thetaPowTermM 15 (125/128) (31625/16384) (21/8) n
      = 2 * (thetaPowTermM 15 (125/128) (31625/16384) (21/8) 0
             + thetaPowTermM 15 (125/128) (31625/16384) (21/8) 1
             + thetaPowTermM 15 (125/128) (31625/16384) (21/8) 2) := by
  simp [Finset.sum_range_succ]

theorem box113_seg30_M_le_MHI :
    2 * ∑ n ∈ Finset.range 3, thetaPowTermM 15 (125/128) (31625/16384) (21/8) n
      ≤ (754000000042800000000000000159/10000000000000000000000000000000 : ℝ) := by
  rw [seg30_M_expand]
  have h0 := seg30_T0_lt
  have h1 := seg30_T1_lt
  have h2 := seg30_T2_lt
  linarith

end PrincipiaTractalis.Box113Seg30M
