/-
# PF.Numerics.Box110Seg23M

M certificate for OPT-40-TIGHT segment 23:  L = 15/8, MHI = 3960000264000000000129/5000000000000000000000.
Auto-generated by scripts/emit_stage2_segment.py.

T_0 ≈ 3.9518e-01   B0 = 99/250
T_1 ≈ 2.6342e-08   B1 = 33/1250000000
T_2 ≈ 1.2848e-20   B2 = 129/10000000000000000000000
2·(B0+B1+B2) = 3960000264000000000129/5000000000000000000000 ≤ 3960000264000000000129/5000000000000000000000

SPDX-License-Identifier: Apache-2.0
-/

import PF.Analytic.RiemannXiThetaRealFormAndBoxes_r331b
import PF.Analytic.RiemannXiBoxParametric
import Interval.Interval.Conversion
import Interval.Interval.Exp
import Interval.Interval.Pi
import Interval.Interval.Order
import Interval.Interval.Mul
import Interval.Tactic.Approx

namespace PrincipiaTractalis.Box110Seg23M

open scoped Real
open PrincipiaTractalis.RiemannXiThetaRealFormAndBoxes

theorem seg23_T0_closed :
    thetaPowTermM 15 (61/64) (7625/4096) (15/8) 0
      = Real.exp (-(π * (15/8))) * ((327305/4096 : ℝ) + π * π + (541/32 : ℝ) * π) := by
  unfold thetaPowTermM
  have h_abs : |(15 : ℝ)| = 15 := by rw [abs_of_pos]; norm_num
  simp only [Nat.cast_zero, zero_add, h_abs, one_pow]
  ring

theorem seg23_T1_closed :
    thetaPowTermM 15 (61/64) (7625/4096) (15/8) 1
      = Real.exp (-(π * (15/2))) * ((327305/4096 : ℝ) + 16 * (π * π) + (541/8 : ℝ) * π) := by
  unfold thetaPowTermM
  have h_abs : |(15 : ℝ)| = 15 := by rw [abs_of_pos]; norm_num
  simp only [Nat.cast_one, h_abs]
  ring

theorem seg23_T2_closed :
    thetaPowTermM 15 (61/64) (7625/4096) (15/8) 2
      = Real.exp (-(π * (135/8))) * ((327305/4096 : ℝ) + 81 * (π * π) + (4869/32 : ℝ) * π) := by
  unfold thetaPowTermM
  have h_abs : |(15 : ℝ)| = 15 := by rw [abs_of_pos]; norm_num
  simp only [Nat.cast_ofNat, h_abs]
  ring

noncomputable def T0_mirror : _root_.Interval :=
  _root_.Interval.exp (-(_root_.Interval.pi * _root_.Interval.ofRat (15/8))) *
    (_root_.Interval.ofRat (327305/4096)
     + _root_.Interval.pi * _root_.Interval.pi
     + _root_.Interval.ofRat (541/32) * _root_.Interval.pi)

noncomputable def T1_mirror : _root_.Interval :=
  _root_.Interval.exp (-(_root_.Interval.pi * _root_.Interval.ofRat (15/2))) *
    (_root_.Interval.ofRat (327305/4096)
     + (16 : _root_.Interval) * (_root_.Interval.pi * _root_.Interval.pi)
     + _root_.Interval.ofRat (541/8) * _root_.Interval.pi)

noncomputable def T2_mirror : _root_.Interval :=
  _root_.Interval.exp (-(_root_.Interval.pi * _root_.Interval.ofRat (135/8))) *
    (_root_.Interval.ofRat (327305/4096)
     + (81 : _root_.Interval) * (_root_.Interval.pi * _root_.Interval.pi)
     + _root_.Interval.ofRat (4869/32) * _root_.Interval.pi)

theorem seg23_T0_lt : thetaPowTermM 15 (61/64) (7625/4096) (15/8) 0 < (99/250 : ℝ) := by
  rw [seg23_T0_closed]
  refine _root_.Interval.approx_lt
    T0_mirror
    (99/250 : _root_.Interval)
    (Real.exp (-(π * (15/8))) * ((327305/4096 : ℝ) + π * π + (541/32 : ℝ) * π))
    (99/250 : ℝ)
    ?_
    (by approx)
    ?_
  · unfold T0_mirror
    approx
  · decide +kernel

theorem seg23_T1_lt : thetaPowTermM 15 (61/64) (7625/4096) (15/8) 1 < (33/1250000000 : ℝ) := by
  rw [seg23_T1_closed]
  refine _root_.Interval.approx_lt
    T1_mirror
    (33/1250000000 : _root_.Interval)
    (Real.exp (-(π * (15/2))) * ((327305/4096 : ℝ) + 16 * (π * π) + (541/8 : ℝ) * π))
    (33/1250000000 : ℝ)
    ?_
    (by approx)
    ?_
  · unfold T1_mirror
    approx
  · decide +kernel

theorem seg23_T2_lt : thetaPowTermM 15 (61/64) (7625/4096) (15/8) 2 < (129/10000000000000000000000 : ℝ) := by
  rw [seg23_T2_closed]
  refine _root_.Interval.approx_lt
    T2_mirror
    (129/10000000000000000000000 : _root_.Interval)
    (Real.exp (-(π * (135/8))) * ((327305/4096 : ℝ) + 81 * (π * π) + (4869/32 : ℝ) * π))
    (129/10000000000000000000000 : ℝ)
    ?_
    (by approx)
    ?_
  · unfold T2_mirror
    approx
  · decide +kernel

theorem seg23_M_expand :
    2 * ∑ n ∈ Finset.range 3, thetaPowTermM 15 (61/64) (7625/4096) (15/8) n
      = 2 * (thetaPowTermM 15 (61/64) (7625/4096) (15/8) 0
             + thetaPowTermM 15 (61/64) (7625/4096) (15/8) 1
             + thetaPowTermM 15 (61/64) (7625/4096) (15/8) 2) := by
  simp [Finset.sum_range_succ]

theorem box110_seg23_M_le_MHI :
    2 * ∑ n ∈ Finset.range 3, thetaPowTermM 15 (61/64) (7625/4096) (15/8) n
      ≤ (3960000264000000000129/5000000000000000000000 : ℝ) := by
  rw [seg23_M_expand]
  have h0 := seg23_T0_lt
  have h1 := seg23_T1_lt
  have h2 := seg23_T2_lt
  linarith

end PrincipiaTractalis.Box110Seg23M
