/-
# PF.Numerics.Box113Seg05M

M certificate for OPT-40-TIGHT segment 5:  L = 9/8, MHI = 41893280000209/5000000000000.
Auto-generated by scripts/emit_stage2_segment.py.

T_0 ≈ 4.1860e+00   B0 = 4189/1000
T_1 ≈ 3.2716e-04   B1 = 41/125000
T_2 ≈ 2.0842e-11   B2 = 209/10000000000000
2·(B0+B1+B2) = 41893280000209/5000000000000 ≤ 41893280000209/5000000000000

SPDX-License-Identifier: Apache-2.0
-/

import PF.Analytic.RiemannXiThetaRealFormAndBoxes_r331b
import PF.Analytic.RiemannXiBoxParametric
import Interval.Interval.Conversion
import Interval.Interval.Exp
import Interval.Interval.Pi
import Interval.Interval.Order
import Interval.Interval.Mul
import Interval.Tactic.Approx

namespace PrincipiaTractalis.Box113Seg05M

open scoped Real
open PrincipiaTractalis.RiemannXiThetaRealFormAndBoxes

theorem seg5_T0_closed :
    thetaPowTermM 15 (125/128) (31625/16384) (9/8) 0
      = Real.exp (-(π * (9/8))) * ((1316105/16384 : ℝ) + π * π + (1085/64 : ℝ) * π) := by
  unfold thetaPowTermM
  have h_abs : |(15 : ℝ)| = 15 := by rw [abs_of_pos]; norm_num
  simp only [Nat.cast_zero, zero_add, h_abs, one_pow]
  ring

theorem seg5_T1_closed :
    thetaPowTermM 15 (125/128) (31625/16384) (9/8) 1
      = Real.exp (-(π * (9/2))) * ((1316105/16384 : ℝ) + 16 * (π * π) + (1085/16 : ℝ) * π) := by
  unfold thetaPowTermM
  have h_abs : |(15 : ℝ)| = 15 := by rw [abs_of_pos]; norm_num
  simp only [Nat.cast_one, h_abs]
  ring

theorem seg5_T2_closed :
    thetaPowTermM 15 (125/128) (31625/16384) (9/8) 2
      = Real.exp (-(π * (81/8))) * ((1316105/16384 : ℝ) + 81 * (π * π) + (9765/64 : ℝ) * π) := by
  unfold thetaPowTermM
  have h_abs : |(15 : ℝ)| = 15 := by rw [abs_of_pos]; norm_num
  simp only [Nat.cast_ofNat, h_abs]
  ring

noncomputable def T0_mirror : _root_.Interval :=
  _root_.Interval.exp (-(_root_.Interval.pi * _root_.Interval.ofRat (9/8))) *
    (_root_.Interval.ofRat (1316105/16384)
     + _root_.Interval.pi * _root_.Interval.pi
     + _root_.Interval.ofRat (1085/64) * _root_.Interval.pi)

noncomputable def T1_mirror : _root_.Interval :=
  _root_.Interval.exp (-(_root_.Interval.pi * _root_.Interval.ofRat (9/2))) *
    (_root_.Interval.ofRat (1316105/16384)
     + (16 : _root_.Interval) * (_root_.Interval.pi * _root_.Interval.pi)
     + _root_.Interval.ofRat (1085/16) * _root_.Interval.pi)

noncomputable def T2_mirror : _root_.Interval :=
  _root_.Interval.exp (-(_root_.Interval.pi * _root_.Interval.ofRat (81/8))) *
    (_root_.Interval.ofRat (1316105/16384)
     + (81 : _root_.Interval) * (_root_.Interval.pi * _root_.Interval.pi)
     + _root_.Interval.ofRat (9765/64) * _root_.Interval.pi)

theorem seg5_T0_lt : thetaPowTermM 15 (125/128) (31625/16384) (9/8) 0 < (4189/1000 : ℝ) := by
  rw [seg5_T0_closed]
  refine _root_.Interval.approx_lt
    T0_mirror
    (4189/1000 : _root_.Interval)
    (Real.exp (-(π * (9/8))) * ((1316105/16384 : ℝ) + π * π + (1085/64 : ℝ) * π))
    (4189/1000 : ℝ)
    ?_
    (by approx)
    ?_
  · unfold T0_mirror
    approx
  · decide +kernel

theorem seg5_T1_lt : thetaPowTermM 15 (125/128) (31625/16384) (9/8) 1 < (41/125000 : ℝ) := by
  rw [seg5_T1_closed]
  refine _root_.Interval.approx_lt
    T1_mirror
    (41/125000 : _root_.Interval)
    (Real.exp (-(π * (9/2))) * ((1316105/16384 : ℝ) + 16 * (π * π) + (1085/16 : ℝ) * π))
    (41/125000 : ℝ)
    ?_
    (by approx)
    ?_
  · unfold T1_mirror
    approx
  · decide +kernel

theorem seg5_T2_lt : thetaPowTermM 15 (125/128) (31625/16384) (9/8) 2 < (209/10000000000000 : ℝ) := by
  rw [seg5_T2_closed]
  refine _root_.Interval.approx_lt
    T2_mirror
    (209/10000000000000 : _root_.Interval)
    (Real.exp (-(π * (81/8))) * ((1316105/16384 : ℝ) + 81 * (π * π) + (9765/64 : ℝ) * π))
    (209/10000000000000 : ℝ)
    ?_
    (by approx)
    ?_
  · unfold T2_mirror
    approx
  · decide +kernel

theorem seg5_M_expand :
    2 * ∑ n ∈ Finset.range 3, thetaPowTermM 15 (125/128) (31625/16384) (9/8) n
      = 2 * (thetaPowTermM 15 (125/128) (31625/16384) (9/8) 0
             + thetaPowTermM 15 (125/128) (31625/16384) (9/8) 1
             + thetaPowTermM 15 (125/128) (31625/16384) (9/8) 2) := by
  simp [Finset.sum_range_succ]

theorem box113_seg5_M_le_MHI :
    2 * ∑ n ∈ Finset.range 3, thetaPowTermM 15 (125/128) (31625/16384) (9/8) n
      ≤ (41893280000209/5000000000000 : ℝ) := by
  rw [seg5_M_expand]
  have h0 := seg5_T0_lt
  have h1 := seg5_T1_lt
  have h2 := seg5_T2_lt
  linarith

end PrincipiaTractalis.Box113Seg05M
