/-
# PF.Numerics.Box109Seg30M

M certificate for OPT-40-TIGHT segment 30:  L = 21/8, MHI = 1875000000106500000000000000397/25000000000000000000000000000000.
Auto-generated by scripts/emit_stage2_segment.py.

T_0 ≈ 3.7406e-02   B0 = 3/80
T_1 ≈ 2.1242e-12   B1 = 213/100000000000000
T_2 ≈ 7.9272e-30   B2 = 397/50000000000000000000000000000000
2·(B0+B1+B2) = 1875000000106500000000000000397/25000000000000000000000000000000 ≤ 1875000000106500000000000000397/25000000000000000000000000000000

SPDX-License-Identifier: Apache-2.0
-/

import PF.Analytic.RiemannXiThetaRealFormAndBoxes_r331b
import PF.Analytic.RiemannXiBoxParametric
import Interval.Interval.Conversion
import Interval.Interval.Exp
import Interval.Interval.Pi
import Interval.Interval.Order
import Interval.Interval.Mul
import Interval.Tactic.Approx

namespace PrincipiaTractalis.Box109Seg30M

open scoped Real
open PrincipiaTractalis.RiemannXiThetaRealFormAndBoxes

theorem seg30_T0_closed :
    thetaPowTermM 15 (121/128) (30129/16384) (21/8) 0
      = Real.exp (-(π * (21/8))) * ((1306929/16384 : ℝ) + π * π + (1081/64 : ℝ) * π) := by
  unfold thetaPowTermM
  have h_abs : |(15 : ℝ)| = 15 := by rw [abs_of_pos]; norm_num
  simp only [Nat.cast_zero, zero_add, h_abs, one_pow]
  ring

theorem seg30_T1_closed :
    thetaPowTermM 15 (121/128) (30129/16384) (21/8) 1
      = Real.exp (-(π * (21/2))) * ((1306929/16384 : ℝ) + 16 * (π * π) + (1081/16 : ℝ) * π) := by
  unfold thetaPowTermM
  have h_abs : |(15 : ℝ)| = 15 := by rw [abs_of_pos]; norm_num
  simp only [Nat.cast_one, h_abs]
  ring

theorem seg30_T2_closed :
    thetaPowTermM 15 (121/128) (30129/16384) (21/8) 2
      = Real.exp (-(π * (189/8))) * ((1306929/16384 : ℝ) + 81 * (π * π) + (9729/64 : ℝ) * π) := by
  unfold thetaPowTermM
  have h_abs : |(15 : ℝ)| = 15 := by rw [abs_of_pos]; norm_num
  simp only [Nat.cast_ofNat, h_abs]
  ring

noncomputable def T0_mirror : _root_.Interval :=
  _root_.Interval.exp (-(_root_.Interval.pi * _root_.Interval.ofRat (21/8))) *
    (_root_.Interval.ofRat (1306929/16384)
     + _root_.Interval.pi * _root_.Interval.pi
     + _root_.Interval.ofRat (1081/64) * _root_.Interval.pi)

noncomputable def T1_mirror : _root_.Interval :=
  _root_.Interval.exp (-(_root_.Interval.pi * _root_.Interval.ofRat (21/2))) *
    (_root_.Interval.ofRat (1306929/16384)
     + (16 : _root_.Interval) * (_root_.Interval.pi * _root_.Interval.pi)
     + _root_.Interval.ofRat (1081/16) * _root_.Interval.pi)

noncomputable def T2_mirror : _root_.Interval :=
  _root_.Interval.exp (-(_root_.Interval.pi * _root_.Interval.ofRat (189/8))) *
    (_root_.Interval.ofRat (1306929/16384)
     + (81 : _root_.Interval) * (_root_.Interval.pi * _root_.Interval.pi)
     + _root_.Interval.ofRat (9729/64) * _root_.Interval.pi)

theorem seg30_T0_lt : thetaPowTermM 15 (121/128) (30129/16384) (21/8) 0 < (3/80 : ℝ) := by
  rw [seg30_T0_closed]
  refine _root_.Interval.approx_lt
    T0_mirror
    (3/80 : _root_.Interval)
    (Real.exp (-(π * (21/8))) * ((1306929/16384 : ℝ) + π * π + (1081/64 : ℝ) * π))
    (3/80 : ℝ)
    ?_
    (by approx)
    ?_
  · unfold T0_mirror
    approx
  · decide +kernel

theorem seg30_T1_lt : thetaPowTermM 15 (121/128) (30129/16384) (21/8) 1 < (213/100000000000000 : ℝ) := by
  rw [seg30_T1_closed]
  refine _root_.Interval.approx_lt
    T1_mirror
    (213/100000000000000 : _root_.Interval)
    (Real.exp (-(π * (21/2))) * ((1306929/16384 : ℝ) + 16 * (π * π) + (1081/16 : ℝ) * π))
    (213/100000000000000 : ℝ)
    ?_
    (by approx)
    ?_
  · unfold T1_mirror
    approx
  · decide +kernel

theorem seg30_T2_lt : thetaPowTermM 15 (121/128) (30129/16384) (21/8) 2 < (397/50000000000000000000000000000000 : ℝ) := by
  rw [seg30_T2_closed]
  refine _root_.Interval.approx_lt
    T2_mirror
    (397/50000000000000000000000000000000 : _root_.Interval)
    (Real.exp (-(π * (189/8))) * ((1306929/16384 : ℝ) + 81 * (π * π) + (9729/64 : ℝ) * π))
    (397/50000000000000000000000000000000 : ℝ)
    ?_
    (by approx)
    ?_
  · unfold T2_mirror
    approx
  · decide +kernel

theorem seg30_M_expand :
    2 * ∑ n ∈ Finset.range 3, thetaPowTermM 15 (121/128) (30129/16384) (21/8) n
      = 2 * (thetaPowTermM 15 (121/128) (30129/16384) (21/8) 0
             + thetaPowTermM 15 (121/128) (30129/16384) (21/8) 1
             + thetaPowTermM 15 (121/128) (30129/16384) (21/8) 2) := by
  simp [Finset.sum_range_succ]

theorem box109_seg30_M_le_MHI :
    2 * ∑ n ∈ Finset.range 3, thetaPowTermM 15 (121/128) (30129/16384) (21/8) n
      ≤ (1875000000106500000000000000397/25000000000000000000000000000000 : ℝ) := by
  rw [seg30_M_expand]
  have h0 := seg30_T0_lt
  have h1 := seg30_T1_lt
  have h2 := seg30_T2_lt
  linarith

end PrincipiaTractalis.Box109Seg30M
