/-
# PF.Numerics.Box106Seg20M

M certificate for OPT-40-TIGHT segment 20:  L = 27/16, MHI = 35450013900000000129/25000000000000000000.
Auto-generated by scripts/emit_stage2_segment.py.

T_0 ≈ 7.0846e-01   B0 = 709/1000
T_1 ≈ 2.7710e-07   B1 = 139/500000000
T_2 ≈ 2.5733e-18   B2 = 129/50000000000000000000
2·(B0+B1+B2) = 35450013900000000129/25000000000000000000 ≤ 35450013900000000129/25000000000000000000

SPDX-License-Identifier: Apache-2.0
-/

import PF.Analytic.RiemannXiThetaRealFormAndBoxes_r331b
import PF.Analytic.RiemannXiBoxParametric
import Interval.Interval.Conversion
import Interval.Interval.Exp
import Interval.Interval.Pi
import Interval.Interval.Order
import Interval.Interval.Mul
import Interval.Tactic.Approx

namespace PrincipiaTractalis.Box106Seg20M

open scoped Real
open PrincipiaTractalis.RiemannXiThetaRealFormAndBoxes

theorem seg20_T0_closed :
    thetaPowTermM 15 (59/64) (7257/4096) (27/16) 0
      = Real.exp (-(π * (27/16))) * ((325017/4096 : ℝ) + π * π + (539/32 : ℝ) * π) := by
  unfold thetaPowTermM
  have h_abs : |(15 : ℝ)| = 15 := by rw [abs_of_pos]; norm_num
  simp only [Nat.cast_zero, zero_add, h_abs, one_pow]
  ring

theorem seg20_T1_closed :
    thetaPowTermM 15 (59/64) (7257/4096) (27/16) 1
      = Real.exp (-(π * (27/4))) * ((325017/4096 : ℝ) + 16 * (π * π) + (539/8 : ℝ) * π) := by
  unfold thetaPowTermM
  have h_abs : |(15 : ℝ)| = 15 := by rw [abs_of_pos]; norm_num
  simp only [Nat.cast_one, h_abs]
  ring

theorem seg20_T2_closed :
    thetaPowTermM 15 (59/64) (7257/4096) (27/16) 2
      = Real.exp (-(π * (243/16))) * ((325017/4096 : ℝ) + 81 * (π * π) + (4851/32 : ℝ) * π) := by
  unfold thetaPowTermM
  have h_abs : |(15 : ℝ)| = 15 := by rw [abs_of_pos]; norm_num
  simp only [Nat.cast_ofNat, h_abs]
  ring

noncomputable def T0_mirror : _root_.Interval :=
  _root_.Interval.exp (-(_root_.Interval.pi * _root_.Interval.ofRat (27/16))) *
    (_root_.Interval.ofRat (325017/4096)
     + _root_.Interval.pi * _root_.Interval.pi
     + _root_.Interval.ofRat (539/32) * _root_.Interval.pi)

noncomputable def T1_mirror : _root_.Interval :=
  _root_.Interval.exp (-(_root_.Interval.pi * _root_.Interval.ofRat (27/4))) *
    (_root_.Interval.ofRat (325017/4096)
     + (16 : _root_.Interval) * (_root_.Interval.pi * _root_.Interval.pi)
     + _root_.Interval.ofRat (539/8) * _root_.Interval.pi)

noncomputable def T2_mirror : _root_.Interval :=
  _root_.Interval.exp (-(_root_.Interval.pi * _root_.Interval.ofRat (243/16))) *
    (_root_.Interval.ofRat (325017/4096)
     + (81 : _root_.Interval) * (_root_.Interval.pi * _root_.Interval.pi)
     + _root_.Interval.ofRat (4851/32) * _root_.Interval.pi)

theorem seg20_T0_lt : thetaPowTermM 15 (59/64) (7257/4096) (27/16) 0 < (709/1000 : ℝ) := by
  rw [seg20_T0_closed]
  refine _root_.Interval.approx_lt
    T0_mirror
    (709/1000 : _root_.Interval)
    (Real.exp (-(π * (27/16))) * ((325017/4096 : ℝ) + π * π + (539/32 : ℝ) * π))
    (709/1000 : ℝ)
    ?_
    (by approx)
    ?_
  · unfold T0_mirror
    approx
  · decide +kernel

theorem seg20_T1_lt : thetaPowTermM 15 (59/64) (7257/4096) (27/16) 1 < (139/500000000 : ℝ) := by
  rw [seg20_T1_closed]
  refine _root_.Interval.approx_lt
    T1_mirror
    (139/500000000 : _root_.Interval)
    (Real.exp (-(π * (27/4))) * ((325017/4096 : ℝ) + 16 * (π * π) + (539/8 : ℝ) * π))
    (139/500000000 : ℝ)
    ?_
    (by approx)
    ?_
  · unfold T1_mirror
    approx
  · decide +kernel

theorem seg20_T2_lt : thetaPowTermM 15 (59/64) (7257/4096) (27/16) 2 < (129/50000000000000000000 : ℝ) := by
  rw [seg20_T2_closed]
  refine _root_.Interval.approx_lt
    T2_mirror
    (129/50000000000000000000 : _root_.Interval)
    (Real.exp (-(π * (243/16))) * ((325017/4096 : ℝ) + 81 * (π * π) + (4851/32 : ℝ) * π))
    (129/50000000000000000000 : ℝ)
    ?_
    (by approx)
    ?_
  · unfold T2_mirror
    approx
  · decide +kernel

theorem seg20_M_expand :
    2 * ∑ n ∈ Finset.range 3, thetaPowTermM 15 (59/64) (7257/4096) (27/16) n
      = 2 * (thetaPowTermM 15 (59/64) (7257/4096) (27/16) 0
             + thetaPowTermM 15 (59/64) (7257/4096) (27/16) 1
             + thetaPowTermM 15 (59/64) (7257/4096) (27/16) 2) := by
  simp [Finset.sum_range_succ]

theorem box106_seg20_M_le_MHI :
    2 * ∑ n ∈ Finset.range 3, thetaPowTermM 15 (59/64) (7257/4096) (27/16) n
      ≤ (35450013900000000129/25000000000000000000 : ℝ) := by
  rw [seg20_M_expand]
  have h0 := seg20_T0_lt
  have h1 := seg20_T1_lt
  have h2 := seg20_T2_lt
  linarith

end PrincipiaTractalis.Box106Seg20M
