/-
# PF.Numerics.Box116Seg17M

M certificate for OPT-40-TIGHT segment 17:  L = 3/2, MHI = 1295002950000000519/500000000000000000.
Auto-generated by scripts/emit_stage2_segment.py.

T_0 ≈ 1.2938e+00   B0 = 259/200
T_1 ≈ 2.9455e-06   B1 = 59/20000000
T_2 ≈ 5.1848e-16   B2 = 519/1000000000000000000
2·(B0+B1+B2) = 1295002950000000519/500000000000000000 ≤ 1295002950000000519/500000000000000000

SPDX-License-Identifier: Apache-2.0
-/

import PF.Analytic.RiemannXiThetaRealFormAndBoxes_r331b
import PF.Analytic.RiemannXiBoxParametric
import Interval.Interval.Conversion
import Interval.Interval.Exp
import Interval.Interval.Pi
import Interval.Interval.Order
import Interval.Interval.Mul
import Interval.Tactic.Approx

namespace PrincipiaTractalis.Box116Seg17M

open scoped Real
open PrincipiaTractalis.RiemannXiThetaRealFormAndBoxes

theorem seg17_T0_closed :
    thetaPowTermM 15 (1/1) (2/1) (3/2) 0
      = Real.exp (-(π * (3/2))) * ((323/4 : ℝ) + π * π + (34/2 : ℝ) * π) := by
  unfold thetaPowTermM
  have h_abs : |(15 : ℝ)| = 15 := by rw [abs_of_pos]; norm_num
  simp only [Nat.cast_zero, zero_add, h_abs, one_pow]
  ring

theorem seg17_T1_closed :
    thetaPowTermM 15 (1/1) (2/1) (3/2) 1
      = Real.exp (-(π * 6)) * ((323/4 : ℝ) + 16 * (π * π) + (136/2 : ℝ) * π) := by
  unfold thetaPowTermM
  have h_abs : |(15 : ℝ)| = 15 := by rw [abs_of_pos]; norm_num
  simp only [Nat.cast_one, h_abs]
  ring

theorem seg17_T2_closed :
    thetaPowTermM 15 (1/1) (2/1) (3/2) 2
      = Real.exp (-(π * (27/2))) * ((323/4 : ℝ) + 81 * (π * π) + (306/2 : ℝ) * π) := by
  unfold thetaPowTermM
  have h_abs : |(15 : ℝ)| = 15 := by rw [abs_of_pos]; norm_num
  simp only [Nat.cast_ofNat, h_abs]
  ring

noncomputable def T0_mirror : _root_.Interval :=
  _root_.Interval.exp (-(_root_.Interval.pi * _root_.Interval.ofRat (3/2))) *
    (_root_.Interval.ofRat (323/4)
     + _root_.Interval.pi * _root_.Interval.pi
     + _root_.Interval.ofRat (34/2) * _root_.Interval.pi)

noncomputable def T1_mirror : _root_.Interval :=
  _root_.Interval.exp (-(_root_.Interval.pi * (6 : _root_.Interval))) *
    (_root_.Interval.ofRat (323/4)
     + (16 : _root_.Interval) * (_root_.Interval.pi * _root_.Interval.pi)
     + _root_.Interval.ofRat (136/2) * _root_.Interval.pi)

noncomputable def T2_mirror : _root_.Interval :=
  _root_.Interval.exp (-(_root_.Interval.pi * _root_.Interval.ofRat (27/2))) *
    (_root_.Interval.ofRat (323/4)
     + (81 : _root_.Interval) * (_root_.Interval.pi * _root_.Interval.pi)
     + _root_.Interval.ofRat (306/2) * _root_.Interval.pi)

theorem seg17_T0_lt : thetaPowTermM 15 (1/1) (2/1) (3/2) 0 < (259/200 : ℝ) := by
  rw [seg17_T0_closed]
  refine _root_.Interval.approx_lt
    T0_mirror
    (259/200 : _root_.Interval)
    (Real.exp (-(π * (3/2))) * ((323/4 : ℝ) + π * π + (34/2 : ℝ) * π))
    (259/200 : ℝ)
    ?_
    (by approx)
    ?_
  · unfold T0_mirror
    approx
  · decide +kernel

theorem seg17_T1_lt : thetaPowTermM 15 (1/1) (2/1) (3/2) 1 < (59/20000000 : ℝ) := by
  rw [seg17_T1_closed]
  refine _root_.Interval.approx_lt
    T1_mirror
    (59/20000000 : _root_.Interval)
    (Real.exp (-(π * 6)) * ((323/4 : ℝ) + 16 * (π * π) + (136/2 : ℝ) * π))
    (59/20000000 : ℝ)
    ?_
    (by approx)
    ?_
  · unfold T1_mirror
    approx
  · decide +kernel

theorem seg17_T2_lt : thetaPowTermM 15 (1/1) (2/1) (3/2) 2 < (519/1000000000000000000 : ℝ) := by
  rw [seg17_T2_closed]
  refine _root_.Interval.approx_lt
    T2_mirror
    (519/1000000000000000000 : _root_.Interval)
    (Real.exp (-(π * (27/2))) * ((323/4 : ℝ) + 81 * (π * π) + (306/2 : ℝ) * π))
    (519/1000000000000000000 : ℝ)
    ?_
    (by approx)
    ?_
  · unfold T2_mirror
    approx
  · decide +kernel

theorem seg17_M_expand :
    2 * ∑ n ∈ Finset.range 3, thetaPowTermM 15 (1/1) (2/1) (3/2) n
      = 2 * (thetaPowTermM 15 (1/1) (2/1) (3/2) 0
             + thetaPowTermM 15 (1/1) (2/1) (3/2) 1
             + thetaPowTermM 15 (1/1) (2/1) (3/2) 2) := by
  simp [Finset.sum_range_succ]

theorem box116_seg17_M_le_MHI :
    2 * ∑ n ∈ Finset.range 3, thetaPowTermM 15 (1/1) (2/1) (3/2) n
      ≤ (1295002950000000519/500000000000000000 : ℝ) := by
  rw [seg17_M_expand]
  have h0 := seg17_T0_lt
  have h1 := seg17_T1_lt
  have h2 := seg17_T2_lt
  linarith

end PrincipiaTractalis.Box116Seg17M
