/-
# PF.Numerics.Box108Seg21M

M certificate for OPT-40-TIGHT segment 21:  L = 7/4, MHI = 584000127000000000441/500000000000000000000.
Auto-generated by scripts/emit_stage2_segment.py.

T_0 ≈ 5.8371e-01   B0 = 73/125
T_1 ≈ 1.2653e-07   B1 = 127/1000000000
T_2 ≈ 4.3994e-19   B2 = 441/1000000000000000000000
2·(B0+B1+B2) = 584000127000000000441/500000000000000000000 ≤ 584000127000000000441/500000000000000000000

SPDX-License-Identifier: Apache-2.0
-/

import PF.Analytic.RiemannXiThetaRealFormAndBoxes_r331b
import PF.Analytic.RiemannXiBoxParametric
import Interval.Interval.Conversion
import Interval.Interval.Exp
import Interval.Interval.Pi
import Interval.Interval.Order
import Interval.Interval.Mul
import Interval.Tactic.Approx

namespace PrincipiaTractalis.Box108Seg21M

open scoped Real
open PrincipiaTractalis.RiemannXiThetaRealFormAndBoxes

theorem seg21_T0_closed :
    thetaPowTermM 15 (15/16) (465/256) (7/4) 0
      = Real.exp (-(π * (7/4))) * ((20385/256 : ℝ) + π * π + (135/8 : ℝ) * π) := by
  unfold thetaPowTermM
  have h_abs : |(15 : ℝ)| = 15 := by rw [abs_of_pos]; norm_num
  simp only [Nat.cast_zero, zero_add, h_abs, one_pow]
  ring

theorem seg21_T1_closed :
    thetaPowTermM 15 (15/16) (465/256) (7/4) 1
      = Real.exp (-(π * 7)) * ((20385/256 : ℝ) + 16 * (π * π) + (135/2 : ℝ) * π) := by
  unfold thetaPowTermM
  have h_abs : |(15 : ℝ)| = 15 := by rw [abs_of_pos]; norm_num
  simp only [Nat.cast_one, h_abs]
  ring

theorem seg21_T2_closed :
    thetaPowTermM 15 (15/16) (465/256) (7/4) 2
      = Real.exp (-(π * (63/4))) * ((20385/256 : ℝ) + 81 * (π * π) + (1215/8 : ℝ) * π) := by
  unfold thetaPowTermM
  have h_abs : |(15 : ℝ)| = 15 := by rw [abs_of_pos]; norm_num
  simp only [Nat.cast_ofNat, h_abs]
  ring

noncomputable def T0_mirror : _root_.Interval :=
  _root_.Interval.exp (-(_root_.Interval.pi * _root_.Interval.ofRat (7/4))) *
    (_root_.Interval.ofRat (20385/256)
     + _root_.Interval.pi * _root_.Interval.pi
     + _root_.Interval.ofRat (135/8) * _root_.Interval.pi)

noncomputable def T1_mirror : _root_.Interval :=
  _root_.Interval.exp (-(_root_.Interval.pi * (7 : _root_.Interval))) *
    (_root_.Interval.ofRat (20385/256)
     + (16 : _root_.Interval) * (_root_.Interval.pi * _root_.Interval.pi)
     + _root_.Interval.ofRat (135/2) * _root_.Interval.pi)

noncomputable def T2_mirror : _root_.Interval :=
  _root_.Interval.exp (-(_root_.Interval.pi * _root_.Interval.ofRat (63/4))) *
    (_root_.Interval.ofRat (20385/256)
     + (81 : _root_.Interval) * (_root_.Interval.pi * _root_.Interval.pi)
     + _root_.Interval.ofRat (1215/8) * _root_.Interval.pi)

theorem seg21_T0_lt : thetaPowTermM 15 (15/16) (465/256) (7/4) 0 < (73/125 : ℝ) := by
  rw [seg21_T0_closed]
  refine _root_.Interval.approx_lt
    T0_mirror
    (73/125 : _root_.Interval)
    (Real.exp (-(π * (7/4))) * ((20385/256 : ℝ) + π * π + (135/8 : ℝ) * π))
    (73/125 : ℝ)
    ?_
    (by approx)
    ?_
  · unfold T0_mirror
    approx
  · decide +kernel

theorem seg21_T1_lt : thetaPowTermM 15 (15/16) (465/256) (7/4) 1 < (127/1000000000 : ℝ) := by
  rw [seg21_T1_closed]
  refine _root_.Interval.approx_lt
    T1_mirror
    (127/1000000000 : _root_.Interval)
    (Real.exp (-(π * 7)) * ((20385/256 : ℝ) + 16 * (π * π) + (135/2 : ℝ) * π))
    (127/1000000000 : ℝ)
    ?_
    (by approx)
    ?_
  · unfold T1_mirror
    approx
  · decide +kernel

theorem seg21_T2_lt : thetaPowTermM 15 (15/16) (465/256) (7/4) 2 < (441/1000000000000000000000 : ℝ) := by
  rw [seg21_T2_closed]
  refine _root_.Interval.approx_lt
    T2_mirror
    (441/1000000000000000000000 : _root_.Interval)
    (Real.exp (-(π * (63/4))) * ((20385/256 : ℝ) + 81 * (π * π) + (1215/8 : ℝ) * π))
    (441/1000000000000000000000 : ℝ)
    ?_
    (by approx)
    ?_
  · unfold T2_mirror
    approx
  · decide +kernel

theorem seg21_M_expand :
    2 * ∑ n ∈ Finset.range 3, thetaPowTermM 15 (15/16) (465/256) (7/4) n
      = 2 * (thetaPowTermM 15 (15/16) (465/256) (7/4) 0
             + thetaPowTermM 15 (15/16) (465/256) (7/4) 1
             + thetaPowTermM 15 (15/16) (465/256) (7/4) 2) := by
  simp [Finset.sum_range_succ]

theorem box108_seg21_M_le_MHI :
    2 * ∑ n ∈ Finset.range 3, thetaPowTermM 15 (15/16) (465/256) (7/4) n
      ≤ (584000127000000000441/500000000000000000000 : ℝ) := by
  rw [seg21_M_expand]
  have h0 := seg21_T0_lt
  have h1 := seg21_T1_lt
  have h2 := seg21_T2_lt
  linarith

end PrincipiaTractalis.Box108Seg21M
