/-
# PF.Analytic.RiemannXiBox106Panels.Seg31P1

Panel 1 of Segment 31: nodes [0, 1, 2].
Auto-generated by scripts/emit_stage2_segment.py.
-/

import PF.Analytic.RiemannXiThetaRealFormAndBoxes_r331b
import PF.Analytic.RiemannXiBoxParametric
import Interval.Interval.Conversion
import Interval.Interval.Exp
import Interval.Interval.Log
import Interval.Interval.Sincos
import Interval.Interval.Pi
import Interval.Interval.Order
import Interval.Interval.Mul
import Interval.Tactic.Approx

namespace PrincipiaTractalis.RiemannXiBox106Panels.Seg31P1

open scoped Real
open PrincipiaTractalis.RiemannXiThetaRealFormAndBoxes
open PrincipiaTractalis.XiQuadrature

private theorem rpow_neg_eq_exp {x a : ℝ} (hx : 0 < x) :
    x ^ (-a) = Real.exp (-(Real.log x * a)) := by
  rw [Real.rpow_def_of_pos hx]; ring_nf

private theorem omegaPartial_3_closed {u : ℝ} :
    omegaPartial 3 u = Real.exp (-(π * u)) + Real.exp (-(π * 4 * u))
      + Real.exp (-(π * 9 * u)) := by
  unfold omegaPartial
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, zero_add,
             Nat.cast_zero, Nat.cast_one, Nat.cast_ofNat, one_pow]
  ring_nf

/-! ## Node 0 at u = 397/144 — cos nn, sin nn -/

private theorem u0_cos_nn : (0 : ℝ) ≤ Real.cos ((15/2 : ℝ) * Real.log (397/144 : ℝ)) := by
  refine _root_.Interval.approx_le
    ((0 : _root_.Interval))
    (_root_.Interval.cos ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((397 : ℚ)/144))))
    (0 : ℝ)
    (Real.cos ((15/2 : ℝ) * Real.log (397/144 : ℝ)))
    (by approx)
    (_root_.Interval.mem_approx_cos (by approx))
    ?_
  decide +kernel


private theorem u0_sin_nn : (0 : ℝ) ≤ Real.sin ((15/2 : ℝ) * Real.log (397/144 : ℝ)) := by
  refine _root_.Interval.approx_le
    ((0 : _root_.Interval))
    (_root_.Interval.sin ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((397 : ℚ)/144))))
    (0 : ℝ)
    (Real.sin ((15/2 : ℝ) * Real.log (397/144 : ℝ)))
    (by approx)
    (_root_.Interval.mem_approx_sin (by approx))
    ?_
  decide +kernel


private theorem u0_re_adverse_le :
    ((397/144 : ℝ) ^ (-(37/64 : ℝ)) + (397/144 : ℝ) ^ (-(59/64 : ℝ)))
        * Real.cos ((15/2 : ℝ) * Real.log (397/144 : ℝ))
        * omegaPartial 3 (397/144 : ℝ)
      ≤ (1/20000 : ℝ) := by
  have hu0 : (0 : ℝ) < (397/144 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine le_of_lt <| _root_.Interval.approx_lt
    ((_root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((397 : ℚ)/144)) * _root_.Interval.ofRat (37/64)))
      + _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((397 : ℚ)/144)) * _root_.Interval.ofRat (59/64))))
     * _root_.Interval.cos ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((397 : ℚ)/144)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((397 : ℚ)/144)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((397 : ℚ)/144)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((397 : ℚ)/144)))))
    (1/20000 : _root_.Interval)
    _
    (1/20000 : ℝ)
    ?_
    (by approx)
    ?_
  · approx
  · decide +kernel

private theorem u0_re_tight_ge :
    (201229/5000000000 : ℝ)
      ≤ ((397/144 : ℝ) ^ (-(19/32 : ℝ)) + (397/144 : ℝ) ^ (-(29/32 : ℝ)))
        * Real.cos ((15/2 : ℝ) * Real.log (397/144 : ℝ))
        * omegaPartial 3 (397/144 : ℝ) := by
  have hu0 : (0 : ℝ) < (397/144 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine _root_.Interval.approx_le
    (201229/5000000000 : _root_.Interval)
    ((_root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((397 : ℚ)/144)) * _root_.Interval.ofRat (19/32)))
      + _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((397 : ℚ)/144)) * _root_.Interval.ofRat (29/32))))
     * _root_.Interval.cos ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((397 : ℚ)/144)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((397 : ℚ)/144)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((397 : ℚ)/144)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((397 : ℚ)/144)))))
    (201229/5000000000 : ℝ)
    _
    (by approx)
    ?_
    ?_
  · approx
  · decide +kernel


private theorem u0_im_adverse_le :
    ((397/144 : ℝ) ^ (-(37/64 : ℝ)) - (397/144 : ℝ) ^ (-(59/64 : ℝ)))
      * Real.sin ((15/2 : ℝ) * Real.log (397/144 : ℝ))
      * omegaPartial 3 (397/144 : ℝ)
      ≤ (11/400000 : ℝ) := by
  have hu0 : (0 : ℝ) < (397/144 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine le_of_lt <| _root_.Interval.approx_lt
    ((_root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((397 : ℚ)/144)) * _root_.Interval.ofRat (37/64)))
      - _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((397 : ℚ)/144)) * _root_.Interval.ofRat (59/64))))
     * _root_.Interval.sin ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((397 : ℚ)/144)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((397 : ℚ)/144)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((397 : ℚ)/144)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((397 : ℚ)/144)))))
    (11/400000 : _root_.Interval)
    _
    (11/400000 : ℝ)
    ?_
    (by approx)
    ?_
  · approx
  · decide +kernel

private theorem u0_im_tight_ge :
    (249703/10000000000 : ℝ)
      ≤ ((397/144 : ℝ) ^ (-(19/32 : ℝ)) - (397/144 : ℝ) ^ (-(29/32 : ℝ)))
        * Real.sin ((15/2 : ℝ) * Real.log (397/144 : ℝ))
        * omegaPartial 3 (397/144 : ℝ) := by
  have hu0 : (0 : ℝ) < (397/144 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine _root_.Interval.approx_le
    (249703/10000000000 : _root_.Interval)
    ((_root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((397 : ℚ)/144)) * _root_.Interval.ofRat (19/32)))
      - _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((397 : ℚ)/144)) * _root_.Interval.ofRat (29/32))))
     * _root_.Interval.sin ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((397 : ℚ)/144)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((397 : ℚ)/144)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((397 : ℚ)/144)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((397 : ℚ)/144)))))
    (249703/10000000000 : ℝ)
    _
    (by approx)
    ?_
    ?_
  · approx
  · decide +kernel


theorem node_0_bounds (σ : ℝ)
    (hσ0 : (13/16 : ℝ) ≤ σ) (hσ1 : σ ≤ 27/32) :
    ((201229/5000000000 : ℝ)) ≤ realThetaReIntegrandN 3 σ 15 (397/144 : ℝ)
    ∧ realThetaReIntegrandN 3 σ 15 (397/144 : ℝ) ≤ ((1/20000 : ℝ))
    ∧ ((249703/10000000000 : ℝ)) ≤ realThetaImIntegrandN 3 σ 15 (397/144 : ℝ)
    ∧ realThetaImIntegrandN 3 σ 15 (397/144 : ℝ) ≤ ((11/400000 : ℝ)) := by
  have hu1 : (1 : ℝ) ≤ (397/144 : ℝ) := by norm_num
  have hA_nn : (0 : ℝ) ≤ (397/144 : ℝ)^(σ/2 - 1) + (397/144 : ℝ)^((1-σ)/2 - 1) :=
    box0_pow_sum_nonneg σ hu1
  have hA_hi : (397/144 : ℝ)^(σ/2 - 1) + (397/144 : ℝ)^((1-σ)/2 - 1)
      ≤ (397/144 : ℝ)^(-(37/64 : ℝ)) + (397/144 : ℝ)^(-(59/64 : ℝ)) :=
    by
    have h := PrincipiaTractalis.RiemannXiBoxParametric.box_pow_sum_ub (σhi := (27/32 : ℝ)) hu1
      (by linarith) hσ1
    have e1 : ((27/32 : ℝ))/2 - 1 = -(37/64 : ℝ) := by norm_num
    have e2 : (1 - (27/32 : ℝ))/2 - 1 = -(59/64 : ℝ) := by norm_num
    rw [e1, e2] at h; exact h
  have hD_nn : (0 : ℝ) ≤ (397/144 : ℝ)^(σ/2 - 1) - (397/144 : ℝ)^((1-σ)/2 - 1) :=
    box0_pow_diff_nonneg (by linarith) hu1
  have hD_hi : (397/144 : ℝ)^(σ/2 - 1) - (397/144 : ℝ)^((1-σ)/2 - 1)
      ≤ (397/144 : ℝ)^(-(37/64 : ℝ)) - (397/144 : ℝ)^(-(59/64 : ℝ)) :=
    by
    have h := PrincipiaTractalis.RiemannXiBoxParametric.box_pow_diff_ub (σhi := (27/32 : ℝ)) hu1 hσ1
    have e1 : ((27/32 : ℝ))/2 - 1 = -(37/64 : ℝ) := by norm_num
    have e2 : (1 - (27/32 : ℝ))/2 - 1 = -(59/64 : ℝ) := by norm_num
    rw [e1, e2] at h; exact h
  have hW_nn : (0 : ℝ) ≤ omegaPartial 3 (397/144 : ℝ) := omegaPartial_nonneg_here 3 _
  have hAstar_nn : (0 : ℝ) ≤ (397/144 : ℝ)^(-(37/64 : ℝ)) + (397/144 : ℝ)^(-(59/64 : ℝ)) := by
    have h := box0_pow_sum_nonneg ((27/32) : ℝ) hu1
    have eq1 : ((27/32 : ℝ))/2 - 1 = -(37/64 : ℝ) := by norm_num
    have eq2 : (1 - (27/32 : ℝ))/2 - 1 = -(59/64 : ℝ) := by norm_num
    rw [eq1, eq2] at h; exact h
  have hDstar_nn : (0 : ℝ) ≤ (397/144 : ℝ)^(-(37/64 : ℝ)) - (397/144 : ℝ)^(-(59/64 : ℝ)) := by
    have h := box0_pow_diff_nonneg (σ := (27/32 : ℝ)) (by norm_num) hu1
    have eq1 : ((27/32 : ℝ))/2 - 1 = -(37/64 : ℝ) := by norm_num
    have eq2 : (1 - (27/32 : ℝ))/2 - 1 = -(59/64 : ℝ) := by norm_num
    rw [eq1, eq2] at h; exact h
  have hC : Real.cos ((15/2 : ℝ) * Real.log (397/144 : ℝ)) ≥ 0 := u0_cos_nn
  have hS : Real.sin ((15/2 : ℝ) * Real.log (397/144 : ℝ)) ≥ 0 := u0_sin_nn
  have hRe := re_scalar_bounds_cos_nonneg
    (A_lo := 0)
    (A_hi := (397/144 : ℝ)^(-(37/64 : ℝ)) + (397/144 : ℝ)^(-(59/64 : ℝ)))
    (C_lo := 0)
    (C_hi := Real.cos ((15/2 : ℝ) * Real.log (397/144 : ℝ)))
    (W_lo := 0) (W_hi := omegaPartial 3 (397/144 : ℝ))
    (le_refl 0) hAstar_nn (le_refl 0) hC
    (le_refl 0) hW_nn
    hA_nn hA_hi hC (le_refl _) hW_nn (le_refl _)
  have hIm := im_scalar_bounds_sin_nonneg
    (D_lo := 0)
    (D_hi := (397/144 : ℝ)^(-(37/64 : ℝ)) - (397/144 : ℝ)^(-(59/64 : ℝ)))
    (S_lo := 0)
    (S_hi := Real.sin ((15/2 : ℝ) * Real.log (397/144 : ℝ)))
    (W_lo := 0) (W_hi := omegaPartial 3 (397/144 : ℝ))
    (le_refl 0) hDstar_nn (le_refl 0) hS
    (le_refl 0) hW_nn
    hD_nn hD_hi hS (le_refl _) hW_nn (le_refl _)
  refine ⟨?_, ?_, ?_, ?_⟩
  · unfold realThetaReIntegrandN
    have hAlo : (397/144 : ℝ)^(-(19/32 : ℝ)) + (397/144 : ℝ)^(-(29/32 : ℝ))
        ≤ (397/144 : ℝ)^(σ/2 - 1) + (397/144 : ℝ)^((1-σ)/2 - 1) :=
      by
        have h := PrincipiaTractalis.RiemannXiBoxParametric.box_pow_sum_lb
          (σlo := (13/16 : ℝ)) hu1 (by norm_num) hσ0
        have e1 : ((13/16 : ℝ))/2 - 1 = -(19/32 : ℝ) := by norm_num
        have e2 : (1 - (13/16 : ℝ))/2 - 1 = -(29/32 : ℝ) := by norm_num
        rw [e1, e2] at h; exact h
    have hCW : (0 : ℝ) ≤ Real.cos ((15/2 : ℝ) * Real.log (397/144 : ℝ))
        * omegaPartial 3 (397/144 : ℝ) := mul_nonneg hC hW_nn
    have hchain : ((397/144 : ℝ)^(-(19/32 : ℝ)) + (397/144 : ℝ)^(-(29/32 : ℝ)))
          * Real.cos ((15/2 : ℝ) * Real.log (397/144 : ℝ))
          * omegaPartial 3 (397/144 : ℝ)
        ≤ ((397/144 : ℝ)^(σ/2 - 1) + (397/144 : ℝ)^((1-σ)/2 - 1))
          * Real.cos ((15/2 : ℝ) * Real.log (397/144 : ℝ))
          * omegaPartial 3 (397/144 : ℝ) := by
      calc ((397/144 : ℝ)^(-(19/32 : ℝ)) + (397/144 : ℝ)^(-(29/32 : ℝ)))
            * Real.cos ((15/2 : ℝ) * Real.log (397/144 : ℝ))
            * omegaPartial 3 (397/144 : ℝ)
          = ((397/144 : ℝ)^(-(19/32 : ℝ)) + (397/144 : ℝ)^(-(29/32 : ℝ)))
            * (Real.cos ((15/2 : ℝ) * Real.log (397/144 : ℝ))
              * omegaPartial 3 (397/144 : ℝ)) := by ring
        _ ≤ ((397/144 : ℝ)^(σ/2 - 1) + (397/144 : ℝ)^((1-σ)/2 - 1))
            * (Real.cos ((15/2 : ℝ) * Real.log (397/144 : ℝ))
              * omegaPartial 3 (397/144 : ℝ)) :=
          mul_le_mul_of_nonneg_right hAlo hCW
        _ = ((397/144 : ℝ)^(σ/2 - 1) + (397/144 : ℝ)^((1-σ)/2 - 1))
            * Real.cos ((15/2 : ℝ) * Real.log (397/144 : ℝ))
            * omegaPartial 3 (397/144 : ℝ) := by ring
    linarith [u0_re_tight_ge, hchain]
  · unfold realThetaReIntegrandN
    linarith [hRe.2, u0_re_adverse_le]
  · unfold realThetaImIntegrandN
    have hDlo : (397/144 : ℝ)^(-(19/32 : ℝ)) - (397/144 : ℝ)^(-(29/32 : ℝ))
        ≤ (397/144 : ℝ)^(σ/2 - 1) - (397/144 : ℝ)^((1-σ)/2 - 1) := by
      have h := PrincipiaTractalis.RiemannXiBoxParametric.box_pow_diff_lb
        (σlo := (13/16 : ℝ)) hu1 hσ0
      have e1 : ((13/16 : ℝ))/2 - 1 = -(19/32 : ℝ) := by norm_num
      have e2 : (1 - (13/16 : ℝ))/2 - 1 = -(29/32 : ℝ) := by norm_num
      rw [e1, e2] at h; exact h
    have hSW : (0 : ℝ) ≤ Real.sin ((15/2 : ℝ) * Real.log (397/144 : ℝ))
        * omegaPartial 3 (397/144 : ℝ) := mul_nonneg hS hW_nn
    have hchain : ((397/144 : ℝ)^(-(19/32 : ℝ)) - (397/144 : ℝ)^(-(29/32 : ℝ)))
          * Real.sin ((15/2 : ℝ) * Real.log (397/144 : ℝ))
          * omegaPartial 3 (397/144 : ℝ)
        ≤ ((397/144 : ℝ)^(σ/2 - 1) - (397/144 : ℝ)^((1-σ)/2 - 1))
          * Real.sin ((15/2 : ℝ) * Real.log (397/144 : ℝ))
          * omegaPartial 3 (397/144 : ℝ) := by
      calc ((397/144 : ℝ)^(-(19/32 : ℝ)) - (397/144 : ℝ)^(-(29/32 : ℝ)))
            * Real.sin ((15/2 : ℝ) * Real.log (397/144 : ℝ))
            * omegaPartial 3 (397/144 : ℝ)
          = ((397/144 : ℝ)^(-(19/32 : ℝ)) - (397/144 : ℝ)^(-(29/32 : ℝ)))
            * (Real.sin ((15/2 : ℝ) * Real.log (397/144 : ℝ))
              * omegaPartial 3 (397/144 : ℝ)) := by ring
        _ ≤ ((397/144 : ℝ)^(σ/2 - 1) - (397/144 : ℝ)^((1-σ)/2 - 1))
            * (Real.sin ((15/2 : ℝ) * Real.log (397/144 : ℝ))
              * omegaPartial 3 (397/144 : ℝ)) :=
          mul_le_mul_of_nonneg_right hDlo hSW
        _ = ((397/144 : ℝ)^(σ/2 - 1) - (397/144 : ℝ)^((1-σ)/2 - 1))
            * Real.sin ((15/2 : ℝ) * Real.log (397/144 : ℝ))
            * omegaPartial 3 (397/144 : ℝ) := by ring
    linarith [u0_im_tight_ge, hchain]
  · unfold realThetaImIntegrandN
    linarith [hIm.2, u0_im_adverse_le]
/-! ## Node 1 at u = 133/48 — cos nn, sin nn -/

private theorem u1_cos_nn : (0 : ℝ) ≤ Real.cos ((15/2 : ℝ) * Real.log (133/48 : ℝ)) := by
  refine _root_.Interval.approx_le
    ((0 : _root_.Interval))
    (_root_.Interval.cos ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((133 : ℚ)/48))))
    (0 : ℝ)
    (Real.cos ((15/2 : ℝ) * Real.log (133/48 : ℝ)))
    (by approx)
    (_root_.Interval.mem_approx_cos (by approx))
    ?_
  decide +kernel


private theorem u1_sin_nn : (0 : ℝ) ≤ Real.sin ((15/2 : ℝ) * Real.log (133/48 : ℝ)) := by
  refine _root_.Interval.approx_le
    ((0 : _root_.Interval))
    (_root_.Interval.sin ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((133 : ℚ)/48))))
    (0 : ℝ)
    (Real.sin ((15/2 : ℝ) * Real.log (133/48 : ℝ)))
    (by approx)
    (_root_.Interval.mem_approx_sin (by approx))
    ?_
  decide +kernel


private theorem u1_re_adverse_le :
    ((133/48 : ℝ) ^ (-(37/64 : ℝ)) + (133/48 : ℝ) ^ (-(59/64 : ℝ)))
        * Real.cos ((15/2 : ℝ) * Real.log (133/48 : ℝ))
        * omegaPartial 3 (133/48 : ℝ)
      ≤ (1/25000 : ℝ) := by
  have hu0 : (0 : ℝ) < (133/48 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine le_of_lt <| _root_.Interval.approx_lt
    ((_root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((133 : ℚ)/48)) * _root_.Interval.ofRat (37/64)))
      + _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((133 : ℚ)/48)) * _root_.Interval.ofRat (59/64))))
     * _root_.Interval.cos ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((133 : ℚ)/48)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((133 : ℚ)/48)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((133 : ℚ)/48)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((133 : ℚ)/48)))))
    (1/25000 : _root_.Interval)
    _
    (1/25000 : ℝ)
    ?_
    (by approx)
    ?_
  · approx
  · decide +kernel

private theorem u1_re_tight_ge :
    (81623/2500000000 : ℝ)
      ≤ ((133/48 : ℝ) ^ (-(19/32 : ℝ)) + (133/48 : ℝ) ^ (-(29/32 : ℝ)))
        * Real.cos ((15/2 : ℝ) * Real.log (133/48 : ℝ))
        * omegaPartial 3 (133/48 : ℝ) := by
  have hu0 : (0 : ℝ) < (133/48 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine _root_.Interval.approx_le
    (81623/2500000000 : _root_.Interval)
    ((_root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((133 : ℚ)/48)) * _root_.Interval.ofRat (19/32)))
      + _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((133 : ℚ)/48)) * _root_.Interval.ofRat (29/32))))
     * _root_.Interval.cos ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((133 : ℚ)/48)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((133 : ℚ)/48)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((133 : ℚ)/48)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((133 : ℚ)/48)))))
    (81623/2500000000 : ℝ)
    _
    (by approx)
    ?_
    ?_
  · approx
  · decide +kernel


private theorem u1_im_adverse_le :
    ((133/48 : ℝ) ^ (-(37/64 : ℝ)) - (133/48 : ℝ) ^ (-(59/64 : ℝ)))
      * Real.sin ((15/2 : ℝ) * Real.log (133/48 : ℝ))
      * omegaPartial 3 (133/48 : ℝ)
      ≤ (133/5000000 : ℝ) := by
  have hu0 : (0 : ℝ) < (133/48 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine le_of_lt <| _root_.Interval.approx_lt
    ((_root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((133 : ℚ)/48)) * _root_.Interval.ofRat (37/64)))
      - _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((133 : ℚ)/48)) * _root_.Interval.ofRat (59/64))))
     * _root_.Interval.sin ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((133 : ℚ)/48)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((133 : ℚ)/48)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((133 : ℚ)/48)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((133 : ℚ)/48)))))
    (133/5000000 : _root_.Interval)
    _
    (133/5000000 : ℝ)
    ?_
    (by approx)
    ?_
  · approx
  · decide +kernel

private theorem u1_im_tight_ge :
    (241447/10000000000 : ℝ)
      ≤ ((133/48 : ℝ) ^ (-(19/32 : ℝ)) - (133/48 : ℝ) ^ (-(29/32 : ℝ)))
        * Real.sin ((15/2 : ℝ) * Real.log (133/48 : ℝ))
        * omegaPartial 3 (133/48 : ℝ) := by
  have hu0 : (0 : ℝ) < (133/48 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine _root_.Interval.approx_le
    (241447/10000000000 : _root_.Interval)
    ((_root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((133 : ℚ)/48)) * _root_.Interval.ofRat (19/32)))
      - _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((133 : ℚ)/48)) * _root_.Interval.ofRat (29/32))))
     * _root_.Interval.sin ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((133 : ℚ)/48)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((133 : ℚ)/48)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((133 : ℚ)/48)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((133 : ℚ)/48)))))
    (241447/10000000000 : ℝ)
    _
    (by approx)
    ?_
    ?_
  · approx
  · decide +kernel


theorem node_1_bounds (σ : ℝ)
    (hσ0 : (13/16 : ℝ) ≤ σ) (hσ1 : σ ≤ 27/32) :
    ((81623/2500000000 : ℝ)) ≤ realThetaReIntegrandN 3 σ 15 (133/48 : ℝ)
    ∧ realThetaReIntegrandN 3 σ 15 (133/48 : ℝ) ≤ ((1/25000 : ℝ))
    ∧ ((241447/10000000000 : ℝ)) ≤ realThetaImIntegrandN 3 σ 15 (133/48 : ℝ)
    ∧ realThetaImIntegrandN 3 σ 15 (133/48 : ℝ) ≤ ((133/5000000 : ℝ)) := by
  have hu1 : (1 : ℝ) ≤ (133/48 : ℝ) := by norm_num
  have hA_nn : (0 : ℝ) ≤ (133/48 : ℝ)^(σ/2 - 1) + (133/48 : ℝ)^((1-σ)/2 - 1) :=
    box0_pow_sum_nonneg σ hu1
  have hA_hi : (133/48 : ℝ)^(σ/2 - 1) + (133/48 : ℝ)^((1-σ)/2 - 1)
      ≤ (133/48 : ℝ)^(-(37/64 : ℝ)) + (133/48 : ℝ)^(-(59/64 : ℝ)) :=
    by
    have h := PrincipiaTractalis.RiemannXiBoxParametric.box_pow_sum_ub (σhi := (27/32 : ℝ)) hu1
      (by linarith) hσ1
    have e1 : ((27/32 : ℝ))/2 - 1 = -(37/64 : ℝ) := by norm_num
    have e2 : (1 - (27/32 : ℝ))/2 - 1 = -(59/64 : ℝ) := by norm_num
    rw [e1, e2] at h; exact h
  have hD_nn : (0 : ℝ) ≤ (133/48 : ℝ)^(σ/2 - 1) - (133/48 : ℝ)^((1-σ)/2 - 1) :=
    box0_pow_diff_nonneg (by linarith) hu1
  have hD_hi : (133/48 : ℝ)^(σ/2 - 1) - (133/48 : ℝ)^((1-σ)/2 - 1)
      ≤ (133/48 : ℝ)^(-(37/64 : ℝ)) - (133/48 : ℝ)^(-(59/64 : ℝ)) :=
    by
    have h := PrincipiaTractalis.RiemannXiBoxParametric.box_pow_diff_ub (σhi := (27/32 : ℝ)) hu1 hσ1
    have e1 : ((27/32 : ℝ))/2 - 1 = -(37/64 : ℝ) := by norm_num
    have e2 : (1 - (27/32 : ℝ))/2 - 1 = -(59/64 : ℝ) := by norm_num
    rw [e1, e2] at h; exact h
  have hW_nn : (0 : ℝ) ≤ omegaPartial 3 (133/48 : ℝ) := omegaPartial_nonneg_here 3 _
  have hAstar_nn : (0 : ℝ) ≤ (133/48 : ℝ)^(-(37/64 : ℝ)) + (133/48 : ℝ)^(-(59/64 : ℝ)) := by
    have h := box0_pow_sum_nonneg ((27/32) : ℝ) hu1
    have eq1 : ((27/32 : ℝ))/2 - 1 = -(37/64 : ℝ) := by norm_num
    have eq2 : (1 - (27/32 : ℝ))/2 - 1 = -(59/64 : ℝ) := by norm_num
    rw [eq1, eq2] at h; exact h
  have hDstar_nn : (0 : ℝ) ≤ (133/48 : ℝ)^(-(37/64 : ℝ)) - (133/48 : ℝ)^(-(59/64 : ℝ)) := by
    have h := box0_pow_diff_nonneg (σ := (27/32 : ℝ)) (by norm_num) hu1
    have eq1 : ((27/32 : ℝ))/2 - 1 = -(37/64 : ℝ) := by norm_num
    have eq2 : (1 - (27/32 : ℝ))/2 - 1 = -(59/64 : ℝ) := by norm_num
    rw [eq1, eq2] at h; exact h
  have hC : Real.cos ((15/2 : ℝ) * Real.log (133/48 : ℝ)) ≥ 0 := u1_cos_nn
  have hS : Real.sin ((15/2 : ℝ) * Real.log (133/48 : ℝ)) ≥ 0 := u1_sin_nn
  have hRe := re_scalar_bounds_cos_nonneg
    (A_lo := 0)
    (A_hi := (133/48 : ℝ)^(-(37/64 : ℝ)) + (133/48 : ℝ)^(-(59/64 : ℝ)))
    (C_lo := 0)
    (C_hi := Real.cos ((15/2 : ℝ) * Real.log (133/48 : ℝ)))
    (W_lo := 0) (W_hi := omegaPartial 3 (133/48 : ℝ))
    (le_refl 0) hAstar_nn (le_refl 0) hC
    (le_refl 0) hW_nn
    hA_nn hA_hi hC (le_refl _) hW_nn (le_refl _)
  have hIm := im_scalar_bounds_sin_nonneg
    (D_lo := 0)
    (D_hi := (133/48 : ℝ)^(-(37/64 : ℝ)) - (133/48 : ℝ)^(-(59/64 : ℝ)))
    (S_lo := 0)
    (S_hi := Real.sin ((15/2 : ℝ) * Real.log (133/48 : ℝ)))
    (W_lo := 0) (W_hi := omegaPartial 3 (133/48 : ℝ))
    (le_refl 0) hDstar_nn (le_refl 0) hS
    (le_refl 0) hW_nn
    hD_nn hD_hi hS (le_refl _) hW_nn (le_refl _)
  refine ⟨?_, ?_, ?_, ?_⟩
  · unfold realThetaReIntegrandN
    have hAlo : (133/48 : ℝ)^(-(19/32 : ℝ)) + (133/48 : ℝ)^(-(29/32 : ℝ))
        ≤ (133/48 : ℝ)^(σ/2 - 1) + (133/48 : ℝ)^((1-σ)/2 - 1) :=
      by
        have h := PrincipiaTractalis.RiemannXiBoxParametric.box_pow_sum_lb
          (σlo := (13/16 : ℝ)) hu1 (by norm_num) hσ0
        have e1 : ((13/16 : ℝ))/2 - 1 = -(19/32 : ℝ) := by norm_num
        have e2 : (1 - (13/16 : ℝ))/2 - 1 = -(29/32 : ℝ) := by norm_num
        rw [e1, e2] at h; exact h
    have hCW : (0 : ℝ) ≤ Real.cos ((15/2 : ℝ) * Real.log (133/48 : ℝ))
        * omegaPartial 3 (133/48 : ℝ) := mul_nonneg hC hW_nn
    have hchain : ((133/48 : ℝ)^(-(19/32 : ℝ)) + (133/48 : ℝ)^(-(29/32 : ℝ)))
          * Real.cos ((15/2 : ℝ) * Real.log (133/48 : ℝ))
          * omegaPartial 3 (133/48 : ℝ)
        ≤ ((133/48 : ℝ)^(σ/2 - 1) + (133/48 : ℝ)^((1-σ)/2 - 1))
          * Real.cos ((15/2 : ℝ) * Real.log (133/48 : ℝ))
          * omegaPartial 3 (133/48 : ℝ) := by
      calc ((133/48 : ℝ)^(-(19/32 : ℝ)) + (133/48 : ℝ)^(-(29/32 : ℝ)))
            * Real.cos ((15/2 : ℝ) * Real.log (133/48 : ℝ))
            * omegaPartial 3 (133/48 : ℝ)
          = ((133/48 : ℝ)^(-(19/32 : ℝ)) + (133/48 : ℝ)^(-(29/32 : ℝ)))
            * (Real.cos ((15/2 : ℝ) * Real.log (133/48 : ℝ))
              * omegaPartial 3 (133/48 : ℝ)) := by ring
        _ ≤ ((133/48 : ℝ)^(σ/2 - 1) + (133/48 : ℝ)^((1-σ)/2 - 1))
            * (Real.cos ((15/2 : ℝ) * Real.log (133/48 : ℝ))
              * omegaPartial 3 (133/48 : ℝ)) :=
          mul_le_mul_of_nonneg_right hAlo hCW
        _ = ((133/48 : ℝ)^(σ/2 - 1) + (133/48 : ℝ)^((1-σ)/2 - 1))
            * Real.cos ((15/2 : ℝ) * Real.log (133/48 : ℝ))
            * omegaPartial 3 (133/48 : ℝ) := by ring
    linarith [u1_re_tight_ge, hchain]
  · unfold realThetaReIntegrandN
    linarith [hRe.2, u1_re_adverse_le]
  · unfold realThetaImIntegrandN
    have hDlo : (133/48 : ℝ)^(-(19/32 : ℝ)) - (133/48 : ℝ)^(-(29/32 : ℝ))
        ≤ (133/48 : ℝ)^(σ/2 - 1) - (133/48 : ℝ)^((1-σ)/2 - 1) := by
      have h := PrincipiaTractalis.RiemannXiBoxParametric.box_pow_diff_lb
        (σlo := (13/16 : ℝ)) hu1 hσ0
      have e1 : ((13/16 : ℝ))/2 - 1 = -(19/32 : ℝ) := by norm_num
      have e2 : (1 - (13/16 : ℝ))/2 - 1 = -(29/32 : ℝ) := by norm_num
      rw [e1, e2] at h; exact h
    have hSW : (0 : ℝ) ≤ Real.sin ((15/2 : ℝ) * Real.log (133/48 : ℝ))
        * omegaPartial 3 (133/48 : ℝ) := mul_nonneg hS hW_nn
    have hchain : ((133/48 : ℝ)^(-(19/32 : ℝ)) - (133/48 : ℝ)^(-(29/32 : ℝ)))
          * Real.sin ((15/2 : ℝ) * Real.log (133/48 : ℝ))
          * omegaPartial 3 (133/48 : ℝ)
        ≤ ((133/48 : ℝ)^(σ/2 - 1) - (133/48 : ℝ)^((1-σ)/2 - 1))
          * Real.sin ((15/2 : ℝ) * Real.log (133/48 : ℝ))
          * omegaPartial 3 (133/48 : ℝ) := by
      calc ((133/48 : ℝ)^(-(19/32 : ℝ)) - (133/48 : ℝ)^(-(29/32 : ℝ)))
            * Real.sin ((15/2 : ℝ) * Real.log (133/48 : ℝ))
            * omegaPartial 3 (133/48 : ℝ)
          = ((133/48 : ℝ)^(-(19/32 : ℝ)) - (133/48 : ℝ)^(-(29/32 : ℝ)))
            * (Real.sin ((15/2 : ℝ) * Real.log (133/48 : ℝ))
              * omegaPartial 3 (133/48 : ℝ)) := by ring
        _ ≤ ((133/48 : ℝ)^(σ/2 - 1) - (133/48 : ℝ)^((1-σ)/2 - 1))
            * (Real.sin ((15/2 : ℝ) * Real.log (133/48 : ℝ))
              * omegaPartial 3 (133/48 : ℝ)) :=
          mul_le_mul_of_nonneg_right hDlo hSW
        _ = ((133/48 : ℝ)^(σ/2 - 1) - (133/48 : ℝ)^((1-σ)/2 - 1))
            * Real.sin ((15/2 : ℝ) * Real.log (133/48 : ℝ))
            * omegaPartial 3 (133/48 : ℝ) := by ring
    linarith [u1_im_tight_ge, hchain]
  · unfold realThetaImIntegrandN
    linarith [hIm.2, u1_im_adverse_le]
/-! ## Node 2 at u = 401/144 — cos nn, sin nn -/

private theorem u2_cos_nn : (0 : ℝ) ≤ Real.cos ((15/2 : ℝ) * Real.log (401/144 : ℝ)) := by
  refine _root_.Interval.approx_le
    ((0 : _root_.Interval))
    (_root_.Interval.cos ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((401 : ℚ)/144))))
    (0 : ℝ)
    (Real.cos ((15/2 : ℝ) * Real.log (401/144 : ℝ)))
    (by approx)
    (_root_.Interval.mem_approx_cos (by approx))
    ?_
  decide +kernel


private theorem u2_sin_nn : (0 : ℝ) ≤ Real.sin ((15/2 : ℝ) * Real.log (401/144 : ℝ)) := by
  refine _root_.Interval.approx_le
    ((0 : _root_.Interval))
    (_root_.Interval.sin ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((401 : ℚ)/144))))
    (0 : ℝ)
    (Real.sin ((15/2 : ℝ) * Real.log (401/144 : ℝ)))
    (by approx)
    (_root_.Interval.mem_approx_sin (by approx))
    ?_
  decide +kernel


private theorem u2_re_adverse_le :
    ((401/144 : ℝ) ^ (-(37/64 : ℝ)) + (401/144 : ℝ) ^ (-(59/64 : ℝ)))
        * Real.cos ((15/2 : ℝ) * Real.log (401/144 : ℝ))
        * omegaPartial 3 (401/144 : ℝ)
      ≤ (3/100000 : ℝ) := by
  have hu0 : (0 : ℝ) < (401/144 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine le_of_lt <| _root_.Interval.approx_lt
    ((_root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((401 : ℚ)/144)) * _root_.Interval.ofRat (37/64)))
      + _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((401 : ℚ)/144)) * _root_.Interval.ofRat (59/64))))
     * _root_.Interval.cos ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((401 : ℚ)/144)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((401 : ℚ)/144)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((401 : ℚ)/144)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((401 : ℚ)/144)))))
    (3/100000 : _root_.Interval)
    _
    (3/100000 : ℝ)
    ?_
    (by approx)
    ?_
  · approx
  · decide +kernel

private theorem u2_re_tight_ge :
    (256523/10000000000 : ℝ)
      ≤ ((401/144 : ℝ) ^ (-(19/32 : ℝ)) + (401/144 : ℝ) ^ (-(29/32 : ℝ)))
        * Real.cos ((15/2 : ℝ) * Real.log (401/144 : ℝ))
        * omegaPartial 3 (401/144 : ℝ) := by
  have hu0 : (0 : ℝ) < (401/144 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine _root_.Interval.approx_le
    (256523/10000000000 : _root_.Interval)
    ((_root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((401 : ℚ)/144)) * _root_.Interval.ofRat (19/32)))
      + _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((401 : ℚ)/144)) * _root_.Interval.ofRat (29/32))))
     * _root_.Interval.cos ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((401 : ℚ)/144)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((401 : ℚ)/144)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((401 : ℚ)/144)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((401 : ℚ)/144)))))
    (256523/10000000000 : ℝ)
    _
    (by approx)
    ?_
    ?_
  · approx
  · decide +kernel


private theorem u2_im_adverse_le :
    ((401/144 : ℝ) ^ (-(37/64 : ℝ)) - (401/144 : ℝ) ^ (-(59/64 : ℝ)))
      * Real.sin ((15/2 : ℝ) * Real.log (401/144 : ℝ))
      * omegaPartial 3 (401/144 : ℝ)
      ≤ (257/10000000 : ℝ) := by
  have hu0 : (0 : ℝ) < (401/144 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine le_of_lt <| _root_.Interval.approx_lt
    ((_root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((401 : ℚ)/144)) * _root_.Interval.ofRat (37/64)))
      - _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((401 : ℚ)/144)) * _root_.Interval.ofRat (59/64))))
     * _root_.Interval.sin ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((401 : ℚ)/144)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((401 : ℚ)/144)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((401 : ℚ)/144)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((401 : ℚ)/144)))))
    (257/10000000 : _root_.Interval)
    _
    (257/10000000 : ℝ)
    ?_
    (by approx)
    ?_
  · approx
  · decide +kernel

private theorem u2_im_tight_ge :
    (116551/5000000000 : ℝ)
      ≤ ((401/144 : ℝ) ^ (-(19/32 : ℝ)) - (401/144 : ℝ) ^ (-(29/32 : ℝ)))
        * Real.sin ((15/2 : ℝ) * Real.log (401/144 : ℝ))
        * omegaPartial 3 (401/144 : ℝ) := by
  have hu0 : (0 : ℝ) < (401/144 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine _root_.Interval.approx_le
    (116551/5000000000 : _root_.Interval)
    ((_root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((401 : ℚ)/144)) * _root_.Interval.ofRat (19/32)))
      - _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((401 : ℚ)/144)) * _root_.Interval.ofRat (29/32))))
     * _root_.Interval.sin ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((401 : ℚ)/144)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((401 : ℚ)/144)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((401 : ℚ)/144)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((401 : ℚ)/144)))))
    (116551/5000000000 : ℝ)
    _
    (by approx)
    ?_
    ?_
  · approx
  · decide +kernel


theorem node_2_bounds (σ : ℝ)
    (hσ0 : (13/16 : ℝ) ≤ σ) (hσ1 : σ ≤ 27/32) :
    ((256523/10000000000 : ℝ)) ≤ realThetaReIntegrandN 3 σ 15 (401/144 : ℝ)
    ∧ realThetaReIntegrandN 3 σ 15 (401/144 : ℝ) ≤ ((3/100000 : ℝ))
    ∧ ((116551/5000000000 : ℝ)) ≤ realThetaImIntegrandN 3 σ 15 (401/144 : ℝ)
    ∧ realThetaImIntegrandN 3 σ 15 (401/144 : ℝ) ≤ ((257/10000000 : ℝ)) := by
  have hu1 : (1 : ℝ) ≤ (401/144 : ℝ) := by norm_num
  have hA_nn : (0 : ℝ) ≤ (401/144 : ℝ)^(σ/2 - 1) + (401/144 : ℝ)^((1-σ)/2 - 1) :=
    box0_pow_sum_nonneg σ hu1
  have hA_hi : (401/144 : ℝ)^(σ/2 - 1) + (401/144 : ℝ)^((1-σ)/2 - 1)
      ≤ (401/144 : ℝ)^(-(37/64 : ℝ)) + (401/144 : ℝ)^(-(59/64 : ℝ)) :=
    by
    have h := PrincipiaTractalis.RiemannXiBoxParametric.box_pow_sum_ub (σhi := (27/32 : ℝ)) hu1
      (by linarith) hσ1
    have e1 : ((27/32 : ℝ))/2 - 1 = -(37/64 : ℝ) := by norm_num
    have e2 : (1 - (27/32 : ℝ))/2 - 1 = -(59/64 : ℝ) := by norm_num
    rw [e1, e2] at h; exact h
  have hD_nn : (0 : ℝ) ≤ (401/144 : ℝ)^(σ/2 - 1) - (401/144 : ℝ)^((1-σ)/2 - 1) :=
    box0_pow_diff_nonneg (by linarith) hu1
  have hD_hi : (401/144 : ℝ)^(σ/2 - 1) - (401/144 : ℝ)^((1-σ)/2 - 1)
      ≤ (401/144 : ℝ)^(-(37/64 : ℝ)) - (401/144 : ℝ)^(-(59/64 : ℝ)) :=
    by
    have h := PrincipiaTractalis.RiemannXiBoxParametric.box_pow_diff_ub (σhi := (27/32 : ℝ)) hu1 hσ1
    have e1 : ((27/32 : ℝ))/2 - 1 = -(37/64 : ℝ) := by norm_num
    have e2 : (1 - (27/32 : ℝ))/2 - 1 = -(59/64 : ℝ) := by norm_num
    rw [e1, e2] at h; exact h
  have hW_nn : (0 : ℝ) ≤ omegaPartial 3 (401/144 : ℝ) := omegaPartial_nonneg_here 3 _
  have hAstar_nn : (0 : ℝ) ≤ (401/144 : ℝ)^(-(37/64 : ℝ)) + (401/144 : ℝ)^(-(59/64 : ℝ)) := by
    have h := box0_pow_sum_nonneg ((27/32) : ℝ) hu1
    have eq1 : ((27/32 : ℝ))/2 - 1 = -(37/64 : ℝ) := by norm_num
    have eq2 : (1 - (27/32 : ℝ))/2 - 1 = -(59/64 : ℝ) := by norm_num
    rw [eq1, eq2] at h; exact h
  have hDstar_nn : (0 : ℝ) ≤ (401/144 : ℝ)^(-(37/64 : ℝ)) - (401/144 : ℝ)^(-(59/64 : ℝ)) := by
    have h := box0_pow_diff_nonneg (σ := (27/32 : ℝ)) (by norm_num) hu1
    have eq1 : ((27/32 : ℝ))/2 - 1 = -(37/64 : ℝ) := by norm_num
    have eq2 : (1 - (27/32 : ℝ))/2 - 1 = -(59/64 : ℝ) := by norm_num
    rw [eq1, eq2] at h; exact h
  have hC : Real.cos ((15/2 : ℝ) * Real.log (401/144 : ℝ)) ≥ 0 := u2_cos_nn
  have hS : Real.sin ((15/2 : ℝ) * Real.log (401/144 : ℝ)) ≥ 0 := u2_sin_nn
  have hRe := re_scalar_bounds_cos_nonneg
    (A_lo := 0)
    (A_hi := (401/144 : ℝ)^(-(37/64 : ℝ)) + (401/144 : ℝ)^(-(59/64 : ℝ)))
    (C_lo := 0)
    (C_hi := Real.cos ((15/2 : ℝ) * Real.log (401/144 : ℝ)))
    (W_lo := 0) (W_hi := omegaPartial 3 (401/144 : ℝ))
    (le_refl 0) hAstar_nn (le_refl 0) hC
    (le_refl 0) hW_nn
    hA_nn hA_hi hC (le_refl _) hW_nn (le_refl _)
  have hIm := im_scalar_bounds_sin_nonneg
    (D_lo := 0)
    (D_hi := (401/144 : ℝ)^(-(37/64 : ℝ)) - (401/144 : ℝ)^(-(59/64 : ℝ)))
    (S_lo := 0)
    (S_hi := Real.sin ((15/2 : ℝ) * Real.log (401/144 : ℝ)))
    (W_lo := 0) (W_hi := omegaPartial 3 (401/144 : ℝ))
    (le_refl 0) hDstar_nn (le_refl 0) hS
    (le_refl 0) hW_nn
    hD_nn hD_hi hS (le_refl _) hW_nn (le_refl _)
  refine ⟨?_, ?_, ?_, ?_⟩
  · unfold realThetaReIntegrandN
    have hAlo : (401/144 : ℝ)^(-(19/32 : ℝ)) + (401/144 : ℝ)^(-(29/32 : ℝ))
        ≤ (401/144 : ℝ)^(σ/2 - 1) + (401/144 : ℝ)^((1-σ)/2 - 1) :=
      by
        have h := PrincipiaTractalis.RiemannXiBoxParametric.box_pow_sum_lb
          (σlo := (13/16 : ℝ)) hu1 (by norm_num) hσ0
        have e1 : ((13/16 : ℝ))/2 - 1 = -(19/32 : ℝ) := by norm_num
        have e2 : (1 - (13/16 : ℝ))/2 - 1 = -(29/32 : ℝ) := by norm_num
        rw [e1, e2] at h; exact h
    have hCW : (0 : ℝ) ≤ Real.cos ((15/2 : ℝ) * Real.log (401/144 : ℝ))
        * omegaPartial 3 (401/144 : ℝ) := mul_nonneg hC hW_nn
    have hchain : ((401/144 : ℝ)^(-(19/32 : ℝ)) + (401/144 : ℝ)^(-(29/32 : ℝ)))
          * Real.cos ((15/2 : ℝ) * Real.log (401/144 : ℝ))
          * omegaPartial 3 (401/144 : ℝ)
        ≤ ((401/144 : ℝ)^(σ/2 - 1) + (401/144 : ℝ)^((1-σ)/2 - 1))
          * Real.cos ((15/2 : ℝ) * Real.log (401/144 : ℝ))
          * omegaPartial 3 (401/144 : ℝ) := by
      calc ((401/144 : ℝ)^(-(19/32 : ℝ)) + (401/144 : ℝ)^(-(29/32 : ℝ)))
            * Real.cos ((15/2 : ℝ) * Real.log (401/144 : ℝ))
            * omegaPartial 3 (401/144 : ℝ)
          = ((401/144 : ℝ)^(-(19/32 : ℝ)) + (401/144 : ℝ)^(-(29/32 : ℝ)))
            * (Real.cos ((15/2 : ℝ) * Real.log (401/144 : ℝ))
              * omegaPartial 3 (401/144 : ℝ)) := by ring
        _ ≤ ((401/144 : ℝ)^(σ/2 - 1) + (401/144 : ℝ)^((1-σ)/2 - 1))
            * (Real.cos ((15/2 : ℝ) * Real.log (401/144 : ℝ))
              * omegaPartial 3 (401/144 : ℝ)) :=
          mul_le_mul_of_nonneg_right hAlo hCW
        _ = ((401/144 : ℝ)^(σ/2 - 1) + (401/144 : ℝ)^((1-σ)/2 - 1))
            * Real.cos ((15/2 : ℝ) * Real.log (401/144 : ℝ))
            * omegaPartial 3 (401/144 : ℝ) := by ring
    linarith [u2_re_tight_ge, hchain]
  · unfold realThetaReIntegrandN
    linarith [hRe.2, u2_re_adverse_le]
  · unfold realThetaImIntegrandN
    have hDlo : (401/144 : ℝ)^(-(19/32 : ℝ)) - (401/144 : ℝ)^(-(29/32 : ℝ))
        ≤ (401/144 : ℝ)^(σ/2 - 1) - (401/144 : ℝ)^((1-σ)/2 - 1) := by
      have h := PrincipiaTractalis.RiemannXiBoxParametric.box_pow_diff_lb
        (σlo := (13/16 : ℝ)) hu1 hσ0
      have e1 : ((13/16 : ℝ))/2 - 1 = -(19/32 : ℝ) := by norm_num
      have e2 : (1 - (13/16 : ℝ))/2 - 1 = -(29/32 : ℝ) := by norm_num
      rw [e1, e2] at h; exact h
    have hSW : (0 : ℝ) ≤ Real.sin ((15/2 : ℝ) * Real.log (401/144 : ℝ))
        * omegaPartial 3 (401/144 : ℝ) := mul_nonneg hS hW_nn
    have hchain : ((401/144 : ℝ)^(-(19/32 : ℝ)) - (401/144 : ℝ)^(-(29/32 : ℝ)))
          * Real.sin ((15/2 : ℝ) * Real.log (401/144 : ℝ))
          * omegaPartial 3 (401/144 : ℝ)
        ≤ ((401/144 : ℝ)^(σ/2 - 1) - (401/144 : ℝ)^((1-σ)/2 - 1))
          * Real.sin ((15/2 : ℝ) * Real.log (401/144 : ℝ))
          * omegaPartial 3 (401/144 : ℝ) := by
      calc ((401/144 : ℝ)^(-(19/32 : ℝ)) - (401/144 : ℝ)^(-(29/32 : ℝ)))
            * Real.sin ((15/2 : ℝ) * Real.log (401/144 : ℝ))
            * omegaPartial 3 (401/144 : ℝ)
          = ((401/144 : ℝ)^(-(19/32 : ℝ)) - (401/144 : ℝ)^(-(29/32 : ℝ)))
            * (Real.sin ((15/2 : ℝ) * Real.log (401/144 : ℝ))
              * omegaPartial 3 (401/144 : ℝ)) := by ring
        _ ≤ ((401/144 : ℝ)^(σ/2 - 1) - (401/144 : ℝ)^((1-σ)/2 - 1))
            * (Real.sin ((15/2 : ℝ) * Real.log (401/144 : ℝ))
              * omegaPartial 3 (401/144 : ℝ)) :=
          mul_le_mul_of_nonneg_right hDlo hSW
        _ = ((401/144 : ℝ)^(σ/2 - 1) - (401/144 : ℝ)^((1-σ)/2 - 1))
            * Real.sin ((15/2 : ℝ) * Real.log (401/144 : ℝ))
            * omegaPartial 3 (401/144 : ℝ) := by ring
    linarith [u2_im_tight_ge, hchain]
  · unfold realThetaImIntegrandN
    linarith [hIm.2, u2_im_adverse_le]


/-! ## Panel 1 chunk sum -/

theorem seg31_p1_chunk_bounds (σ : ℝ)
    (hσ0 : (13/16 : ℝ) ≤ σ) (hσ1 : σ ≤ 27/32) :
    ((985473/10000000000 : ℝ)) ≤ realThetaReIntegrandN 3 σ 15 (397/144 : ℝ) + realThetaReIntegrandN 3 σ 15 (133/48 : ℝ) + realThetaReIntegrandN 3 σ 15 (401/144 : ℝ)
    ∧ realThetaReIntegrandN 3 σ 15 (397/144 : ℝ) + realThetaReIntegrandN 3 σ 15 (133/48 : ℝ) + realThetaReIntegrandN 3 σ 15 (401/144 : ℝ) ≤ ((3/25000 : ℝ))
    ∧ ((181063/2500000000 : ℝ)) ≤ realThetaImIntegrandN 3 σ 15 (397/144 : ℝ) + realThetaImIntegrandN 3 σ 15 (133/48 : ℝ) + realThetaImIntegrandN 3 σ 15 (401/144 : ℝ)
    ∧ realThetaImIntegrandN 3 σ 15 (397/144 : ℝ) + realThetaImIntegrandN 3 σ 15 (133/48 : ℝ) + realThetaImIntegrandN 3 σ 15 (401/144 : ℝ) ≤ ((399/5000000 : ℝ)) := by
  have h0 := node_0_bounds σ hσ0 hσ1
  have h1 := node_1_bounds σ hσ0 hσ1
  have h2 := node_2_bounds σ hσ0 hσ1
  refine ⟨?_, ?_, ?_, ?_⟩
  · linarith [h0.1, h1.1, h2.1]
  · linarith [h0.2.1, h1.2.1, h2.2.1]
  · linarith [h0.2.2.1, h1.2.2.1, h2.2.2.1]
  · linarith [h0.2.2.2, h1.2.2.2, h2.2.2.2]

end PrincipiaTractalis.RiemannXiBox106Panels.Seg31P1
