/-
# PF.Analytic.RiemannXiBox113Panels.Seg06

OPT-40-TIGHT Stage-2 segment 6: L=37/32 U=19/16 n=14 MHI=189861100000431/25000000000000.
Auto-generated by scripts/emit_stage2_segment.py.

Split into 5 panel modules (Seg06P1..P5) for
per-file Interval-computation memory bounds.

  RE_LO_SUM = 1170567763/5000000000     RE_HI_SUM = 23421/100000
  IM_LO_SUM = 201126591/10000000000     IM_HI_SUM = 104159/5000000
  E_SEG     = 63287033333477/1284505600000000000000 ≈ 4.9270e-08
  RE_INT_LO = 671187090981386523/1284505600000000000000 ≈ 5.2253e-04
  RE_INT_HI = 671590199033333477/1284505600000000000000 ≈ 5.2284e-04
  IM_INT_LO = 57603729138186523/1284505600000000000000 ≈ 4.4845e-05
  IM_INT_HI = 59792223993333477/1284505600000000000000 ≈ 4.6549e-05

SPDX-License-Identifier: Apache-2.0
-/

import PF.Analytic.RiemannXiThetaRealFormAndBoxes_r331b
import PF.Analytic.RiemannXiBoxParametric
import PF.Numerics.Box113Seg06M
import PF.Analytic.RiemannXiBox113Panels.Seg06P1
import PF.Analytic.RiemannXiBox113Panels.Seg06P2
import PF.Analytic.RiemannXiBox113Panels.Seg06P3
import PF.Analytic.RiemannXiBox113Panels.Seg06P4
import PF.Analytic.RiemannXiBox113Panels.Seg06P5

namespace PrincipiaTractalis.RiemannXiBox113Panels.Seg06

open scoped Real BigOperators
open PrincipiaTractalis.RiemannXiThetaRealFormAndBoxes
open PrincipiaTractalis.Box113Seg06M
open PrincipiaTractalis.XiQuadrature
open PrincipiaTractalis.RiemannXiBox113Panels.Seg06P1
open PrincipiaTractalis.RiemannXiBox113Panels.Seg06P2
open PrincipiaTractalis.RiemannXiBox113Panels.Seg06P3
open PrincipiaTractalis.RiemannXiBox113Panels.Seg06P4
open PrincipiaTractalis.RiemannXiBox113Panels.Seg06P5

/-! ## Chunk sum (aggregated from all panels) -/

theorem seg6_chunk_bounds (σ : ℝ)
    (hσ0 : (15/16 : ℝ) ≤ σ) (hσ1 : σ ≤ 61/64) :
    ((1170567763/5000000000 : ℝ)) ≤ realThetaReIntegrandN 3 σ 15 (1037/896 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (1039/896 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (1041/896 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (149/128 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (1045/896 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (1047/896 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (1049/896 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (1051/896 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (1053/896 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (1055/896 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (151/128 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (1059/896 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (1061/896 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (1063/896 : ℝ)
    ∧ realThetaReIntegrandN 3 σ 15 (1037/896 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (1039/896 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (1041/896 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (149/128 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (1045/896 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (1047/896 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (1049/896 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (1051/896 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (1053/896 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (1055/896 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (151/128 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (1059/896 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (1061/896 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (1063/896 : ℝ) ≤ ((23421/100000 : ℝ))
    ∧ ((201126591/10000000000 : ℝ)) ≤ realThetaImIntegrandN 3 σ 15 (1037/896 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (1039/896 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (1041/896 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (149/128 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (1045/896 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (1047/896 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (1049/896 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (1051/896 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (1053/896 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (1055/896 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (151/128 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (1059/896 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (1061/896 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (1063/896 : ℝ)
    ∧ realThetaImIntegrandN 3 σ 15 (1037/896 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (1039/896 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (1041/896 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (149/128 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (1045/896 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (1047/896 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (1049/896 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (1051/896 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (1053/896 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (1055/896 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (151/128 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (1059/896 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (1061/896 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (1063/896 : ℝ) ≤ ((104159/5000000 : ℝ)) := by
  have hp1 := seg6_p1_chunk_bounds σ hσ0 hσ1
  have hp2 := seg6_p2_chunk_bounds σ hσ0 hσ1
  have hp3 := seg6_p3_chunk_bounds σ hσ0 hσ1
  have hp4 := seg6_p4_chunk_bounds σ hσ0 hσ1
  have hp5 := seg6_p5_chunk_bounds σ hσ0 hσ1
  refine ⟨?_, ?_, ?_, ?_⟩
  · linarith [(hp1).1, (hp2).1, (hp3).1, (hp4).1, (hp5).1]
  · linarith [(hp1).2.1, (hp2).2.1, (hp3).2.1, (hp4).2.1, (hp5).2.1]
  · linarith [(hp1).2.2.1, (hp2).2.2.1, (hp3).2.2.1, (hp4).2.2.1, (hp5).2.2.1]
  · linarith [(hp1).2.2.2, (hp2).2.2.2, (hp3).2.2.2, (hp4).2.2.2, (hp5).2.2.2]

/-! ## Midpoint sum equality -/

theorem seg6_re_midpoint_sum_eq_raw (σ : ℝ) :
    (∑ i ∈ Finset.range 14, realThetaReIntegrandN 3 σ 15
       ((37/32 : ℝ) + (19/16 - 37/32) / 14 * ((i : ℝ) + 1/2)))
    = realThetaReIntegrandN 3 σ 15 (1037/896 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (1039/896 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (1041/896 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (149/128 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (1045/896 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (1047/896 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (1049/896 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (1051/896 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (1053/896 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (1055/896 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (151/128 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (1059/896 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (1061/896 : ℝ)
        + realThetaReIntegrandN 3 σ 15 (1063/896 : ℝ) := by
  have e0 : ((37/32 : ℝ) + (19/16 - 37/32) / 14 * (1/2)) = (1037/896 : ℝ) := by norm_num
  have e1 : ((37/32 : ℝ) + (19/16 - 37/32) / 14 * ((1 : ℝ) + 1/2)) = (1039/896 : ℝ) := by norm_num
  have e2 : ((37/32 : ℝ) + (19/16 - 37/32) / 14 * ((2 : ℝ) + 1/2)) = (1041/896 : ℝ) := by norm_num
  have e3 : ((37/32 : ℝ) + (19/16 - 37/32) / 14 * ((3 : ℝ) + 1/2)) = (149/128 : ℝ) := by norm_num
  have e4 : ((37/32 : ℝ) + (19/16 - 37/32) / 14 * ((4 : ℝ) + 1/2)) = (1045/896 : ℝ) := by norm_num
  have e5 : ((37/32 : ℝ) + (19/16 - 37/32) / 14 * ((5 : ℝ) + 1/2)) = (1047/896 : ℝ) := by norm_num
  have e6 : ((37/32 : ℝ) + (19/16 - 37/32) / 14 * ((6 : ℝ) + 1/2)) = (1049/896 : ℝ) := by norm_num
  have e7 : ((37/32 : ℝ) + (19/16 - 37/32) / 14 * ((7 : ℝ) + 1/2)) = (1051/896 : ℝ) := by norm_num
  have e8 : ((37/32 : ℝ) + (19/16 - 37/32) / 14 * ((8 : ℝ) + 1/2)) = (1053/896 : ℝ) := by norm_num
  have e9 : ((37/32 : ℝ) + (19/16 - 37/32) / 14 * ((9 : ℝ) + 1/2)) = (1055/896 : ℝ) := by norm_num
  have e10 : ((37/32 : ℝ) + (19/16 - 37/32) / 14 * ((10 : ℝ) + 1/2)) = (151/128 : ℝ) := by norm_num
  have e11 : ((37/32 : ℝ) + (19/16 - 37/32) / 14 * ((11 : ℝ) + 1/2)) = (1059/896 : ℝ) := by norm_num
  have e12 : ((37/32 : ℝ) + (19/16 - 37/32) / 14 * ((12 : ℝ) + 1/2)) = (1061/896 : ℝ) := by norm_num
  have e13 : ((37/32 : ℝ) + (19/16 - 37/32) / 14 * ((13 : ℝ) + 1/2)) = (1063/896 : ℝ) := by norm_num
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, zero_add,
             Nat.cast_zero, Nat.cast_one, Nat.cast_ofNat,
             e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13]

theorem seg6_im_midpoint_sum_eq_raw (σ : ℝ) :
    (∑ i ∈ Finset.range 14, realThetaImIntegrandN 3 σ 15
       ((37/32 : ℝ) + (19/16 - 37/32) / 14 * ((i : ℝ) + 1/2)))
    = realThetaImIntegrandN 3 σ 15 (1037/896 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (1039/896 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (1041/896 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (149/128 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (1045/896 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (1047/896 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (1049/896 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (1051/896 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (1053/896 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (1055/896 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (151/128 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (1059/896 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (1061/896 : ℝ)
        + realThetaImIntegrandN 3 σ 15 (1063/896 : ℝ) := by
  have e0 : ((37/32 : ℝ) + (19/16 - 37/32) / 14 * (1/2)) = (1037/896 : ℝ) := by norm_num
  have e1 : ((37/32 : ℝ) + (19/16 - 37/32) / 14 * ((1 : ℝ) + 1/2)) = (1039/896 : ℝ) := by norm_num
  have e2 : ((37/32 : ℝ) + (19/16 - 37/32) / 14 * ((2 : ℝ) + 1/2)) = (1041/896 : ℝ) := by norm_num
  have e3 : ((37/32 : ℝ) + (19/16 - 37/32) / 14 * ((3 : ℝ) + 1/2)) = (149/128 : ℝ) := by norm_num
  have e4 : ((37/32 : ℝ) + (19/16 - 37/32) / 14 * ((4 : ℝ) + 1/2)) = (1045/896 : ℝ) := by norm_num
  have e5 : ((37/32 : ℝ) + (19/16 - 37/32) / 14 * ((5 : ℝ) + 1/2)) = (1047/896 : ℝ) := by norm_num
  have e6 : ((37/32 : ℝ) + (19/16 - 37/32) / 14 * ((6 : ℝ) + 1/2)) = (1049/896 : ℝ) := by norm_num
  have e7 : ((37/32 : ℝ) + (19/16 - 37/32) / 14 * ((7 : ℝ) + 1/2)) = (1051/896 : ℝ) := by norm_num
  have e8 : ((37/32 : ℝ) + (19/16 - 37/32) / 14 * ((8 : ℝ) + 1/2)) = (1053/896 : ℝ) := by norm_num
  have e9 : ((37/32 : ℝ) + (19/16 - 37/32) / 14 * ((9 : ℝ) + 1/2)) = (1055/896 : ℝ) := by norm_num
  have e10 : ((37/32 : ℝ) + (19/16 - 37/32) / 14 * ((10 : ℝ) + 1/2)) = (151/128 : ℝ) := by norm_num
  have e11 : ((37/32 : ℝ) + (19/16 - 37/32) / 14 * ((11 : ℝ) + 1/2)) = (1059/896 : ℝ) := by norm_num
  have e12 : ((37/32 : ℝ) + (19/16 - 37/32) / 14 * ((12 : ℝ) + 1/2)) = (1061/896 : ℝ) := by norm_num
  have e13 : ((37/32 : ℝ) + (19/16 - 37/32) / 14 * ((13 : ℝ) + 1/2)) = (1063/896 : ℝ) := by norm_num
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, zero_add,
             Nat.cast_zero, Nat.cast_one, Nat.cast_ofNat,
             e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13]

/-! ## Midpoint sum bounds -/

theorem seg6_re_midpoint_sum_lower (σ : ℝ)
    (hσ0 : (15/16 : ℝ) ≤ σ) (hσ1 : σ ≤ 61/64) :
    ((1170567763/5000000000 : ℝ)) ≤ (∑ i ∈ Finset.range 14, realThetaReIntegrandN 3 σ 15
        ((37/32 : ℝ) + (19/16 - 37/32) / 14 * ((i : ℝ) + 1/2))) := by
  rw [seg6_re_midpoint_sum_eq_raw]
  linarith [(seg6_chunk_bounds σ hσ0 hσ1).1]

theorem seg6_re_midpoint_sum_upper (σ : ℝ)
    (hσ0 : (15/16 : ℝ) ≤ σ) (hσ1 : σ ≤ 61/64) :
    (∑ i ∈ Finset.range 14, realThetaReIntegrandN 3 σ 15
        ((37/32 : ℝ) + (19/16 - 37/32) / 14 * ((i : ℝ) + 1/2))) ≤ ((23421/100000 : ℝ)) := by
  rw [seg6_re_midpoint_sum_eq_raw]
  linarith [(seg6_chunk_bounds σ hσ0 hσ1).2.1]

theorem seg6_im_midpoint_sum_lower (σ : ℝ)
    (hσ0 : (15/16 : ℝ) ≤ σ) (hσ1 : σ ≤ 61/64) :
    ((201126591/10000000000 : ℝ)) ≤ (∑ i ∈ Finset.range 14, realThetaImIntegrandN 3 σ 15
        ((37/32 : ℝ) + (19/16 - 37/32) / 14 * ((i : ℝ) + 1/2))) := by
  rw [seg6_im_midpoint_sum_eq_raw]
  linarith [(seg6_chunk_bounds σ hσ0 hσ1).2.2.1]

theorem seg6_im_midpoint_sum_upper (σ : ℝ)
    (hσ0 : (15/16 : ℝ) ≤ σ) (hσ1 : σ ≤ 61/64) :
    (∑ i ∈ Finset.range 14, realThetaImIntegrandN 3 σ 15
        ((37/32 : ℝ) + (19/16 - 37/32) / 14 * ((i : ℝ) + 1/2))) ≤ ((104159/5000000 : ℝ)) := by
  rw [seg6_im_midpoint_sum_eq_raw]
  linarith [(seg6_chunk_bounds σ hσ0 hσ1).2.2.2]

/-! ## Stage-2 segment-integral bounds via midpoint error + M ≤ MHI -/

private lemma seg6_error_bound_le :
    (2 * ∑ n' ∈ Finset.range 3, thetaPowTermM 15 (125/128) (31625/16384) (37/32) n')
      * ((19/16 : ℝ) - 37/32) ^ 3 / (24 * (14 : ℕ) ^ 2)
      ≤ ((63287033333477/1284505600000000000000 : ℝ)) := by
  have hM := box113_seg6_M_le_MHI
  set M := 2 * ∑ n' ∈ Finset.range 3, thetaPowTermM 15 (125/128) (31625/16384) (37/32) n' with hM_def
  have hassoc : M * ((19/16 : ℝ) - 37/32) ^ 3 / (24 * (14 : ℕ) ^ 2)
              = M * (((19/16 : ℝ) - 37/32) ^ 3 / (24 * (14 : ℕ) ^ 2)) := by ring
  rw [hassoc]
  have hf : ((19/16 : ℝ) - 37/32) ^ 3 / (24 * (14 : ℕ) ^ 2)
          = ((1/154140672 : ℝ)) := by push_cast; norm_num
  rw [hf]
  have hpos : (0 : ℝ) < (1/154140672 : ℝ) := by norm_num
  calc M * ((1/154140672 : ℝ))
        ≤ ((189861100000431/25000000000000 : ℝ)) * ((1/154140672 : ℝ)) :=
          mul_le_mul_of_nonneg_right hM (le_of_lt hpos)
    _ = ((63287033333477/1284505600000000000000 : ℝ)) := by norm_num

theorem box113_seg6_re_integral_lower (σ : ℝ)
    (hσ0 : (15/16 : ℝ) ≤ σ) (hσ1 : σ ≤ 61/64) :
    ((671187090981386523/1284505600000000000000 : ℝ)) ≤ ∫ u in (37/32 : ℝ)..19/16, realThetaReIntegrandN 3 σ 15 u := by
  have hL : (1 : ℝ) ≤ 37/32 := by norm_num
  have hLU : (37/32 : ℝ) ≤ 19/16 := by norm_num
  have hn : 0 < (14 : ℕ) := by decide
  have herr := PrincipiaTractalis.RiemannXiBoxParametric.box_re_midpoint_error_on_segment (N := 3) (σlo := (15/16 : ℝ)) (σhi := (61/64 : ℝ)) (p1 := (125/128 : ℝ)) (p2 := (31625/16384 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) hσ0 hσ1 hL hLU hn
  have hbound := seg6_error_bound_le
  have habs := abs_le.mp (le_trans herr hbound)
  have hmid := seg6_re_midpoint_sum_lower σ hσ0 hσ1
  have hscale : ((19/16 : ℝ) - 37/32) / (14 : ℕ) = ((1/448 : ℝ)) := by push_cast; norm_num
  rw [hscale] at habs
  linarith [habs.1, hmid]

theorem box113_seg6_re_integral_upper (σ : ℝ)
    (hσ0 : (15/16 : ℝ) ≤ σ) (hσ1 : σ ≤ 61/64) :
    (∫ u in (37/32 : ℝ)..19/16, realThetaReIntegrandN 3 σ 15 u) ≤ ((671590199033333477/1284505600000000000000 : ℝ)) := by
  have hL : (1 : ℝ) ≤ 37/32 := by norm_num
  have hLU : (37/32 : ℝ) ≤ 19/16 := by norm_num
  have hn : 0 < (14 : ℕ) := by decide
  have herr := PrincipiaTractalis.RiemannXiBoxParametric.box_re_midpoint_error_on_segment (N := 3) (σlo := (15/16 : ℝ)) (σhi := (61/64 : ℝ)) (p1 := (125/128 : ℝ)) (p2 := (31625/16384 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) hσ0 hσ1 hL hLU hn
  have hbound := seg6_error_bound_le
  have habs := abs_le.mp (le_trans herr hbound)
  have hmid := seg6_re_midpoint_sum_upper σ hσ0 hσ1
  have hscale : ((19/16 : ℝ) - 37/32) / (14 : ℕ) = ((1/448 : ℝ)) := by push_cast; norm_num
  rw [hscale] at habs
  linarith [habs.2, hmid]

theorem box113_seg6_im_integral_lower (σ : ℝ)
    (hσ0 : (15/16 : ℝ) ≤ σ) (hσ1 : σ ≤ 61/64) :
    ((57603729138186523/1284505600000000000000 : ℝ)) ≤ ∫ u in (37/32 : ℝ)..19/16, realThetaImIntegrandN 3 σ 15 u := by
  have hL : (1 : ℝ) ≤ 37/32 := by norm_num
  have hLU : (37/32 : ℝ) ≤ 19/16 := by norm_num
  have hn : 0 < (14 : ℕ) := by decide
  have herr := PrincipiaTractalis.RiemannXiBoxParametric.box_im_midpoint_error_on_segment (N := 3) (σlo := (15/16 : ℝ)) (σhi := (61/64 : ℝ)) (p1 := (125/128 : ℝ)) (p2 := (31625/16384 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) hσ0 hσ1 hL hLU hn
  have hbound := seg6_error_bound_le
  have habs := abs_le.mp (le_trans herr hbound)
  have hmid := seg6_im_midpoint_sum_lower σ hσ0 hσ1
  have hscale : ((19/16 : ℝ) - 37/32) / (14 : ℕ) = ((1/448 : ℝ)) := by push_cast; norm_num
  rw [hscale] at habs
  linarith [habs.1, hmid]

theorem box113_seg6_im_integral_upper (σ : ℝ)
    (hσ0 : (15/16 : ℝ) ≤ σ) (hσ1 : σ ≤ 61/64) :
    (∫ u in (37/32 : ℝ)..19/16, realThetaImIntegrandN 3 σ 15 u) ≤ ((59792223993333477/1284505600000000000000 : ℝ)) := by
  have hL : (1 : ℝ) ≤ 37/32 := by norm_num
  have hLU : (37/32 : ℝ) ≤ 19/16 := by norm_num
  have hn : 0 < (14 : ℕ) := by decide
  have herr := PrincipiaTractalis.RiemannXiBoxParametric.box_im_midpoint_error_on_segment (N := 3) (σlo := (15/16 : ℝ)) (σhi := (61/64 : ℝ)) (p1 := (125/128 : ℝ)) (p2 := (31625/16384 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) hσ0 hσ1 hL hLU hn
  have hbound := seg6_error_bound_le
  have habs := abs_le.mp (le_trans herr hbound)
  have hmid := seg6_im_midpoint_sum_upper σ hσ0 hσ1
  have hscale : ((19/16 : ℝ) - 37/32) / (14 : ℕ) = ((1/448 : ℝ)) := by push_cast; norm_num
  rw [hscale] at habs
  linarith [habs.2, hmid]

end PrincipiaTractalis.RiemannXiBox113Panels.Seg06
