/-
# PF.Analytic.RiemannXiBox108Panels.Seg26P6

Panel 6 of Segment 26: nodes [15, 16, 17].
Auto-generated by scripts/emit_stage2_segment.py.
-/

import PF.Analytic.RiemannXiThetaRealFormAndBoxes_r331b
import PF.Analytic.RiemannXiBoxParametric
import Interval.Interval.Conversion
import Interval.Interval.Exp
import Interval.Interval.Log
import Interval.Interval.Sincos
import Interval.Interval.Pi
import Interval.Interval.Order
import Interval.Interval.Mul
import Interval.Tactic.Approx

namespace PrincipiaTractalis.RiemannXiBox108Panels.Seg26P6

open scoped Real
open PrincipiaTractalis.RiemannXiThetaRealFormAndBoxes
open PrincipiaTractalis.XiQuadrature

private theorem rpow_neg_eq_exp {x a : ℝ} (hx : 0 < x) :
    x ^ (-a) = Real.exp (-(Real.log x * a)) := by
  rw [Real.rpow_def_of_pos hx]; ring_nf

private theorem omegaPartial_3_closed {u : ℝ} :
    omegaPartial 3 u = Real.exp (-(π * u)) + Real.exp (-(π * 4 * u))
      + Real.exp (-(π * 9 * u)) := by
  unfold omegaPartial
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, zero_add,
             Nat.cast_zero, Nat.cast_one, Nat.cast_ofNat, one_pow]
  ring_nf

/-! ## Node 15 at u = 847/384 — cos nn, sin np -/

private theorem u15_cos_nn : (0 : ℝ) ≤ Real.cos ((15/2 : ℝ) * Real.log (847/384 : ℝ)) := by
  refine _root_.Interval.approx_le
    ((0 : _root_.Interval))
    (_root_.Interval.cos ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((847 : ℚ)/384))))
    (0 : ℝ)
    (Real.cos ((15/2 : ℝ) * Real.log (847/384 : ℝ)))
    (by approx)
    (_root_.Interval.mem_approx_cos (by approx))
    ?_
  decide +kernel


private theorem u15_sin_np : Real.sin ((15/2 : ℝ) * Real.log (847/384 : ℝ)) ≤ 0 := by
  have hlt : Real.sin ((15/2 : ℝ) * Real.log (847/384 : ℝ)) < (0 : ℝ) := by
    refine _root_.Interval.approx_lt
      (_root_.Interval.sin ((15/2 : _root_.Interval) * _root_.Interval.log
          (_root_.Interval.ofRat ((847 : ℚ)/384))))
      ((0 : _root_.Interval))
      (Real.sin ((15/2 : ℝ) * Real.log (847/384 : ℝ)))
      (0 : ℝ)
      (_root_.Interval.mem_approx_sin (by approx))
      (by approx)
      ?_
    decide +kernel
  linarith


private theorem u15_re_adverse_le :
    ((847/384 : ℝ) ^ (-(9/16 : ℝ)) + (847/384 : ℝ) ^ (-(15/16 : ℝ)))
        * Real.cos ((15/2 : ℝ) * Real.log (847/384 : ℝ))
        * omegaPartial 3 (847/384 : ℝ)
      ≤ (103/100000 : ℝ) := by
  have hu0 : (0 : ℝ) < (847/384 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine le_of_lt <| _root_.Interval.approx_lt
    ((_root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((847 : ℚ)/384)) * _root_.Interval.ofRat (9/16)))
      + _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((847 : ℚ)/384)) * _root_.Interval.ofRat (15/16))))
     * _root_.Interval.cos ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((847 : ℚ)/384)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((847 : ℚ)/384)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((847 : ℚ)/384)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((847 : ℚ)/384)))))
    (103/100000 : _root_.Interval)
    _
    (103/100000 : ℝ)
    ?_
    (by approx)
    ?_
  · approx
  · decide +kernel

private theorem u15_re_tight_ge :
    (5129349/5000000000 : ℝ)
      ≤ ((847/384 : ℝ) ^ (-(73/128 : ℝ)) + (847/384 : ℝ) ^ (-(119/128 : ℝ)))
        * Real.cos ((15/2 : ℝ) * Real.log (847/384 : ℝ))
        * omegaPartial 3 (847/384 : ℝ) := by
  have hu0 : (0 : ℝ) < (847/384 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine _root_.Interval.approx_le
    (5129349/5000000000 : _root_.Interval)
    ((_root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((847 : ℚ)/384)) * _root_.Interval.ofRat (73/128)))
      + _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((847 : ℚ)/384)) * _root_.Interval.ofRat (119/128))))
     * _root_.Interval.cos ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((847 : ℚ)/384)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((847 : ℚ)/384)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((847 : ℚ)/384)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((847 : ℚ)/384)))))
    (5129349/5000000000 : ℝ)
    _
    (by approx)
    ?_
    ?_
  · approx
  · decide +kernel


private theorem u15_im_adverse_ge :
    (-553/10000000 : ℝ)
      ≤ ((847/384 : ℝ) ^ (-(9/16 : ℝ)) - (847/384 : ℝ) ^ (-(15/16 : ℝ)))
      * Real.sin ((15/2 : ℝ) * Real.log (847/384 : ℝ))
      * omegaPartial 3 (847/384 : ℝ) := by
  have hu0 : (0 : ℝ) < (847/384 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine _root_.Interval.approx_le
    (-553/10000000 : _root_.Interval)
    ((_root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((847 : ℚ)/384)) * _root_.Interval.ofRat (9/16)))
      - _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((847 : ℚ)/384)) * _root_.Interval.ofRat (15/16))))
     * _root_.Interval.sin ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((847 : ℚ)/384)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((847 : ℚ)/384)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((847 : ℚ)/384)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((847 : ℚ)/384)))))
    (-553/10000000 : ℝ)
    _
    (by approx)
    ?_
    ?_
  · approx
  · decide +kernel


theorem node_15_bounds (σ : ℝ)
    (hσ0 : (55/64 : ℝ) ≤ σ) (hσ1 : σ ≤ 7/8) :
    ((5129349/5000000000 : ℝ)) ≤ realThetaReIntegrandN 3 σ 15 (847/384 : ℝ)
    ∧ realThetaReIntegrandN 3 σ 15 (847/384 : ℝ) ≤ ((103/100000 : ℝ))
    ∧ ((-553/10000000 : ℝ)) ≤ realThetaImIntegrandN 3 σ 15 (847/384 : ℝ)
    ∧ realThetaImIntegrandN 3 σ 15 (847/384 : ℝ) ≤ (0) := by
  have hu1 : (1 : ℝ) ≤ (847/384 : ℝ) := by norm_num
  have hA_nn : (0 : ℝ) ≤ (847/384 : ℝ)^(σ/2 - 1) + (847/384 : ℝ)^((1-σ)/2 - 1) :=
    box0_pow_sum_nonneg σ hu1
  have hA_hi : (847/384 : ℝ)^(σ/2 - 1) + (847/384 : ℝ)^((1-σ)/2 - 1)
      ≤ (847/384 : ℝ)^(-(9/16 : ℝ)) + (847/384 : ℝ)^(-(15/16 : ℝ)) :=
    by
    have h := PrincipiaTractalis.RiemannXiBoxParametric.box_pow_sum_ub (σhi := (7/8 : ℝ)) hu1
      (by linarith) hσ1
    have e1 : ((7/8 : ℝ))/2 - 1 = -(9/16 : ℝ) := by norm_num
    have e2 : (1 - (7/8 : ℝ))/2 - 1 = -(15/16 : ℝ) := by norm_num
    rw [e1, e2] at h; exact h
  have hD_nn : (0 : ℝ) ≤ (847/384 : ℝ)^(σ/2 - 1) - (847/384 : ℝ)^((1-σ)/2 - 1) :=
    box0_pow_diff_nonneg (by linarith) hu1
  have hD_hi : (847/384 : ℝ)^(σ/2 - 1) - (847/384 : ℝ)^((1-σ)/2 - 1)
      ≤ (847/384 : ℝ)^(-(9/16 : ℝ)) - (847/384 : ℝ)^(-(15/16 : ℝ)) :=
    by
    have h := PrincipiaTractalis.RiemannXiBoxParametric.box_pow_diff_ub (σhi := (7/8 : ℝ)) hu1 hσ1
    have e1 : ((7/8 : ℝ))/2 - 1 = -(9/16 : ℝ) := by norm_num
    have e2 : (1 - (7/8 : ℝ))/2 - 1 = -(15/16 : ℝ) := by norm_num
    rw [e1, e2] at h; exact h
  have hW_nn : (0 : ℝ) ≤ omegaPartial 3 (847/384 : ℝ) := omegaPartial_nonneg_here 3 _
  have hAstar_nn : (0 : ℝ) ≤ (847/384 : ℝ)^(-(9/16 : ℝ)) + (847/384 : ℝ)^(-(15/16 : ℝ)) := by
    have h := box0_pow_sum_nonneg ((7/8) : ℝ) hu1
    have eq1 : ((7/8 : ℝ))/2 - 1 = -(9/16 : ℝ) := by norm_num
    have eq2 : (1 - (7/8 : ℝ))/2 - 1 = -(15/16 : ℝ) := by norm_num
    rw [eq1, eq2] at h; exact h
  have hDstar_nn : (0 : ℝ) ≤ (847/384 : ℝ)^(-(9/16 : ℝ)) - (847/384 : ℝ)^(-(15/16 : ℝ)) := by
    have h := box0_pow_diff_nonneg (σ := (7/8 : ℝ)) (by norm_num) hu1
    have eq1 : ((7/8 : ℝ))/2 - 1 = -(9/16 : ℝ) := by norm_num
    have eq2 : (1 - (7/8 : ℝ))/2 - 1 = -(15/16 : ℝ) := by norm_num
    rw [eq1, eq2] at h; exact h
  have hC : Real.cos ((15/2 : ℝ) * Real.log (847/384 : ℝ)) ≥ 0 := u15_cos_nn
  have hS : Real.sin ((15/2 : ℝ) * Real.log (847/384 : ℝ)) ≤ 0 := u15_sin_np
  have hRe := re_scalar_bounds_cos_nonneg
    (A_lo := 0)
    (A_hi := (847/384 : ℝ)^(-(9/16 : ℝ)) + (847/384 : ℝ)^(-(15/16 : ℝ)))
    (C_lo := 0)
    (C_hi := Real.cos ((15/2 : ℝ) * Real.log (847/384 : ℝ)))
    (W_lo := 0) (W_hi := omegaPartial 3 (847/384 : ℝ))
    (le_refl 0) hAstar_nn (le_refl 0) hC
    (le_refl 0) hW_nn
    hA_nn hA_hi hC (le_refl _) hW_nn (le_refl _)
  have hIm := im_scalar_bounds_sin_neg
    (D_lo := 0)
    (D_hi := (847/384 : ℝ)^(-(9/16 : ℝ)) - (847/384 : ℝ)^(-(15/16 : ℝ)))
    (S_lo := Real.sin ((15/2 : ℝ) * Real.log (847/384 : ℝ)))
    (S_hi := 0) (W_lo := 0) (W_hi := omegaPartial 3 (847/384 : ℝ))
    (le_refl 0) hDstar_nn hS hS (le_refl 0)
    (le_refl 0) hW_nn
    hD_nn hD_hi (le_refl _) hS hW_nn (le_refl _)
  refine ⟨?_, ?_, ?_, ?_⟩
  · unfold realThetaReIntegrandN
    have hAlo : (847/384 : ℝ)^(-(73/128 : ℝ)) + (847/384 : ℝ)^(-(119/128 : ℝ))
        ≤ (847/384 : ℝ)^(σ/2 - 1) + (847/384 : ℝ)^((1-σ)/2 - 1) :=
      by
        have h := PrincipiaTractalis.RiemannXiBoxParametric.box_pow_sum_lb
          (σlo := (55/64 : ℝ)) hu1 (by norm_num) hσ0
        have e1 : ((55/64 : ℝ))/2 - 1 = -(73/128 : ℝ) := by norm_num
        have e2 : (1 - (55/64 : ℝ))/2 - 1 = -(119/128 : ℝ) := by norm_num
        rw [e1, e2] at h; exact h
    have hCW : (0 : ℝ) ≤ Real.cos ((15/2 : ℝ) * Real.log (847/384 : ℝ))
        * omegaPartial 3 (847/384 : ℝ) := mul_nonneg hC hW_nn
    have hchain : ((847/384 : ℝ)^(-(73/128 : ℝ)) + (847/384 : ℝ)^(-(119/128 : ℝ)))
          * Real.cos ((15/2 : ℝ) * Real.log (847/384 : ℝ))
          * omegaPartial 3 (847/384 : ℝ)
        ≤ ((847/384 : ℝ)^(σ/2 - 1) + (847/384 : ℝ)^((1-σ)/2 - 1))
          * Real.cos ((15/2 : ℝ) * Real.log (847/384 : ℝ))
          * omegaPartial 3 (847/384 : ℝ) := by
      calc ((847/384 : ℝ)^(-(73/128 : ℝ)) + (847/384 : ℝ)^(-(119/128 : ℝ)))
            * Real.cos ((15/2 : ℝ) * Real.log (847/384 : ℝ))
            * omegaPartial 3 (847/384 : ℝ)
          = ((847/384 : ℝ)^(-(73/128 : ℝ)) + (847/384 : ℝ)^(-(119/128 : ℝ)))
            * (Real.cos ((15/2 : ℝ) * Real.log (847/384 : ℝ))
              * omegaPartial 3 (847/384 : ℝ)) := by ring
        _ ≤ ((847/384 : ℝ)^(σ/2 - 1) + (847/384 : ℝ)^((1-σ)/2 - 1))
            * (Real.cos ((15/2 : ℝ) * Real.log (847/384 : ℝ))
              * omegaPartial 3 (847/384 : ℝ)) :=
          mul_le_mul_of_nonneg_right hAlo hCW
        _ = ((847/384 : ℝ)^(σ/2 - 1) + (847/384 : ℝ)^((1-σ)/2 - 1))
            * Real.cos ((15/2 : ℝ) * Real.log (847/384 : ℝ))
            * omegaPartial 3 (847/384 : ℝ) := by ring
    linarith [u15_re_tight_ge, hchain]
  · unfold realThetaReIntegrandN
    linarith [hRe.2, u15_re_adverse_le]
  · unfold realThetaImIntegrandN
    linarith [hIm.1, u15_im_adverse_ge]
  · unfold realThetaImIntegrandN
    have h2 : (0 : ℝ) * 0 * 0 = 0 := by norm_num
    linarith [hIm.2]
/-! ## Node 16 at u = 283/128 — cos nn, sin np -/

private theorem u16_cos_nn : (0 : ℝ) ≤ Real.cos ((15/2 : ℝ) * Real.log (283/128 : ℝ)) := by
  refine _root_.Interval.approx_le
    ((0 : _root_.Interval))
    (_root_.Interval.cos ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((283 : ℚ)/128))))
    (0 : ℝ)
    (Real.cos ((15/2 : ℝ) * Real.log (283/128 : ℝ)))
    (by approx)
    (_root_.Interval.mem_approx_cos (by approx))
    ?_
  decide +kernel


private theorem u16_sin_np : Real.sin ((15/2 : ℝ) * Real.log (283/128 : ℝ)) ≤ 0 := by
  have hlt : Real.sin ((15/2 : ℝ) * Real.log (283/128 : ℝ)) < (0 : ℝ) := by
    refine _root_.Interval.approx_lt
      (_root_.Interval.sin ((15/2 : _root_.Interval) * _root_.Interval.log
          (_root_.Interval.ofRat ((283 : ℚ)/128))))
      ((0 : _root_.Interval))
      (Real.sin ((15/2 : ℝ) * Real.log (283/128 : ℝ)))
      (0 : ℝ)
      (_root_.Interval.mem_approx_sin (by approx))
      (by approx)
      ?_
    decide +kernel
  linarith


private theorem u16_re_adverse_le :
    ((283/128 : ℝ) ^ (-(9/16 : ℝ)) + (283/128 : ℝ) ^ (-(15/16 : ℝ)))
        * Real.cos ((15/2 : ℝ) * Real.log (283/128 : ℝ))
        * omegaPartial 3 (283/128 : ℝ)
      ≤ (51/50000 : ℝ) := by
  have hu0 : (0 : ℝ) < (283/128 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine le_of_lt <| _root_.Interval.approx_lt
    ((_root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((283 : ℚ)/128)) * _root_.Interval.ofRat (9/16)))
      + _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((283 : ℚ)/128)) * _root_.Interval.ofRat (15/16))))
     * _root_.Interval.cos ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((283 : ℚ)/128)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((283 : ℚ)/128)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((283 : ℚ)/128)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((283 : ℚ)/128)))))
    (51/50000 : _root_.Interval)
    _
    (51/50000 : ℝ)
    ?_
    (by approx)
    ?_
  · approx
  · decide +kernel

private theorem u16_re_tight_ge :
    (10138497/10000000000 : ℝ)
      ≤ ((283/128 : ℝ) ^ (-(73/128 : ℝ)) + (283/128 : ℝ) ^ (-(119/128 : ℝ)))
        * Real.cos ((15/2 : ℝ) * Real.log (283/128 : ℝ))
        * omegaPartial 3 (283/128 : ℝ) := by
  have hu0 : (0 : ℝ) < (283/128 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine _root_.Interval.approx_le
    (10138497/10000000000 : _root_.Interval)
    ((_root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((283 : ℚ)/128)) * _root_.Interval.ofRat (73/128)))
      + _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((283 : ℚ)/128)) * _root_.Interval.ofRat (119/128))))
     * _root_.Interval.cos ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((283 : ℚ)/128)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((283 : ℚ)/128)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((283 : ℚ)/128)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((283 : ℚ)/128)))))
    (10138497/10000000000 : ℝ)
    _
    (by approx)
    ?_
    ?_
  · approx
  · decide +kernel


private theorem u16_im_adverse_ge :
    (-259/5000000 : ℝ)
      ≤ ((283/128 : ℝ) ^ (-(9/16 : ℝ)) - (283/128 : ℝ) ^ (-(15/16 : ℝ)))
      * Real.sin ((15/2 : ℝ) * Real.log (283/128 : ℝ))
      * omegaPartial 3 (283/128 : ℝ) := by
  have hu0 : (0 : ℝ) < (283/128 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine _root_.Interval.approx_le
    (-259/5000000 : _root_.Interval)
    ((_root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((283 : ℚ)/128)) * _root_.Interval.ofRat (9/16)))
      - _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((283 : ℚ)/128)) * _root_.Interval.ofRat (15/16))))
     * _root_.Interval.sin ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((283 : ℚ)/128)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((283 : ℚ)/128)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((283 : ℚ)/128)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((283 : ℚ)/128)))))
    (-259/5000000 : ℝ)
    _
    (by approx)
    ?_
    ?_
  · approx
  · decide +kernel


theorem node_16_bounds (σ : ℝ)
    (hσ0 : (55/64 : ℝ) ≤ σ) (hσ1 : σ ≤ 7/8) :
    ((10138497/10000000000 : ℝ)) ≤ realThetaReIntegrandN 3 σ 15 (283/128 : ℝ)
    ∧ realThetaReIntegrandN 3 σ 15 (283/128 : ℝ) ≤ ((51/50000 : ℝ))
    ∧ ((-259/5000000 : ℝ)) ≤ realThetaImIntegrandN 3 σ 15 (283/128 : ℝ)
    ∧ realThetaImIntegrandN 3 σ 15 (283/128 : ℝ) ≤ (0) := by
  have hu1 : (1 : ℝ) ≤ (283/128 : ℝ) := by norm_num
  have hA_nn : (0 : ℝ) ≤ (283/128 : ℝ)^(σ/2 - 1) + (283/128 : ℝ)^((1-σ)/2 - 1) :=
    box0_pow_sum_nonneg σ hu1
  have hA_hi : (283/128 : ℝ)^(σ/2 - 1) + (283/128 : ℝ)^((1-σ)/2 - 1)
      ≤ (283/128 : ℝ)^(-(9/16 : ℝ)) + (283/128 : ℝ)^(-(15/16 : ℝ)) :=
    by
    have h := PrincipiaTractalis.RiemannXiBoxParametric.box_pow_sum_ub (σhi := (7/8 : ℝ)) hu1
      (by linarith) hσ1
    have e1 : ((7/8 : ℝ))/2 - 1 = -(9/16 : ℝ) := by norm_num
    have e2 : (1 - (7/8 : ℝ))/2 - 1 = -(15/16 : ℝ) := by norm_num
    rw [e1, e2] at h; exact h
  have hD_nn : (0 : ℝ) ≤ (283/128 : ℝ)^(σ/2 - 1) - (283/128 : ℝ)^((1-σ)/2 - 1) :=
    box0_pow_diff_nonneg (by linarith) hu1
  have hD_hi : (283/128 : ℝ)^(σ/2 - 1) - (283/128 : ℝ)^((1-σ)/2 - 1)
      ≤ (283/128 : ℝ)^(-(9/16 : ℝ)) - (283/128 : ℝ)^(-(15/16 : ℝ)) :=
    by
    have h := PrincipiaTractalis.RiemannXiBoxParametric.box_pow_diff_ub (σhi := (7/8 : ℝ)) hu1 hσ1
    have e1 : ((7/8 : ℝ))/2 - 1 = -(9/16 : ℝ) := by norm_num
    have e2 : (1 - (7/8 : ℝ))/2 - 1 = -(15/16 : ℝ) := by norm_num
    rw [e1, e2] at h; exact h
  have hW_nn : (0 : ℝ) ≤ omegaPartial 3 (283/128 : ℝ) := omegaPartial_nonneg_here 3 _
  have hAstar_nn : (0 : ℝ) ≤ (283/128 : ℝ)^(-(9/16 : ℝ)) + (283/128 : ℝ)^(-(15/16 : ℝ)) := by
    have h := box0_pow_sum_nonneg ((7/8) : ℝ) hu1
    have eq1 : ((7/8 : ℝ))/2 - 1 = -(9/16 : ℝ) := by norm_num
    have eq2 : (1 - (7/8 : ℝ))/2 - 1 = -(15/16 : ℝ) := by norm_num
    rw [eq1, eq2] at h; exact h
  have hDstar_nn : (0 : ℝ) ≤ (283/128 : ℝ)^(-(9/16 : ℝ)) - (283/128 : ℝ)^(-(15/16 : ℝ)) := by
    have h := box0_pow_diff_nonneg (σ := (7/8 : ℝ)) (by norm_num) hu1
    have eq1 : ((7/8 : ℝ))/2 - 1 = -(9/16 : ℝ) := by norm_num
    have eq2 : (1 - (7/8 : ℝ))/2 - 1 = -(15/16 : ℝ) := by norm_num
    rw [eq1, eq2] at h; exact h
  have hC : Real.cos ((15/2 : ℝ) * Real.log (283/128 : ℝ)) ≥ 0 := u16_cos_nn
  have hS : Real.sin ((15/2 : ℝ) * Real.log (283/128 : ℝ)) ≤ 0 := u16_sin_np
  have hRe := re_scalar_bounds_cos_nonneg
    (A_lo := 0)
    (A_hi := (283/128 : ℝ)^(-(9/16 : ℝ)) + (283/128 : ℝ)^(-(15/16 : ℝ)))
    (C_lo := 0)
    (C_hi := Real.cos ((15/2 : ℝ) * Real.log (283/128 : ℝ)))
    (W_lo := 0) (W_hi := omegaPartial 3 (283/128 : ℝ))
    (le_refl 0) hAstar_nn (le_refl 0) hC
    (le_refl 0) hW_nn
    hA_nn hA_hi hC (le_refl _) hW_nn (le_refl _)
  have hIm := im_scalar_bounds_sin_neg
    (D_lo := 0)
    (D_hi := (283/128 : ℝ)^(-(9/16 : ℝ)) - (283/128 : ℝ)^(-(15/16 : ℝ)))
    (S_lo := Real.sin ((15/2 : ℝ) * Real.log (283/128 : ℝ)))
    (S_hi := 0) (W_lo := 0) (W_hi := omegaPartial 3 (283/128 : ℝ))
    (le_refl 0) hDstar_nn hS hS (le_refl 0)
    (le_refl 0) hW_nn
    hD_nn hD_hi (le_refl _) hS hW_nn (le_refl _)
  refine ⟨?_, ?_, ?_, ?_⟩
  · unfold realThetaReIntegrandN
    have hAlo : (283/128 : ℝ)^(-(73/128 : ℝ)) + (283/128 : ℝ)^(-(119/128 : ℝ))
        ≤ (283/128 : ℝ)^(σ/2 - 1) + (283/128 : ℝ)^((1-σ)/2 - 1) :=
      by
        have h := PrincipiaTractalis.RiemannXiBoxParametric.box_pow_sum_lb
          (σlo := (55/64 : ℝ)) hu1 (by norm_num) hσ0
        have e1 : ((55/64 : ℝ))/2 - 1 = -(73/128 : ℝ) := by norm_num
        have e2 : (1 - (55/64 : ℝ))/2 - 1 = -(119/128 : ℝ) := by norm_num
        rw [e1, e2] at h; exact h
    have hCW : (0 : ℝ) ≤ Real.cos ((15/2 : ℝ) * Real.log (283/128 : ℝ))
        * omegaPartial 3 (283/128 : ℝ) := mul_nonneg hC hW_nn
    have hchain : ((283/128 : ℝ)^(-(73/128 : ℝ)) + (283/128 : ℝ)^(-(119/128 : ℝ)))
          * Real.cos ((15/2 : ℝ) * Real.log (283/128 : ℝ))
          * omegaPartial 3 (283/128 : ℝ)
        ≤ ((283/128 : ℝ)^(σ/2 - 1) + (283/128 : ℝ)^((1-σ)/2 - 1))
          * Real.cos ((15/2 : ℝ) * Real.log (283/128 : ℝ))
          * omegaPartial 3 (283/128 : ℝ) := by
      calc ((283/128 : ℝ)^(-(73/128 : ℝ)) + (283/128 : ℝ)^(-(119/128 : ℝ)))
            * Real.cos ((15/2 : ℝ) * Real.log (283/128 : ℝ))
            * omegaPartial 3 (283/128 : ℝ)
          = ((283/128 : ℝ)^(-(73/128 : ℝ)) + (283/128 : ℝ)^(-(119/128 : ℝ)))
            * (Real.cos ((15/2 : ℝ) * Real.log (283/128 : ℝ))
              * omegaPartial 3 (283/128 : ℝ)) := by ring
        _ ≤ ((283/128 : ℝ)^(σ/2 - 1) + (283/128 : ℝ)^((1-σ)/2 - 1))
            * (Real.cos ((15/2 : ℝ) * Real.log (283/128 : ℝ))
              * omegaPartial 3 (283/128 : ℝ)) :=
          mul_le_mul_of_nonneg_right hAlo hCW
        _ = ((283/128 : ℝ)^(σ/2 - 1) + (283/128 : ℝ)^((1-σ)/2 - 1))
            * Real.cos ((15/2 : ℝ) * Real.log (283/128 : ℝ))
            * omegaPartial 3 (283/128 : ℝ) := by ring
    linarith [u16_re_tight_ge, hchain]
  · unfold realThetaReIntegrandN
    linarith [hRe.2, u16_re_adverse_le]
  · unfold realThetaImIntegrandN
    linarith [hIm.1, u16_im_adverse_ge]
  · unfold realThetaImIntegrandN
    have h2 : (0 : ℝ) * 0 * 0 = 0 := by norm_num
    linarith [hIm.2]
/-! ## Node 17 at u = 851/384 — cos nn, sin np -/

private theorem u17_cos_nn : (0 : ℝ) ≤ Real.cos ((15/2 : ℝ) * Real.log (851/384 : ℝ)) := by
  refine _root_.Interval.approx_le
    ((0 : _root_.Interval))
    (_root_.Interval.cos ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((851 : ℚ)/384))))
    (0 : ℝ)
    (Real.cos ((15/2 : ℝ) * Real.log (851/384 : ℝ)))
    (by approx)
    (_root_.Interval.mem_approx_cos (by approx))
    ?_
  decide +kernel


private theorem u17_sin_np : Real.sin ((15/2 : ℝ) * Real.log (851/384 : ℝ)) ≤ 0 := by
  have hlt : Real.sin ((15/2 : ℝ) * Real.log (851/384 : ℝ)) < (0 : ℝ) := by
    refine _root_.Interval.approx_lt
      (_root_.Interval.sin ((15/2 : _root_.Interval) * _root_.Interval.log
          (_root_.Interval.ofRat ((851 : ℚ)/384))))
      ((0 : _root_.Interval))
      (Real.sin ((15/2 : ℝ) * Real.log (851/384 : ℝ)))
      (0 : ℝ)
      (_root_.Interval.mem_approx_sin (by approx))
      (by approx)
      ?_
    decide +kernel
  linarith


private theorem u17_re_adverse_le :
    ((851/384 : ℝ) ^ (-(9/16 : ℝ)) + (851/384 : ℝ) ^ (-(15/16 : ℝ)))
        * Real.cos ((15/2 : ℝ) * Real.log (851/384 : ℝ))
        * omegaPartial 3 (851/384 : ℝ)
      ≤ (101/100000 : ℝ) := by
  have hu0 : (0 : ℝ) < (851/384 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine le_of_lt <| _root_.Interval.approx_lt
    ((_root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((851 : ℚ)/384)) * _root_.Interval.ofRat (9/16)))
      + _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((851 : ℚ)/384)) * _root_.Interval.ofRat (15/16))))
     * _root_.Interval.cos ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((851 : ℚ)/384)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((851 : ℚ)/384)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((851 : ℚ)/384)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((851 : ℚ)/384)))))
    (101/100000 : _root_.Interval)
    _
    (101/100000 : ℝ)
    ?_
    (by approx)
    ?_
  · approx
  · decide +kernel

private theorem u17_re_tight_ge :
    (10016103/10000000000 : ℝ)
      ≤ ((851/384 : ℝ) ^ (-(73/128 : ℝ)) + (851/384 : ℝ) ^ (-(119/128 : ℝ)))
        * Real.cos ((15/2 : ℝ) * Real.log (851/384 : ℝ))
        * omegaPartial 3 (851/384 : ℝ) := by
  have hu0 : (0 : ℝ) < (851/384 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine _root_.Interval.approx_le
    (10016103/10000000000 : _root_.Interval)
    ((_root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((851 : ℚ)/384)) * _root_.Interval.ofRat (73/128)))
      + _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((851 : ℚ)/384)) * _root_.Interval.ofRat (119/128))))
     * _root_.Interval.cos ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((851 : ℚ)/384)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((851 : ℚ)/384)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((851 : ℚ)/384)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((851 : ℚ)/384)))))
    (10016103/10000000000 : ℝ)
    _
    (by approx)
    ?_
    ?_
  · approx
  · decide +kernel


private theorem u17_im_adverse_ge :
    (-121/2500000 : ℝ)
      ≤ ((851/384 : ℝ) ^ (-(9/16 : ℝ)) - (851/384 : ℝ) ^ (-(15/16 : ℝ)))
      * Real.sin ((15/2 : ℝ) * Real.log (851/384 : ℝ))
      * omegaPartial 3 (851/384 : ℝ) := by
  have hu0 : (0 : ℝ) < (851/384 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine _root_.Interval.approx_le
    (-121/2500000 : _root_.Interval)
    ((_root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((851 : ℚ)/384)) * _root_.Interval.ofRat (9/16)))
      - _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((851 : ℚ)/384)) * _root_.Interval.ofRat (15/16))))
     * _root_.Interval.sin ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((851 : ℚ)/384)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((851 : ℚ)/384)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((851 : ℚ)/384)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((851 : ℚ)/384)))))
    (-121/2500000 : ℝ)
    _
    (by approx)
    ?_
    ?_
  · approx
  · decide +kernel


theorem node_17_bounds (σ : ℝ)
    (hσ0 : (55/64 : ℝ) ≤ σ) (hσ1 : σ ≤ 7/8) :
    ((10016103/10000000000 : ℝ)) ≤ realThetaReIntegrandN 3 σ 15 (851/384 : ℝ)
    ∧ realThetaReIntegrandN 3 σ 15 (851/384 : ℝ) ≤ ((101/100000 : ℝ))
    ∧ ((-121/2500000 : ℝ)) ≤ realThetaImIntegrandN 3 σ 15 (851/384 : ℝ)
    ∧ realThetaImIntegrandN 3 σ 15 (851/384 : ℝ) ≤ (0) := by
  have hu1 : (1 : ℝ) ≤ (851/384 : ℝ) := by norm_num
  have hA_nn : (0 : ℝ) ≤ (851/384 : ℝ)^(σ/2 - 1) + (851/384 : ℝ)^((1-σ)/2 - 1) :=
    box0_pow_sum_nonneg σ hu1
  have hA_hi : (851/384 : ℝ)^(σ/2 - 1) + (851/384 : ℝ)^((1-σ)/2 - 1)
      ≤ (851/384 : ℝ)^(-(9/16 : ℝ)) + (851/384 : ℝ)^(-(15/16 : ℝ)) :=
    by
    have h := PrincipiaTractalis.RiemannXiBoxParametric.box_pow_sum_ub (σhi := (7/8 : ℝ)) hu1
      (by linarith) hσ1
    have e1 : ((7/8 : ℝ))/2 - 1 = -(9/16 : ℝ) := by norm_num
    have e2 : (1 - (7/8 : ℝ))/2 - 1 = -(15/16 : ℝ) := by norm_num
    rw [e1, e2] at h; exact h
  have hD_nn : (0 : ℝ) ≤ (851/384 : ℝ)^(σ/2 - 1) - (851/384 : ℝ)^((1-σ)/2 - 1) :=
    box0_pow_diff_nonneg (by linarith) hu1
  have hD_hi : (851/384 : ℝ)^(σ/2 - 1) - (851/384 : ℝ)^((1-σ)/2 - 1)
      ≤ (851/384 : ℝ)^(-(9/16 : ℝ)) - (851/384 : ℝ)^(-(15/16 : ℝ)) :=
    by
    have h := PrincipiaTractalis.RiemannXiBoxParametric.box_pow_diff_ub (σhi := (7/8 : ℝ)) hu1 hσ1
    have e1 : ((7/8 : ℝ))/2 - 1 = -(9/16 : ℝ) := by norm_num
    have e2 : (1 - (7/8 : ℝ))/2 - 1 = -(15/16 : ℝ) := by norm_num
    rw [e1, e2] at h; exact h
  have hW_nn : (0 : ℝ) ≤ omegaPartial 3 (851/384 : ℝ) := omegaPartial_nonneg_here 3 _
  have hAstar_nn : (0 : ℝ) ≤ (851/384 : ℝ)^(-(9/16 : ℝ)) + (851/384 : ℝ)^(-(15/16 : ℝ)) := by
    have h := box0_pow_sum_nonneg ((7/8) : ℝ) hu1
    have eq1 : ((7/8 : ℝ))/2 - 1 = -(9/16 : ℝ) := by norm_num
    have eq2 : (1 - (7/8 : ℝ))/2 - 1 = -(15/16 : ℝ) := by norm_num
    rw [eq1, eq2] at h; exact h
  have hDstar_nn : (0 : ℝ) ≤ (851/384 : ℝ)^(-(9/16 : ℝ)) - (851/384 : ℝ)^(-(15/16 : ℝ)) := by
    have h := box0_pow_diff_nonneg (σ := (7/8 : ℝ)) (by norm_num) hu1
    have eq1 : ((7/8 : ℝ))/2 - 1 = -(9/16 : ℝ) := by norm_num
    have eq2 : (1 - (7/8 : ℝ))/2 - 1 = -(15/16 : ℝ) := by norm_num
    rw [eq1, eq2] at h; exact h
  have hC : Real.cos ((15/2 : ℝ) * Real.log (851/384 : ℝ)) ≥ 0 := u17_cos_nn
  have hS : Real.sin ((15/2 : ℝ) * Real.log (851/384 : ℝ)) ≤ 0 := u17_sin_np
  have hRe := re_scalar_bounds_cos_nonneg
    (A_lo := 0)
    (A_hi := (851/384 : ℝ)^(-(9/16 : ℝ)) + (851/384 : ℝ)^(-(15/16 : ℝ)))
    (C_lo := 0)
    (C_hi := Real.cos ((15/2 : ℝ) * Real.log (851/384 : ℝ)))
    (W_lo := 0) (W_hi := omegaPartial 3 (851/384 : ℝ))
    (le_refl 0) hAstar_nn (le_refl 0) hC
    (le_refl 0) hW_nn
    hA_nn hA_hi hC (le_refl _) hW_nn (le_refl _)
  have hIm := im_scalar_bounds_sin_neg
    (D_lo := 0)
    (D_hi := (851/384 : ℝ)^(-(9/16 : ℝ)) - (851/384 : ℝ)^(-(15/16 : ℝ)))
    (S_lo := Real.sin ((15/2 : ℝ) * Real.log (851/384 : ℝ)))
    (S_hi := 0) (W_lo := 0) (W_hi := omegaPartial 3 (851/384 : ℝ))
    (le_refl 0) hDstar_nn hS hS (le_refl 0)
    (le_refl 0) hW_nn
    hD_nn hD_hi (le_refl _) hS hW_nn (le_refl _)
  refine ⟨?_, ?_, ?_, ?_⟩
  · unfold realThetaReIntegrandN
    have hAlo : (851/384 : ℝ)^(-(73/128 : ℝ)) + (851/384 : ℝ)^(-(119/128 : ℝ))
        ≤ (851/384 : ℝ)^(σ/2 - 1) + (851/384 : ℝ)^((1-σ)/2 - 1) :=
      by
        have h := PrincipiaTractalis.RiemannXiBoxParametric.box_pow_sum_lb
          (σlo := (55/64 : ℝ)) hu1 (by norm_num) hσ0
        have e1 : ((55/64 : ℝ))/2 - 1 = -(73/128 : ℝ) := by norm_num
        have e2 : (1 - (55/64 : ℝ))/2 - 1 = -(119/128 : ℝ) := by norm_num
        rw [e1, e2] at h; exact h
    have hCW : (0 : ℝ) ≤ Real.cos ((15/2 : ℝ) * Real.log (851/384 : ℝ))
        * omegaPartial 3 (851/384 : ℝ) := mul_nonneg hC hW_nn
    have hchain : ((851/384 : ℝ)^(-(73/128 : ℝ)) + (851/384 : ℝ)^(-(119/128 : ℝ)))
          * Real.cos ((15/2 : ℝ) * Real.log (851/384 : ℝ))
          * omegaPartial 3 (851/384 : ℝ)
        ≤ ((851/384 : ℝ)^(σ/2 - 1) + (851/384 : ℝ)^((1-σ)/2 - 1))
          * Real.cos ((15/2 : ℝ) * Real.log (851/384 : ℝ))
          * omegaPartial 3 (851/384 : ℝ) := by
      calc ((851/384 : ℝ)^(-(73/128 : ℝ)) + (851/384 : ℝ)^(-(119/128 : ℝ)))
            * Real.cos ((15/2 : ℝ) * Real.log (851/384 : ℝ))
            * omegaPartial 3 (851/384 : ℝ)
          = ((851/384 : ℝ)^(-(73/128 : ℝ)) + (851/384 : ℝ)^(-(119/128 : ℝ)))
            * (Real.cos ((15/2 : ℝ) * Real.log (851/384 : ℝ))
              * omegaPartial 3 (851/384 : ℝ)) := by ring
        _ ≤ ((851/384 : ℝ)^(σ/2 - 1) + (851/384 : ℝ)^((1-σ)/2 - 1))
            * (Real.cos ((15/2 : ℝ) * Real.log (851/384 : ℝ))
              * omegaPartial 3 (851/384 : ℝ)) :=
          mul_le_mul_of_nonneg_right hAlo hCW
        _ = ((851/384 : ℝ)^(σ/2 - 1) + (851/384 : ℝ)^((1-σ)/2 - 1))
            * Real.cos ((15/2 : ℝ) * Real.log (851/384 : ℝ))
            * omegaPartial 3 (851/384 : ℝ) := by ring
    linarith [u17_re_tight_ge, hchain]
  · unfold realThetaReIntegrandN
    linarith [hRe.2, u17_re_adverse_le]
  · unfold realThetaImIntegrandN
    linarith [hIm.1, u17_im_adverse_ge]
  · unfold realThetaImIntegrandN
    have h2 : (0 : ℝ) * 0 * 0 = 0 := by norm_num
    linarith [hIm.2]


/-! ## Panel 6 chunk sum -/

theorem seg26_p6_chunk_bounds (σ : ℝ)
    (hσ0 : (55/64 : ℝ) ≤ σ) (hσ1 : σ ≤ 7/8) :
    ((15206649/5000000000 : ℝ)) ≤ realThetaReIntegrandN 3 σ 15 (847/384 : ℝ) + realThetaReIntegrandN 3 σ 15 (283/128 : ℝ) + realThetaReIntegrandN 3 σ 15 (851/384 : ℝ)
    ∧ realThetaReIntegrandN 3 σ 15 (847/384 : ℝ) + realThetaReIntegrandN 3 σ 15 (283/128 : ℝ) + realThetaReIntegrandN 3 σ 15 (851/384 : ℝ) ≤ ((153/50000 : ℝ))
    ∧ ((-311/2000000 : ℝ)) ≤ realThetaImIntegrandN 3 σ 15 (847/384 : ℝ) + realThetaImIntegrandN 3 σ 15 (283/128 : ℝ) + realThetaImIntegrandN 3 σ 15 (851/384 : ℝ)
    ∧ realThetaImIntegrandN 3 σ 15 (847/384 : ℝ) + realThetaImIntegrandN 3 σ 15 (283/128 : ℝ) + realThetaImIntegrandN 3 σ 15 (851/384 : ℝ) ≤ ((0/1 : ℝ)) := by
  have h15 := node_15_bounds σ hσ0 hσ1
  have h16 := node_16_bounds σ hσ0 hσ1
  have h17 := node_17_bounds σ hσ0 hσ1
  refine ⟨?_, ?_, ?_, ?_⟩
  · linarith [h15.1, h16.1, h17.1]
  · linarith [h15.2.1, h16.2.1, h17.2.1]
  · linarith [h15.2.2.1, h16.2.2.1, h17.2.2.1]
  · linarith [h15.2.2.2, h16.2.2.2, h17.2.2.2]

end PrincipiaTractalis.RiemannXiBox108Panels.Seg26P6
