/-
# PF.Analytic.RiemannXiBox110Panels.Seg14P4

Panel 4 of Segment 14: nodes [9].
Auto-generated by scripts/emit_stage2_segment.py.
-/

import PF.Analytic.RiemannXiThetaRealFormAndBoxes_r331b
import PF.Analytic.RiemannXiBoxParametric
import Interval.Interval.Conversion
import Interval.Interval.Exp
import Interval.Interval.Log
import Interval.Interval.Sincos
import Interval.Interval.Pi
import Interval.Interval.Order
import Interval.Interval.Mul
import Interval.Tactic.Approx

namespace PrincipiaTractalis.RiemannXiBox110Panels.Seg14P4

open scoped Real
open PrincipiaTractalis.RiemannXiThetaRealFormAndBoxes
open PrincipiaTractalis.XiQuadrature

private theorem rpow_neg_eq_exp {x a : ℝ} (hx : 0 < x) :
    x ^ (-a) = Real.exp (-(Real.log x * a)) := by
  rw [Real.rpow_def_of_pos hx]; ring_nf

private theorem omegaPartial_3_closed {u : ℝ} :
    omegaPartial 3 u = Real.exp (-(π * u)) + Real.exp (-(π * 4 * u))
      + Real.exp (-(π * 9 * u)) := by
  unfold omegaPartial
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, zero_add,
             Nat.cast_zero, Nat.cast_one, Nat.cast_ofNat, one_pow]
  ring_nf

/-! ## Node 9 at u = 919/640 — cos np, sin nn -/

private theorem u9_cos_np : Real.cos ((15/2 : ℝ) * Real.log (919/640 : ℝ)) ≤ 0 := by
  have hlt : Real.cos ((15/2 : ℝ) * Real.log (919/640 : ℝ)) < (0 : ℝ) := by
    refine _root_.Interval.approx_lt
      (_root_.Interval.cos ((15/2 : _root_.Interval) * _root_.Interval.log
          (_root_.Interval.ofRat ((919 : ℚ)/640))))
      ((0 : _root_.Interval))
      (Real.cos ((15/2 : ℝ) * Real.log (919/640 : ℝ)))
      (0 : ℝ)
      (_root_.Interval.mem_approx_cos (by approx))
      (by approx)
      ?_
    decide +kernel
  linarith


private theorem u9_sin_nn : (0 : ℝ) ≤ Real.sin ((15/2 : ℝ) * Real.log (919/640 : ℝ)) := by
  refine _root_.Interval.approx_le
    ((0 : _root_.Interval))
    (_root_.Interval.sin ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((919 : ℚ)/640))))
    (0 : ℝ)
    (Real.sin ((15/2 : ℝ) * Real.log (919/640 : ℝ)))
    (by approx)
    (_root_.Interval.mem_approx_sin (by approx))
    ?_
  decide +kernel


private theorem u9_re_adverse_ge :
    (-955047/62500000 : ℝ)
      ≤ ((919/640 : ℝ) ^ (-(35/64 : ℝ)) + (919/640 : ℝ) ^ (-(61/64 : ℝ)))
        * Real.cos ((15/2 : ℝ) * Real.log (919/640 : ℝ))
        * omegaPartial 3 (919/640 : ℝ) := by
  have hu0 : (0 : ℝ) < (919/640 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine _root_.Interval.approx_le
    (-955047/62500000 : _root_.Interval)
    ((_root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((919 : ℚ)/640)) * _root_.Interval.ofRat (35/64)))
      + _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((919 : ℚ)/640)) * _root_.Interval.ofRat (61/64))))
     * _root_.Interval.cos ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((919 : ℚ)/640)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((919 : ℚ)/640)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((919 : ℚ)/640)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((919 : ℚ)/640)))))
    (-955047/62500000 : ℝ)
    _
    (by approx)
    ?_
    ?_
  · approx
  · decide +kernel


private theorem u9_im_adverse_le :
    ((919/640 : ℝ) ^ (-(35/64 : ℝ)) - (919/640 : ℝ) ^ (-(61/64 : ℝ)))
      * Real.sin ((15/2 : ℝ) * Real.log (919/640 : ℝ))
      * omegaPartial 3 (919/640 : ℝ)
      ≤ (2557/5000000 : ℝ) := by
  have hu0 : (0 : ℝ) < (919/640 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine le_of_lt <| _root_.Interval.approx_lt
    ((_root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((919 : ℚ)/640)) * _root_.Interval.ofRat (35/64)))
      - _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((919 : ℚ)/640)) * _root_.Interval.ofRat (61/64))))
     * _root_.Interval.sin ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((919 : ℚ)/640)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((919 : ℚ)/640)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((919 : ℚ)/640)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((919 : ℚ)/640)))))
    (2557/5000000 : _root_.Interval)
    _
    (2557/5000000 : ℝ)
    ?_
    (by approx)
    ?_
  · approx
  · decide +kernel

private theorem u9_im_tight_ge :
    (4916589/10000000000 : ℝ)
      ≤ ((919/640 : ℝ) ^ (-(71/128 : ℝ)) - (919/640 : ℝ) ^ (-(121/128 : ℝ)))
        * Real.sin ((15/2 : ℝ) * Real.log (919/640 : ℝ))
        * omegaPartial 3 (919/640 : ℝ) := by
  have hu0 : (0 : ℝ) < (919/640 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine _root_.Interval.approx_le
    (4916589/10000000000 : _root_.Interval)
    ((_root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((919 : ℚ)/640)) * _root_.Interval.ofRat (71/128)))
      - _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((919 : ℚ)/640)) * _root_.Interval.ofRat (121/128))))
     * _root_.Interval.sin ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((919 : ℚ)/640)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((919 : ℚ)/640)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((919 : ℚ)/640)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((919 : ℚ)/640)))))
    (4916589/10000000000 : ℝ)
    _
    (by approx)
    ?_
    ?_
  · approx
  · decide +kernel


theorem node_9_bounds (σ : ℝ)
    (hσ0 : (57/64 : ℝ) ≤ σ) (hσ1 : σ ≤ 29/32) :
    ((-955047/62500000 : ℝ)) ≤ realThetaReIntegrandN 3 σ 15 (919/640 : ℝ)
    ∧ realThetaReIntegrandN 3 σ 15 (919/640 : ℝ) ≤ (0)
    ∧ ((4916589/10000000000 : ℝ)) ≤ realThetaImIntegrandN 3 σ 15 (919/640 : ℝ)
    ∧ realThetaImIntegrandN 3 σ 15 (919/640 : ℝ) ≤ ((2557/5000000 : ℝ)) := by
  have hu1 : (1 : ℝ) ≤ (919/640 : ℝ) := by norm_num
  have hA_nn : (0 : ℝ) ≤ (919/640 : ℝ)^(σ/2 - 1) + (919/640 : ℝ)^((1-σ)/2 - 1) :=
    box0_pow_sum_nonneg σ hu1
  have hA_hi : (919/640 : ℝ)^(σ/2 - 1) + (919/640 : ℝ)^((1-σ)/2 - 1)
      ≤ (919/640 : ℝ)^(-(35/64 : ℝ)) + (919/640 : ℝ)^(-(61/64 : ℝ)) :=
    by
    have h := PrincipiaTractalis.RiemannXiBoxParametric.box_pow_sum_ub (σhi := (29/32 : ℝ)) hu1
      (by linarith) hσ1
    have e1 : ((29/32 : ℝ))/2 - 1 = -(35/64 : ℝ) := by norm_num
    have e2 : (1 - (29/32 : ℝ))/2 - 1 = -(61/64 : ℝ) := by norm_num
    rw [e1, e2] at h; exact h
  have hD_nn : (0 : ℝ) ≤ (919/640 : ℝ)^(σ/2 - 1) - (919/640 : ℝ)^((1-σ)/2 - 1) :=
    box0_pow_diff_nonneg (by linarith) hu1
  have hD_hi : (919/640 : ℝ)^(σ/2 - 1) - (919/640 : ℝ)^((1-σ)/2 - 1)
      ≤ (919/640 : ℝ)^(-(35/64 : ℝ)) - (919/640 : ℝ)^(-(61/64 : ℝ)) :=
    by
    have h := PrincipiaTractalis.RiemannXiBoxParametric.box_pow_diff_ub (σhi := (29/32 : ℝ)) hu1 hσ1
    have e1 : ((29/32 : ℝ))/2 - 1 = -(35/64 : ℝ) := by norm_num
    have e2 : (1 - (29/32 : ℝ))/2 - 1 = -(61/64 : ℝ) := by norm_num
    rw [e1, e2] at h; exact h
  have hW_nn : (0 : ℝ) ≤ omegaPartial 3 (919/640 : ℝ) := omegaPartial_nonneg_here 3 _
  have hAstar_nn : (0 : ℝ) ≤ (919/640 : ℝ)^(-(35/64 : ℝ)) + (919/640 : ℝ)^(-(61/64 : ℝ)) := by
    have h := box0_pow_sum_nonneg ((29/32) : ℝ) hu1
    have eq1 : ((29/32 : ℝ))/2 - 1 = -(35/64 : ℝ) := by norm_num
    have eq2 : (1 - (29/32 : ℝ))/2 - 1 = -(61/64 : ℝ) := by norm_num
    rw [eq1, eq2] at h; exact h
  have hDstar_nn : (0 : ℝ) ≤ (919/640 : ℝ)^(-(35/64 : ℝ)) - (919/640 : ℝ)^(-(61/64 : ℝ)) := by
    have h := box0_pow_diff_nonneg (σ := (29/32 : ℝ)) (by norm_num) hu1
    have eq1 : ((29/32 : ℝ))/2 - 1 = -(35/64 : ℝ) := by norm_num
    have eq2 : (1 - (29/32 : ℝ))/2 - 1 = -(61/64 : ℝ) := by norm_num
    rw [eq1, eq2] at h; exact h
  have hC : Real.cos ((15/2 : ℝ) * Real.log (919/640 : ℝ)) ≤ 0 := u9_cos_np
  have hS : Real.sin ((15/2 : ℝ) * Real.log (919/640 : ℝ)) ≥ 0 := u9_sin_nn
  have hRe := re_scalar_bounds_cos_neg
    (A_lo := 0)
    (A_hi := (919/640 : ℝ)^(-(35/64 : ℝ)) + (919/640 : ℝ)^(-(61/64 : ℝ)))
    (C_lo := Real.cos ((15/2 : ℝ) * Real.log (919/640 : ℝ)))
    (C_hi := 0) (W_lo := 0) (W_hi := omegaPartial 3 (919/640 : ℝ))
    (le_refl 0) hAstar_nn hC hC (le_refl 0)
    (le_refl 0) hW_nn
    hA_nn hA_hi (le_refl _) hC hW_nn (le_refl _)
  have hIm := im_scalar_bounds_sin_nonneg
    (D_lo := 0)
    (D_hi := (919/640 : ℝ)^(-(35/64 : ℝ)) - (919/640 : ℝ)^(-(61/64 : ℝ)))
    (S_lo := 0)
    (S_hi := Real.sin ((15/2 : ℝ) * Real.log (919/640 : ℝ)))
    (W_lo := 0) (W_hi := omegaPartial 3 (919/640 : ℝ))
    (le_refl 0) hDstar_nn (le_refl 0) hS
    (le_refl 0) hW_nn
    hD_nn hD_hi hS (le_refl _) hW_nn (le_refl _)
  refine ⟨?_, ?_, ?_, ?_⟩
  · unfold realThetaReIntegrandN
    linarith [hRe.1, u9_re_adverse_ge]
  · unfold realThetaReIntegrandN
    have h2 : (0 : ℝ) * 0 * 0 = 0 := by norm_num
    linarith [hRe.2]
  · unfold realThetaImIntegrandN
    have hDlo : (919/640 : ℝ)^(-(71/128 : ℝ)) - (919/640 : ℝ)^(-(121/128 : ℝ))
        ≤ (919/640 : ℝ)^(σ/2 - 1) - (919/640 : ℝ)^((1-σ)/2 - 1) := by
      have h := PrincipiaTractalis.RiemannXiBoxParametric.box_pow_diff_lb
        (σlo := (57/64 : ℝ)) hu1 hσ0
      have e1 : ((57/64 : ℝ))/2 - 1 = -(71/128 : ℝ) := by norm_num
      have e2 : (1 - (57/64 : ℝ))/2 - 1 = -(121/128 : ℝ) := by norm_num
      rw [e1, e2] at h; exact h
    have hSW : (0 : ℝ) ≤ Real.sin ((15/2 : ℝ) * Real.log (919/640 : ℝ))
        * omegaPartial 3 (919/640 : ℝ) := mul_nonneg hS hW_nn
    have hchain : ((919/640 : ℝ)^(-(71/128 : ℝ)) - (919/640 : ℝ)^(-(121/128 : ℝ)))
          * Real.sin ((15/2 : ℝ) * Real.log (919/640 : ℝ))
          * omegaPartial 3 (919/640 : ℝ)
        ≤ ((919/640 : ℝ)^(σ/2 - 1) - (919/640 : ℝ)^((1-σ)/2 - 1))
          * Real.sin ((15/2 : ℝ) * Real.log (919/640 : ℝ))
          * omegaPartial 3 (919/640 : ℝ) := by
      calc ((919/640 : ℝ)^(-(71/128 : ℝ)) - (919/640 : ℝ)^(-(121/128 : ℝ)))
            * Real.sin ((15/2 : ℝ) * Real.log (919/640 : ℝ))
            * omegaPartial 3 (919/640 : ℝ)
          = ((919/640 : ℝ)^(-(71/128 : ℝ)) - (919/640 : ℝ)^(-(121/128 : ℝ)))
            * (Real.sin ((15/2 : ℝ) * Real.log (919/640 : ℝ))
              * omegaPartial 3 (919/640 : ℝ)) := by ring
        _ ≤ ((919/640 : ℝ)^(σ/2 - 1) - (919/640 : ℝ)^((1-σ)/2 - 1))
            * (Real.sin ((15/2 : ℝ) * Real.log (919/640 : ℝ))
              * omegaPartial 3 (919/640 : ℝ)) :=
          mul_le_mul_of_nonneg_right hDlo hSW
        _ = ((919/640 : ℝ)^(σ/2 - 1) - (919/640 : ℝ)^((1-σ)/2 - 1))
            * Real.sin ((15/2 : ℝ) * Real.log (919/640 : ℝ))
            * omegaPartial 3 (919/640 : ℝ) := by ring
    linarith [u9_im_tight_ge, hchain]
  · unfold realThetaImIntegrandN
    linarith [hIm.2, u9_im_adverse_le]


/-! ## Panel 4 chunk sum -/

theorem seg14_p4_chunk_bounds (σ : ℝ)
    (hσ0 : (57/64 : ℝ) ≤ σ) (hσ1 : σ ≤ 29/32) :
    ((-955047/62500000 : ℝ)) ≤ realThetaReIntegrandN 3 σ 15 (919/640 : ℝ)
    ∧ realThetaReIntegrandN 3 σ 15 (919/640 : ℝ) ≤ ((0/1 : ℝ))
    ∧ ((4916589/10000000000 : ℝ)) ≤ realThetaImIntegrandN 3 σ 15 (919/640 : ℝ)
    ∧ realThetaImIntegrandN 3 σ 15 (919/640 : ℝ) ≤ ((2557/5000000 : ℝ)) := by
  have h9 := node_9_bounds σ hσ0 hσ1
  refine ⟨?_, ?_, ?_, ?_⟩
  · linarith [h9.1]
  · linarith [h9.2.1]
  · linarith [h9.2.2.1]
  · linarith [h9.2.2.2]

end PrincipiaTractalis.RiemannXiBox110Panels.Seg14P4
