/-
# PF.Analytic.RiemannXiBox108Bridge

**Section-8 consumption layer for r331b box 108** -- sigma in [55/64, 7/8].

AUTO-GENERATED by scripts/emit_box_bridge.py.  Do not edit by hand.

Chains the 40 certified OPT-40-TIGHT segment integrals in GEOMETRIC order
(segment index order = geometric order) into a single intervalIntegral over
[1, 5], rewrites it as the set integral over Ioc 1 5, instantiates T := 5, and
applies the section-8 analytic envelope EXACTLY ONCE via
RiemannXiBox0Envelope.box0_envelope_le, which has no hypotheses and no sigma
and is therefore reusable verbatim by every box.

The 39+39 adjacent-interval joins, the two integrability lemmas and the two
Ioc rewrites are sigma-universal and are IMPORTED from box 0's bridge rather
than re-emitted.

Error ledger (locked): node rounding and composite-midpoint error are already
inside each box108_seg{j}_*_integral_* endpoint and are NEVER re-subtracted
here.  The only error applied at this layer is the section-8 envelope.

Certified Lambda-0 endpoints (exact rationals, after one envelope application):
  RE_LO = 195302807046820212601488901565450990996694242254087/44033689957518419558400000000000000000000000000000000
        ~ 4.435304132705e-03
  IM_LO ~ 2.004955314766e-04
  IM_HI ~ 4.335134219295e-04

HEADLINE FIGURE for this box -- xi-space margin against the -1/10000 target:

    xi margin ~ +1.950668e-04

xi top-edge bound: Re xi(sigma+15i) <= -18884273057/64000000000000
                                     ~ -2.950667665e-04   <   -1e-4

Internal enclosure check (NOT the headline).  These are Lambda-space margins of
the certified endpoints against the DECLARED box bounds.  They sit near 1e-13 by
construction, because the declared bounds are outward-rounded at 1e-12 -- that is
the rounding step, not a measure of tightness.  Quoting them as the box's margin
would misread as knife-edge when the consumer margin above is healthy.
  RE     margin = 31031861868007766256650990996694242254087/44033689957518419558400000000000000000000000000000000
         ~ +7.047300e-13
  IM_LO  margin ~ +4.765853e-13
  IM_HI  margin ~ +7.052567e-14

SPDX-License-Identifier: Apache-2.0
-/

import PF.Analytic.RiemannXiBox0Bridge
import PF.Analytic.RiemannXiBox108Panels.Seg01
import PF.Analytic.RiemannXiBox108Panels.Seg02
import PF.Analytic.RiemannXiBox108Panels.Seg03
import PF.Analytic.RiemannXiBox108Panels.Seg04
import PF.Analytic.RiemannXiBox108Panels.Seg05
import PF.Analytic.RiemannXiBox108Panels.Seg06
import PF.Analytic.RiemannXiBox108Panels.Seg07
import PF.Analytic.RiemannXiBox108Panels.Seg08
import PF.Analytic.RiemannXiBox108Panels.Seg09
import PF.Analytic.RiemannXiBox108Panels.Seg10
import PF.Analytic.RiemannXiBox108Panels.Seg11
import PF.Analytic.RiemannXiBox108Panels.Seg12
import PF.Analytic.RiemannXiBox108Panels.Seg13
import PF.Analytic.RiemannXiBox108Panels.Seg14
import PF.Analytic.RiemannXiBox108Panels.Seg15
import PF.Analytic.RiemannXiBox108Panels.Seg16
import PF.Analytic.RiemannXiBox108Panels.Seg17
import PF.Analytic.RiemannXiBox108Panels.Seg18
import PF.Analytic.RiemannXiBox108Panels.Seg19
import PF.Analytic.RiemannXiBox108Panels.Seg20
import PF.Analytic.RiemannXiBox108Panels.Seg21
import PF.Analytic.RiemannXiBox108Panels.Seg22
import PF.Analytic.RiemannXiBox108Panels.Seg23
import PF.Analytic.RiemannXiBox108Panels.Seg24
import PF.Analytic.RiemannXiBox108Panels.Seg25
import PF.Analytic.RiemannXiBox108Panels.Seg26
import PF.Analytic.RiemannXiBox108Panels.Seg27
import PF.Analytic.RiemannXiBox108Panels.Seg28
import PF.Analytic.RiemannXiBox108Panels.Seg29
import PF.Analytic.RiemannXiBox108Panels.Seg30
import PF.Analytic.RiemannXiBox108Panels.Seg31
import PF.Analytic.RiemannXiBox108Panels.Seg32
import PF.Analytic.RiemannXiBox108Panels.Seg33
import PF.Analytic.RiemannXiBox108Panels.Seg34
import PF.Analytic.RiemannXiBox108Panels.Seg35
import PF.Analytic.RiemannXiBox108Panels.Seg36
import PF.Analytic.RiemannXiBox108Panels.Seg37
import PF.Analytic.RiemannXiBox108Panels.Seg38
import PF.Analytic.RiemannXiBox108Panels.Seg39
import PF.Analytic.RiemannXiBox108Panels.Seg40

namespace PrincipiaTractalis.RiemannXiBox108Bridge

open scoped Real
open MeasureTheory
open PrincipiaTractalis.RiemannXiThetaRealFormAndBoxes
open PrincipiaTractalis.RiemannXiEntire
-- sigma-universal infrastructure, reused verbatim from box 0.  Selective open
-- so that box 0's own finite_* / *_Lambda0_* names cannot shadow ours.
open PrincipiaTractalis.RiemannXiBox0Bridge (re_join_1 re_join_2 re_join_3 re_join_4 re_join_5 re_join_6 re_join_7 re_join_8 re_join_9 re_join_10 re_join_11 re_join_12 re_join_13 re_join_14 re_join_15 re_join_16 re_join_17 re_join_18 re_join_19 re_join_20 re_join_21 re_join_22 re_join_23 re_join_24 re_join_25 re_join_26 re_join_27 re_join_28 re_join_29 re_join_30 re_join_31 re_join_32 re_join_33 re_join_34 re_join_35 re_join_36 re_join_37 re_join_38 re_join_39 im_join_1 im_join_2 im_join_3 im_join_4 im_join_5 im_join_6 im_join_7 im_join_8 im_join_9 im_join_10 im_join_11 im_join_12 im_join_13 im_join_14 im_join_15 im_join_16 im_join_17 im_join_18 im_join_19 im_join_20 im_join_21 im_join_22 im_join_23 im_join_24 im_join_25 im_join_26 im_join_27 im_join_28 im_join_29 im_join_30 im_join_31 im_join_32 im_join_33 im_join_34 im_join_35 im_join_36 im_join_37 im_join_38 im_join_39 re_interval_eq_Ioc im_interval_eq_Ioc)
open PrincipiaTractalis.RiemannXiBox108Panels.Seg01
open PrincipiaTractalis.RiemannXiBox108Panels.Seg02
open PrincipiaTractalis.RiemannXiBox108Panels.Seg03
open PrincipiaTractalis.RiemannXiBox108Panels.Seg04
open PrincipiaTractalis.RiemannXiBox108Panels.Seg05
open PrincipiaTractalis.RiemannXiBox108Panels.Seg06
open PrincipiaTractalis.RiemannXiBox108Panels.Seg07
open PrincipiaTractalis.RiemannXiBox108Panels.Seg08
open PrincipiaTractalis.RiemannXiBox108Panels.Seg09
open PrincipiaTractalis.RiemannXiBox108Panels.Seg10
open PrincipiaTractalis.RiemannXiBox108Panels.Seg11
open PrincipiaTractalis.RiemannXiBox108Panels.Seg12
open PrincipiaTractalis.RiemannXiBox108Panels.Seg13
open PrincipiaTractalis.RiemannXiBox108Panels.Seg14
open PrincipiaTractalis.RiemannXiBox108Panels.Seg15
open PrincipiaTractalis.RiemannXiBox108Panels.Seg16
open PrincipiaTractalis.RiemannXiBox108Panels.Seg17
open PrincipiaTractalis.RiemannXiBox108Panels.Seg18
open PrincipiaTractalis.RiemannXiBox108Panels.Seg19
open PrincipiaTractalis.RiemannXiBox108Panels.Seg20
open PrincipiaTractalis.RiemannXiBox108Panels.Seg21
open PrincipiaTractalis.RiemannXiBox108Panels.Seg22
open PrincipiaTractalis.RiemannXiBox108Panels.Seg23
open PrincipiaTractalis.RiemannXiBox108Panels.Seg24
open PrincipiaTractalis.RiemannXiBox108Panels.Seg25
open PrincipiaTractalis.RiemannXiBox108Panels.Seg26
open PrincipiaTractalis.RiemannXiBox108Panels.Seg27
open PrincipiaTractalis.RiemannXiBox108Panels.Seg28
open PrincipiaTractalis.RiemannXiBox108Panels.Seg29
open PrincipiaTractalis.RiemannXiBox108Panels.Seg30
open PrincipiaTractalis.RiemannXiBox108Panels.Seg31
open PrincipiaTractalis.RiemannXiBox108Panels.Seg32
open PrincipiaTractalis.RiemannXiBox108Panels.Seg33
open PrincipiaTractalis.RiemannXiBox108Panels.Seg34
open PrincipiaTractalis.RiemannXiBox108Panels.Seg35
open PrincipiaTractalis.RiemannXiBox108Panels.Seg36
open PrincipiaTractalis.RiemannXiBox108Panels.Seg37
open PrincipiaTractalis.RiemannXiBox108Panels.Seg38
open PrincipiaTractalis.RiemannXiBox108Panels.Seg39
open PrincipiaTractalis.RiemannXiBox108Panels.Seg40

/-! ## Section B.3 -- cumulative bounds over [1, 5] (exact rationals) -/

set_option maxHeartbeats 4000000 in
theorem finite_re_lower (σ : ℝ)
    (hσ0 : (55/64 : ℝ) ≤ σ) (hσ1 : σ ≤ 7/8) :
    (195311613784811716285400581565450990996694242254087/44033689957518419558400000000000000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..5/1, realThetaReIntegrandN 3 σ 15 u := by
  have s1 := box108_seg1_re_integral_lower σ hσ0 hσ1
  have c1 : (160624439080484443/63700992000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..33/32, realThetaReIntegrandN 3 σ 15 u := s1
  have s2 := box108_seg2_re_integral_lower σ hσ0 hσ1
  have c2 : (85442158099665076237/18409586688000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..17/16, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_1 σ]
    linarith [c1, s2]
  have s3 := box108_seg3_re_integral_lower σ hσ0 hσ1
  have c3 : (7457290331289516196819/1178213548032000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..35/32, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_2 σ]
    linarith [c2, s3]
  have s4 := box108_seg4_re_integral_lower σ hσ0 hσ1
  have c4 : (44728034762407343846561/5891067740160000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..9/8, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_3 σ]
    linarith [c3, s4]
  have s5 := box108_seg5_re_integral_lower σ hσ0 hσ1
  have c5 : (1246264868443746810013049/147276693504000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..37/32, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_4 σ]
    linarith [c4, s5]
  have s6 := box108_seg6_re_integral_lower σ hσ0 hσ1
  have c6 : (64837090601258777851769801/7216557981696000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..19/16, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_5 σ]
    linarith [c5, s6]
  have s7 := box108_seg7_re_integral_lower σ hσ0 hσ1
  have c7 : (66493522529036874382425641/7216557981696000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..39/32, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_6 σ]
    linarith [c6, s7]
  have s8 := box108_seg8_re_integral_lower σ hσ0 hσ1
  have c8 : (11228727593499218945981129009/1219598298906624000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..5/4, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_7 σ]
    linarith [c7, s8]
  have s9 := box108_seg9_re_integral_lower σ hσ0 hσ1
  have c9 : (10997642139827338199869489361/1219598298906624000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..41/32, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_8 σ]
    linarith [c8, s9]
  have s10 := box108_seg10_re_integral_lower σ hσ0 hσ1
  have c10 : (1060480735165641355470483023/121959829890662400000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..21/16, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_9 σ]
    linarith [c9, s10]
  have s11 := box108_seg11_re_integral_lower σ hσ0 hσ1
  have c11 : (611258534653432746526211887987/73785697083850752000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..43/32, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_10 σ]
    linarith [c10, s11]
  have s12 := box108_seg12_re_integral_lower σ hσ0 hσ1
  have c12 : (2885419047880962551902732961771/368928485419253760000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..11/8, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_11 σ]
    linarith [c11, s12]
  have s13 := box108_seg13_re_integral_lower σ hσ0 hσ1
  have c13 : (67660645080920783736588504273473/9223212135481344000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..45/32, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_12 σ]
    linarith [c12, s13]
  have s14 := box108_seg14_re_integral_lower σ hσ0 hσ1
  have c14 : (632005602544786923073282310981933/92232121354813440000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..23/16, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_13 σ]
    linarith [c13, s14]
  have s15 := box108_seg15_re_integral_lower σ hσ0 hσ1
  have c15 : (589185082153121255137232088825233/92232121354813440000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..47/32, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_14 σ]
    linarith [c14, s15]
  have s16 := box108_seg16_re_integral_lower σ hσ0 hσ1
  have c16 : (549305437375644181532551402383833/92232121354813440000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..3/2, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_15 σ]
    linarith [c15, s16]
  have s17 := box108_seg17_re_integral_lower σ hσ0 hσ1
  have c17 : (254488365378106626068902294260371417/48790792196696309760000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..25/16, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_16 σ]
    linarith [c16, s17]
  have s18 := box108_seg18_re_integral_lower σ hσ0 hσ1
  have c18 : (45475197473920093957038057967346341/9758158439339261952000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..13/8, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_17 σ]
    linarith [c17, s18]
  have s19 := box108_seg19_re_integral_lower σ hσ0 hσ1
  have c19 : (75393489606182095406269681261812869417/17613475983007367823360000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..27/16, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_18 σ]
    linarith [c18, s19]
  have s20 := box108_seg20_re_integral_lower σ hσ0 hσ1
  have c20 : (356670922863526170989949949605491570437/88067379915036839116800000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..7/4, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_19 σ]
    linarith [c19, s20]
  have s21 := box108_seg21_re_integral_lower σ hσ0 hσ1
  have c21 : (221819366284197984503070163769801691503119/56363123145623577034752000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..29/16, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_20 σ]
    linarith [c20, s21]
  have s22 := box108_seg22_re_integral_lower σ hσ0 hσ1
  have c22 : (157185668344547336839223904726384468152477/40259373675445412167680000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..15/8, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_21 σ]
    linarith [c21, s22]
  have s23 := box108_seg23_re_integral_lower σ hσ0 hσ1
  have c23 : (158130845571683372481486305692965532802333/40259373675445412167680000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..31/16, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_22 σ]
    linarith [c22, s23]
  have s24 := box108_seg24_re_integral_lower σ hσ0 hσ1
  have c24 : (160362292316979798673994130043257759243341/40259373675445412167680000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..2/1, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_23 σ]
    linarith [c23, s24]
  have s25 := box108_seg25_re_integral_lower σ hσ0 hσ1
  have c25 : (830914363586053414710504788163051225061441/201296868377227060838400000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..17/8, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_24 σ]
    linarith [c24, s25]
  have s26 := box108_seg26_re_integral_lower σ hσ0 hσ1
  have c26 : (4287685099014079051112863745766829181917457/1006484341886135304192000000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..9/4, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_25 σ]
    linarith [c25, s26]
  have s27 := box108_seg27_re_integral_lower σ hσ0 hσ1
  have c27 : (2739170885925579060242173298217960333271479041/629052713678834565120000000000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..19/8, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_26 σ]
    linarith [c26, s27]
  have s28 := box108_seg28_re_integral_lower σ hσ0 hσ1
  have c28 : (13874783438437757603196734644353292547010963493/3145263568394172825600000000000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..5/2, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_27 σ]
    linarith [c27, s28]
  have s29 := box108_seg29_re_integral_lower σ hσ0 hσ1
  have c29 : (488804635213358192447984366123640374245521975167/110084224893796048896000000000000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..21/8, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_28 σ]
    linarith [c28, s29]
  have s30 := box108_seg30_re_integral_lower σ hσ0 hσ1
  have c30 : (6125702705472134350159091763638989999905833028391/1376052811172450611200000000000000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..11/4, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_29 σ]
    linarith [c29, s30]
  have s31 := box108_seg31_re_integral_lower σ hσ0 hσ1
  have c31 : (6128228727511090703160229831532887234882019426341/1376052811172450611200000000000000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..23/8, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_30 σ]
    linarith [c30, s31]
  have s32 := box108_seg32_re_integral_lower σ hσ0 hσ1
  have c32 : (195995638467151007456929885857990584532760170759887/44033689957518419558400000000000000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..3/1, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_31 σ]
    linarith [c31, s32]
  have s33 := box108_seg33_re_integral_lower σ hσ0 hσ1
  have c33 : (195673685359299410348794955950844487571236100228687/44033689957518419558400000000000000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..13/4, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_32 σ]
    linarith [c32, s33]
  have s34 := box108_seg34_re_integral_lower σ hσ0 hσ1
  have c34 : (195455661216429836872229033774920549407806941533487/44033689957518419558400000000000000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..7/2, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_33 σ]
    linarith [c33, s34]
  have s35 := box108_seg35_re_integral_lower σ hσ0 hσ1
  have c35 : (195355971969682199717757683367747461600091334469287/44033689957518419558400000000000000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..15/4, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_34 σ]
    linarith [c34, s35]
  have s36 := box108_seg36_re_integral_lower σ hσ0 hσ1
  have c36 : (195321114421641590170640502564128306514374699688487/44033689957518419558400000000000000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..4/1, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_35 σ]
    linarith [c35, s36]
  have s37 := box108_seg37_re_integral_lower σ hσ0 hσ1
  have c37 : (195312006500091041116362637004687001140632271431687/44033689957518419558400000000000000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..17/4, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_36 σ]
    linarith [c36, s37]
  have s38 := box108_seg38_re_integral_lower σ hσ0 hσ1
  have c38 : (195310945298356048708895529313864997850949732308487/44033689957518419558400000000000000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..9/2, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_37 σ]
    linarith [c37, s38]
  have s39 := box108_seg39_re_integral_lower σ hσ0 hσ1
  have c39 : (195311084371426831204568842858419449839100019281287/44033689957518419558400000000000000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..19/4, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_38 σ]
    linarith [c38, s39]
  have s40 := box108_seg40_re_integral_lower σ hσ0 hσ1
  have c40 : (195311613784811716285400581565450990996694242254087/44033689957518419558400000000000000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..5/1, realThetaReIntegrandN 3 σ 15 u := by
    rw [← re_join_39 σ]
    linarith [c39, s40]
  exact c40

set_option maxHeartbeats 4000000 in
theorem finite_re_upper (σ : ℝ)
    (hσ0 : (55/64 : ℝ) ≤ σ) (hσ1 : σ ≤ 7/8) :
    (∫ u in (1/1 : ℝ)..5/1, realThetaReIntegrandN 3 σ 15 u) ≤ (431618203449312894323334294978549009003305757745913/44033689957518419558400000000000000000000000000000000 : ℝ) := by
  have s1 := box108_seg1_re_integral_upper σ hσ0 hσ1
  have c1 : (∫ u in (1/1 : ℝ)..33/32, realThetaReIntegrandN 3 σ 15 u) ≤ (160641279545000357/63700992000000000000 : ℝ) := s1
  have s2 := box108_seg2_re_integral_upper σ hσ0 hσ1
  have c2 : (∫ u in (1/1 : ℝ)..17/16, realThetaReIntegrandN 3 σ 15 u) ≤ (85451851378625150963/18409586688000000000000 : ℝ) := by
    rw [← re_join_1 σ]
    linarith [c1, s2]
  have s3 := box108_seg3_re_integral_upper σ hσ0 hσ1
  have c3 : (∫ u in (1/1 : ℝ)..35/32, realThetaReIntegrandN 3 σ 15 u) ≤ (7458202645788913089581/1178213548032000000000000 : ℝ) := by
    rw [← re_join_2 σ]
    linarith [c2, s3]
  have s4 := box108_seg4_re_integral_upper σ hσ0 hσ1
  have c4 : (∫ u in (1/1 : ℝ)..9/8, realThetaReIntegrandN 3 σ 15 u) ≤ (44734162713527535897439/5891067740160000000000000 : ℝ) := by
    rw [← re_join_3 σ]
    linarith [c3, s4]
  have s5 := box108_seg5_re_integral_upper σ hσ0 hσ1
  have c5 : (∫ u in (1/1 : ℝ)..37/32, realThetaReIntegrandN 3 σ 15 u) ≤ (1246454899124669712226951/147276693504000000000000000 : ℝ) := by
    rw [← re_join_4 σ]
    linarith [c4, s5]
  have s6 := box108_seg6_re_integral_upper σ hσ0 hσ1
  have c6 : (∫ u in (1/1 : ℝ)..19/16, realThetaReIntegrandN 3 σ 15 u) ≤ (64848261321531652704390199/7216557981696000000000000000 : ℝ) := by
    rw [← re_join_5 σ]
    linarith [c5, s6]
  have s7 := box108_seg7_re_integral_upper σ hσ0 hσ1
  have c7 : (∫ u in (1/1 : ℝ)..39/32, realThetaReIntegrandN 3 σ 15 u) ≤ (66506617890038777037734359/7216557981696000000000000000 : ℝ) := by
    rw [← re_join_6 σ]
    linarith [c6, s7]
  have s8 := box108_seg8_re_integral_upper σ hσ0 hσ1
  have c8 : (∫ u in (1/1 : ℝ)..5/4, realThetaReIntegrandN 3 σ 15 u) ≤ (11267585356497980882355510991/1219598298906624000000000000000 : ℝ) := by
    rw [← re_join_7 σ]
    linarith [c7, s8]
  have s9 := box108_seg9_re_integral_upper σ hσ0 hσ1
  have c9 : (∫ u in (1/1 : ℝ)..41/32, realThetaReIntegrandN 3 σ 15 u) ≤ (11267645882213927027251150639/1219598298906624000000000000000 : ℝ) := by
    rw [← re_join_8 σ]
    linarith [c8, s9]
  have s10 := box108_seg10_re_integral_upper σ hσ0 hσ1
  have c10 : (∫ u in (1/1 : ℝ)..21/16, realThetaReIntegrandN 3 σ 15 u) ≤ (1126770074273031478245740977/121959829890662400000000000000 : ℝ) := by
    rw [← re_join_9 σ]
    linarith [c9, s10]
  have s11 := box108_seg11_re_integral_upper σ hσ0 hσ1
  have c11 : (∫ u in (1/1 : ℝ)..43/32, realThetaReIntegrandN 3 σ 15 u) ≤ (681699475779147314891956432013/73785697083850752000000000000000 : ℝ) := by
    rw [← re_join_10 σ]
    linarith [c10, s11]
  have s12 := box108_seg12_re_integral_upper σ hσ0 hσ1
  have c12 : (∫ u in (1/1 : ℝ)..11/8, realThetaReIntegrandN 3 σ 15 u) ≤ (3408513608173850995436428638229/368928485419253760000000000000000 : ℝ) := by
    rw [← re_join_11 σ]
    linarith [c11, s12]
  have s13 := box108_seg13_re_integral_upper σ hσ0 hσ1
  have c13 : (∫ u in (1/1 : ℝ)..45/32, realThetaReIntegrandN 3 σ 15 u) ≤ (85213285164965077258754855726527/9223212135481344000000000000000000 : ℝ) := by
    rw [← re_join_12 σ]
    linarith [c12, s13]
  have s14 := box108_seg14_re_integral_upper σ hσ0 hσ1
  have c14 : (∫ u in (1/1 : ℝ)..23/16, realThetaReIntegrandN 3 σ 15 u) ≤ (852136886076703081626109689018067/92232121354813440000000000000000000 : ℝ) := by
    rw [← re_join_13 σ]
    linarith [c13, s14]
  have s15 := box108_seg15_re_integral_upper σ hσ0 hσ1
  have c15 : (∫ u in (1/1 : ℝ)..47/32, realThetaReIntegrandN 3 σ 15 u) ≤ (852141400620848475617583911174767/92232121354813440000000000000000000 : ℝ) := by
    rw [← re_join_14 σ]
    linarith [c14, s15]
  have s16 := box108_seg16_re_integral_upper σ hσ0 hσ1
  have c16 : (∫ u in (1/1 : ℝ)..3/2, realThetaReIntegrandN 3 σ 15 u) ≤ (852145495270422633363832597616167/92232121354813440000000000000000000 : ℝ) := by
    rw [← re_join_15 σ]
    linarith [c15, s16]
  have s17 := box108_seg17_re_integral_upper σ hσ0 hσ1
  have c17 : (∫ u in (1/1 : ℝ)..25/16, realThetaReIntegrandN 3 σ 15 u) ≤ (450787370758179216596707177739628583/48790792196696309760000000000000000000 : ℝ) := by
    rw [← re_join_16 σ]
    linarith [c16, s17]
  have s18 := box108_seg18_re_integral_upper σ hσ0 hσ1
  have c18 : (∫ u in (1/1 : ℝ)..13/8, realThetaReIntegrandN 3 σ 15 u) ≤ (90157948193836581745655471632653659/9758158439339261952000000000000000000 : ℝ) := by
    rw [← re_join_17 σ]
    linarith [c17, s18]
  have s19 := box108_seg19_re_integral_upper σ hσ0 hσ1
  have c19 : (∫ u in (1/1 : ℝ)..27/16, realThetaReIntegrandN 3 σ 15 u) ≤ (162735955133774845618056303250187130583/17613475983007367823360000000000000000000 : ℝ) := by
    rw [← re_join_18 σ]
    linarith [c18, s19]
  have s20 := box108_seg20_re_integral_upper σ hσ0 hσ1
  have c20 : (∫ u in (1/1 : ℝ)..7/4, realThetaReIntegrandN 3 σ 15 u) ≤ (813684183711745147450747088474508429563/88067379915036839116800000000000000000000 : ℝ) := by
    rw [← re_join_19 σ]
    linarith [c19, s20]
  have s21 := box108_seg21_re_integral_upper σ hσ0 hσ1
  have c21 : (∫ u in (1/1 : ℝ)..29/16, realThetaReIntegrandN 3 σ 15 u) ≤ (520760493509815342995354597778998308496881/56363123145623577034752000000000000000000000 : ℝ) := by
    rw [← re_join_20 σ]
    linarith [c20, s21]
  have s22 := box108_seg22_re_integral_upper σ hσ0 hσ1
  have c22 : (∫ u in (1/1 : ℝ)..15/8, realThetaReIntegrandN 3 σ 15 u) ≤ (371973786986569081940253427241615531847523/40259373675445412167680000000000000000000000 : ℝ) := by
    rw [← re_join_21 σ]
    linarith [c21, s22]
  have s23 := box108_seg23_re_integral_upper σ hσ0 hσ1
  have c23 : (∫ u in (1/1 : ℝ)..31/16, realThetaReIntegrandN 3 σ 15 u) ≤ (372937668167463863430189127267034467197667/40259373675445412167680000000000000000000000 : ℝ) := by
    rw [← re_join_22 σ]
    linarith [c22, s23]
  have s24 := box108_seg24_re_integral_upper σ hσ0 hσ1
  have c24 : (∫ u in (1/1 : ℝ)..2/1, realThetaReIntegrandN 3 σ 15 u) ≤ (375187331813665582806073716100742240756659/40259373675445412167680000000000000000000000 : ℝ) := by
    rw [← re_join_23 σ]
    linarith [c23, s24]
  have s25 := box108_seg25_re_integral_upper σ hσ0 hσ1
  have c25 : (∫ u in (1/1 : ℝ)..17/8, realThetaReIntegrandN 3 σ 15 u) ≤ (1905209911046977451801825476412948774938559/201296868377227060838400000000000000000000000 : ℝ) := by
    rw [← re_join_24 σ]
    linarith [c24, s25]
  have s26 := box108_seg26_re_integral_upper σ hσ0 hσ1
  have c26 : (∫ u in (1/1 : ℝ)..9/4, realThetaReIntegrandN 3 σ 15 u) ≤ (9660141396749168308625762322713170818082543/1006484341886135304192000000000000000000000000 : ℝ) := by
    rw [← re_join_25 σ]
    linarith [c25, s26]
  have s27 := box108_seg27_re_integral_upper σ hσ0 hσ1
  have c27 : (∫ u in (1/1 : ℝ)..19/8, realThetaReIntegrandN 3 σ 15 u) ≤ (6097497555540538938767318272982039666728520959/629052713678834565120000000000000000000000000000 : ℝ) := by
    rw [← re_join_26 σ]
    linarith [c26, s27]
  have s28 := box108_seg28_re_integral_upper σ hσ0 hσ1
  have c28 : (∫ u in (1/1 : ℝ)..5/2, realThetaReIntegrandN 3 σ 15 u) ≤ (30668716954173888576949639051646707452989036507/3145263568394172825600000000000000000000000000000 : ℝ) := by
    rw [← re_join_27 σ]
    linarith [c27, s28]
  have s29 := box108_seg29_re_integral_upper σ hσ0 hσ1
  have c29 : (∫ u in (1/1 : ℝ)..21/8, realThetaReIntegrandN 3 σ 15 u) ≤ (1076673368743341366621649484436359625754478024833/110084224893796048896000000000000000000000000000000 : ℝ) := by
    rw [← re_join_28 σ]
    linarith [c28, s29]
  have s30 := box108_seg30_re_integral_upper σ hσ0 hσ1
  have c30 : (∫ u in (1/1 : ℝ)..11/4, realThetaReIntegrandN 3 σ 15 u) ≤ (13474905147384921038718953768361010000094166971609/1376052811172450611200000000000000000000000000000000 : ℝ) := by
    rw [← re_join_29 σ]
    linarith [c29, s30]
  have s31 := box108_seg31_re_integral_upper σ hσ0 hσ1
  have c31 : (∫ u in (1/1 : ℝ)..23/8, realThetaReIntegrandN 3 σ 15 u) ≤ (13478415234515337519252479380467112765117980573659/1376052811172450611200000000000000000000000000000000 : ℝ) := by
    rw [← re_join_30 σ]
    linarith [c30, s31]
  have s32 := box108_seg32_re_integral_upper σ hσ0 hσ1
  have c32 : (∫ u in (1/1 : ℝ)..3/1, realThetaReIntegrandN 3 σ 15 u) ≤ (431311202421732920995888876766009415467239829240113/44033689957518419558400000000000000000000000000000000 : ℝ) := by
    rw [← re_join_31 σ]
    linarith [c31, s32]
  have s33 := box108_seg33_re_integral_upper σ hσ0 hσ1
  have c33 : (∫ u in (1/1 : ℝ)..13/4, realThetaReIntegrandN 3 σ 15 u) ≤ (431313255175412142537773986513155512428763899771313/44033689957518419558400000000000000000000000000000000 : ℝ) := by
    rw [← re_join_32 σ]
    linarith [c32, s33]
  have s34 := box108_seg34_re_integral_upper σ hσ0 hσ1
  have c34 : (∫ u in (1/1 : ℝ)..7/2, realThetaReIntegrandN 3 σ 15 u) ≤ (431315345533415226016058815569079450592193058466513/44033689957518419558400000000000000000000000000000000 : ℝ) := by
    rw [← re_join_33 σ]
    linarith [c33, s34]
  have s35 := box108_seg35_re_integral_upper σ hσ0 hσ1
  have c35 : (∫ u in (1/1 : ℝ)..15/4, realThetaReIntegrandN 3 σ 15 u) ≤ (431317495615932683002121293016252538399908665530713/44033689957518419558400000000000000000000000000000000 : ℝ) := by
    rw [← re_join_34 σ]
    linarith [c34, s35]
  have s36 := box108_seg36_re_integral_upper σ hσ0 hσ1
  have c36 : (∫ u in (1/1 : ℝ)..4/1, realThetaReIntegrandN 3 σ 15 u) ≤ (431319247535020981263453979739871693485625300311513/44033689957518419558400000000000000000000000000000000 : ℝ) := by
    rw [← re_join_35 σ]
    linarith [c35, s36]
  have s37 := box108_seg37_re_integral_upper σ hσ0 hσ1
  have c37 : (∫ u in (1/1 : ℝ)..17/4, realThetaReIntegrandN 3 σ 15 u) ≤ (431321032103510470535579038899312998859367728568313/44033689957518419558400000000000000000000000000000000 : ℝ) := by
    rw [← re_join_36 σ]
    linarith [c36, s37]
  have s38 := box108_seg38_re_integral_upper σ hσ0 hσ1
  have c38 : (∫ u in (1/1 : ℝ)..9/2, realThetaReIntegrandN 3 σ 15 u) ≤ (431395867716347705615827786270135002149050267691513/44033689957518419558400000000000000000000000000000000 : ℝ) := by
    rw [← re_join_37 σ]
    linarith [c37, s38]
  have s39 := box108_seg39_re_integral_upper σ hσ0 hσ1
  have c39 : (∫ u in (1/1 : ℝ)..19/4, realThetaReIntegrandN 3 σ 15 u) ≤ (431507442665120271819554378005580550160899980718713/44033689957518419558400000000000000000000000000000000 : ℝ) := by
    rw [← re_join_38 σ]
    linarith [c38, s39]
  have s40 := box108_seg40_re_integral_upper σ hσ0 hσ1
  have c40 : (∫ u in (1/1 : ℝ)..5/1, realThetaReIntegrandN 3 σ 15 u) ≤ (431618203449312894323334294978549009003305757745913/44033689957518419558400000000000000000000000000000000 : ℝ) := by
    rw [← re_join_39 σ]
    linarith [c39, s40]
  exact c40

set_option maxHeartbeats 4000000 in
theorem finite_im_lower (σ : ℝ)
    (hσ0 : (55/64 : ℝ) ≤ σ) (hσ1 : σ ≤ 7/8) :
    (8837364808899338182842004925450990996694242254087/44033689957518419558400000000000000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..5/1, realThetaImIntegrandN 3 σ 15 u := by
  have s1 := box108_seg1_im_integral_lower σ hσ0 hσ1
  have c1 : (63882378788443/63700992000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..33/32, realThetaImIntegrandN 3 σ 15 u := s1
  have s2 := box108_seg2_im_integral_lower σ hσ0 hσ1
  have c2 : (134614484057063437/18409586688000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..17/16, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_1 σ]
    linarith [c1, s2]
  have s3 := box108_seg3_im_integral_lower σ hσ0 hσ1
  have c3 : (25590582549130200019/1178213548032000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..35/32, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_2 σ]
    linarith [c2, s3]
  have s4 := box108_seg4_im_integral_lower σ hσ0 hσ1
  have c4 : (264169783514396390561/5891067740160000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..9/8, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_3 σ]
    linarith [c3, s4]
  have s5 := box108_seg5_im_integral_lower σ hσ0 hσ1
  have c5 : (11156163847243217053049/147276693504000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..37/32, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_4 σ]
    linarith [c4, s5]
  have s6 := box108_seg6_im_integral_lower σ hσ0 hσ1
  have c6 : (812409853936824203129801/7216557981696000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..19/16, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_5 σ]
    linarith [c5, s6]
  have s7 := box108_seg7_im_integral_lower σ hσ0 hσ1
  have c7 : (1104234248620893469785641/7216557981696000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..39/32, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_6 σ]
    linarith [c6, s7]
  have s8 := box108_seg8_im_integral_lower σ hσ0 hσ1
  have c8 : (237421572668380665133769009/1219598298906624000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..5/4, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_7 σ]
    linarith [c7, s8]
  have s9 := box108_seg9_im_integral_lower σ hσ0 hσ1
  have c9 : (287035493697340321966129361/1219598298906624000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..41/32, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_8 σ]
    linarith [c8, s9]
  have s10 := box108_seg10_im_integral_lower σ hσ0 hσ1
  have c10 : (33321424026690578081427023/121959829890662400000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..21/16, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_9 σ]
    linarith [c9, s10]
  have s11 := box108_seg11_im_integral_lower σ hσ0 hσ1
  have c11 : (22640270057594241330364207987/73785697083850752000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..43/32, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_10 σ]
    linarith [c10, s11]
  have s12 := box108_seg12_im_integral_lower σ hσ0 hσ1
  have c12 : (123685695411869432050598561771/368928485419253760000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..11/8, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_11 σ]
    linarith [c11, s12]
  have s13 := box108_seg13_im_integral_lower σ hσ0 hσ1
  have c13 : (3301146000167804455170264273473/9223212135481344000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..45/32, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_12 σ]
    linarith [c12, s13]
  have s14 := box108_seg14_im_integral_lower σ hσ0 hσ1
  have c14 : (34555324611388102288027910981933/92232121354813440000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..23/16, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_13 σ]
    linarith [c13, s14]
  have s15 := box108_seg15_im_integral_lower σ hσ0 hσ1
  have c15 : (35564570269952089015145688825233/92232121354813440000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..47/32, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_14 σ]
    linarith [c14, s15]
  have s16 := box108_seg16_im_integral_lower σ hσ0 hσ1
  have c16 : (36074473927848432177953002383833/92232121354813440000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..3/2, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_15 σ]
    linarith [c15, s16]
  have s17 := box108_seg17_im_integral_lower σ hσ0 hσ1
  have c17 : (18934614021482570436927996660371417/48790792196696309760000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..25/16, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_16 σ]
    linarith [c16, s17]
  have s18 := box108_seg18_im_integral_lower σ hσ0 hσ1
  have c18 : (3614237595138186311081163247346341/9758158439339261952000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..13/8, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_17 σ]
    linarith [c17, s18]
  have s19 := box108_seg19_im_integral_lower σ hσ0 hσ1
  have c19 : (6055735467380514015827242708212869417/17613475983007367823360000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..27/16, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_18 σ]
    linarith [c18, s19]
  have s20 := box108_seg20_im_integral_lower σ hσ0 hσ1
  have c20 : (27605762927179626378108721317491570437/88067379915036839116800000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..7/4, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_19 σ]
    linarith [c19, s20]
  have s21 := box108_seg21_im_integral_lower σ hσ0 hσ1
  have c21 : (15963940811812681911523232487881691503119/56363123145623577034752000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..29/16, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_20 σ]
    linarith [c20, s21]
  have s22 := box108_seg22_im_integral_lower σ hσ0 hσ1
  have c22 : (1470871789651074237624387768226352593211/5751339096492201738240000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..15/8, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_21 σ]
    linarith [c21, s22]
  have s23 := box108_seg23_im_integral_lower σ hσ0 hσ1
  have c23 : (1337067692252302372326711764595076114619/5751339096492201738240000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..31/16, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_22 σ]
    linarith [c22, s23]
  have s24 := box108_seg24_im_integral_lower σ hσ0 hσ1
  have c24 : (1230880113737646253503464216922537034763/5751339096492201738240000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..2/1, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_23 σ]
    linarith [c23, s24]
  have s25 := box108_seg25_im_integral_lower σ hσ0 hσ1
  have c25 : (5489199665300664272131190811864460723063/28756695482461008691200000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..17/8, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_24 σ]
    linarith [c24, s25]
  have s26 := box108_seg26_im_integral_lower σ hσ0 hσ1
  have c26 : (26179306610384723489179648252404168845351/143783477412305043456000000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..9/4, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_25 σ]
    linarith [c25, s26]
  have s27 := box108_seg27_im_integral_lower σ hσ0 hσ1
  have c27 : (16342840922412420590828304316851476181639863/89864673382690652160000000000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..19/8, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_26 σ]
    linarith [c26, s27]
  have s28 := box108_seg28_im_integral_lower σ hσ0 hσ1
  have c28 : (83340784151056727530971600621898935287280499/449323366913453260800000000000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..5/2, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_27 σ]
    linarith [c27, s28]
  have s29 := box108_seg29_im_integral_lower σ hσ0 hσ1
  have c29 : (20921942534120120556802439723640374245521975167/110084224893796048896000000000000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..21/8, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_28 σ]
    linarith [c28, s29]
  have s30 := box108_seg30_im_integral_lower σ hσ0 hσ1
  have c30 : (267133593906345854480971443638989999905833028391/1376052811172450611200000000000000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..11/4, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_29 σ]
    linarith [c29, s30]
  have s31 := box108_seg31_im_integral_lower σ hσ0 hσ1
  have c31 : (271349101096723922993012551532887234882019426341/1376052811172450611200000000000000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..23/8, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_30 σ]
    linarith [c30, s31]
  have s32 := box108_seg32_im_integral_lower σ hσ0 hσ1
  have c32 : (8773096421760473502924392097990584532760170759887/44033689957518419558400000000000000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..3/1, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_31 σ]
    linarith [c31, s32]
  have s33 := box108_seg33_im_integral_lower σ hσ0 hσ1
  have c33 : (8855570922797412475550335150844487571236100228687/44033689957518419558400000000000000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..13/4, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_32 σ]
    linarith [c32, s33]
  have s34 := box108_seg34_im_integral_lower σ hσ0 hσ1
  have c34 : (8869782478974580863329644334920549407806941533487/44033689957518419558400000000000000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..7/2, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_33 σ]
    linarith [c33, s34]
  have s35 := box108_seg35_im_integral_lower σ hσ0 hσ1
  have c35 : (8862403395774668564944606887747461600091334469287/44033689957518419558400000000000000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..15/4, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_34 σ]
    linarith [c34, s35]
  have s36 := box108_seg36_im_integral_lower σ hσ0 hσ1
  have c36 : (8853312528360117233685520164128306514374699688487/44033689957518419558400000000000000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..4/1, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_35 σ]
    linarith [c35, s36]
  have s37 := box108_seg37_im_integral_lower σ hσ0 hσ1
  have c37 : (8846298959188172649237901004687001140632271431687/44033689957518419558400000000000000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..17/4, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_36 σ]
    linarith [c36, s37]
  have s38 := box108_seg38_im_integral_lower σ hσ0 hσ1
  have c38 : (8842284197699279693778913633864997850949732308487/44033689957518419558400000000000000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..9/2, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_37 σ]
    linarith [c37, s38]
  have s39 := box108_seg39_im_integral_lower σ hσ0 hσ1
  have c39 : (8839142210447102598214881898419449839100019281287/44033689957518419558400000000000000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..19/4, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_38 σ]
    linarith [c38, s39]
  have s40 := box108_seg40_im_integral_lower σ hσ0 hσ1
  have c40 : (8837364808899338182842004925450990996694242254087/44033689957518419558400000000000000000000000000000000 : ℝ) ≤ ∫ u in (1/1 : ℝ)..5/1, realThetaImIntegrandN 3 σ 15 u := by
    rw [← im_join_39 σ]
    linarith [c39, s40]
  exact c40

set_option maxHeartbeats 4000000 in
theorem finite_im_upper (σ : ℝ)
    (hσ0 : (55/64 : ℝ) ≤ σ) (hσ1 : σ ≤ 7/8) :
    (∫ u in (1/1 : ℝ)..5/1, realThetaImIntegrandN 3 σ 15 u) ≤ (19080388875673835717720982978549009003305757745913/44033689957518419558400000000000000000000000000000000 : ℝ) := by
  have s1 := box108_seg1_im_integral_upper σ hσ0 hσ1
  have c1 : (∫ u in (1/1 : ℝ)..33/32, realThetaImIntegrandN 3 σ 15 u) ≤ (73053343400357/63700992000000000000 : ℝ) := s1
  have s2 := box108_seg2_im_integral_upper σ hσ0 hσ1
  have c2 : (∫ u in (1/1 : ℝ)..17/16, realThetaImIntegrandN 3 σ 15 u) ≤ (144190846913150963/18409586688000000000000 : ℝ) := by
    rw [← im_join_1 σ]
    linarith [c1, s2]
  have s3 := box108_seg3_im_integral_upper σ hσ0 hσ1
  have c3 : (∫ u in (1/1 : ℝ)..35/32, realThetaImIntegrandN 3 σ 15 u) ≤ (27064481436298689581/1178213548032000000000000 : ℝ) := by
    rw [← im_join_2 σ]
    linarith [c2, s3]
  have s4 := box108_seg4_im_integral_upper σ hσ0 hσ1
  have c4 : (∫ u in (1/1 : ℝ)..9/8, realThetaImIntegrandN 3 σ 15 u) ≤ (278020272932079897439/5891067740160000000000000 : ℝ) := by
    rw [← im_join_3 σ]
    linarith [c3, s4]
  have s5 := box108_seg5_im_integral_upper σ hσ0 hσ1
  have c5 : (∫ u in (1/1 : ℝ)..37/32, realThetaImIntegrandN 3 σ 15 u) ≤ (11714747278658832226951/147276693504000000000000000 : ℝ) := by
    rw [← im_join_4 σ]
    linarith [c4, s5]
  have s6 := box108_seg6_im_integral_upper σ hσ0 hσ1
  have c6 : (∫ u in (1/1 : ℝ)..19/16, realThetaImIntegrandN 3 σ 15 u) ≤ (852073171656473184390199/7216557981696000000000000000 : ℝ) := by
    rw [← im_join_5 σ]
    linarith [c5, s6]
  have s7 := box108_seg7_im_integral_upper σ hσ0 hσ1
  have c7 : (∫ u in (1/1 : ℝ)..39/32, realThetaImIntegrandN 3 σ 15 u) ≤ (1157257463364519117734359/7216557981696000000000000000 : ℝ) := by
    rw [← im_join_6 σ]
    linarith [c6, s7]
  have s8 := box108_seg8_im_integral_upper σ hσ0 hσ1
  have c8 : (∫ u in (1/1 : ℝ)..5/4, realThetaImIntegrandN 3 σ 15 u) ≤ (248710852075040701875510991/1219598298906624000000000000000 : ℝ) := by
    rw [← im_join_7 σ]
    linarith [c7, s8]
  have s9 := box108_seg9_im_integral_upper σ hσ0 hσ1
  have c9 : (∫ u in (1/1 : ℝ)..41/32, realThetaImIntegrandN 3 σ 15 u) ≤ (300609069550373470771150639/1219598298906624000000000000000 : ℝ) := by
    rw [← im_join_8 σ]
    linarith [c8, s9]
  have s10 := box108_seg10_im_integral_upper σ hσ0 hσ1
  have c10 : (∫ u in (1/1 : ℝ)..21/16, realThetaImIntegrandN 3 σ 15 u) ≤ (34891111173001780197740977/121959829890662400000000000000 : ℝ) := by
    rw [← im_join_9 σ]
    linarith [c9, s10]
  have s11 := box108_seg11_im_integral_upper σ hσ0 hσ1
  have c11 : (∫ u in (1/1 : ℝ)..43/32, realThetaImIntegrandN 3 σ 15 u) ≤ (23705285149375865998516432013/73785697083850752000000000000000 : ℝ) := by
    rw [← im_join_10 σ]
    linarith [c10, s11]
  have s12 := box108_seg12_im_integral_upper σ hσ0 hσ1
  have c12 : (∫ u in (1/1 : ℝ)..11/8, realThetaImIntegrandN 3 σ 15 u) ≤ (129500774325004898233228638229/368928485419253760000000000000000 : ℝ) := by
    rw [← im_join_11 σ]
    linarith [c11, s12]
  have s13 := box108_seg13_im_integral_upper σ hσ0 hσ1
  have c13 : (∫ u in (1/1 : ℝ)..45/32, realThetaImIntegrandN 3 σ 15 u) ≤ (3456545799593455667714855726527/9223212135481344000000000000000000 : ℝ) := by
    rw [← im_join_12 σ]
    linarith [c12, s13]
  have s14 := box108_seg14_im_integral_upper σ hσ0 hσ1
  have c14 : (∫ u in (1/1 : ℝ)..23/16, realThetaImIntegrandN 3 σ 15 u) ≤ (36184938028516423117309689018067/92232121354813440000000000000000000 : ℝ) := by
    rw [← im_join_13 σ]
    linarith [c13, s14]
  have s15 := box108_seg15_im_integral_upper σ hσ0 hσ1
  have c15 : (∫ u in (1/1 : ℝ)..47/32, realThetaImIntegrandN 3 σ 15 u) ≤ (37247527939829067540783911174767/92232121354813440000000000000000000 : ℝ) := by
    rw [← im_join_14 σ]
    linarith [c14, s15]
  have s16 := box108_seg16_im_integral_upper σ hσ0 hσ1
  have c16 : (∫ u in (1/1 : ℝ)..3/2, realThetaImIntegrandN 3 σ 15 u) ≤ (37788138120325860551032597616167/92232121354813440000000000000000000 : ℝ) := by
    rw [← im_join_15 σ]
    linarith [c15, s16]
  have s17 := box108_seg17_im_integral_upper σ hσ0 hσ1
  have c17 : (∫ u in (1/1 : ℝ)..25/16, realThetaImIntegrandN 3 σ 15 u) ≤ (20041517368998062721455977739628583/48790792196696309760000000000000000000 : ℝ) := by
    rw [← im_join_16 σ]
    linarith [c16, s17]
  have s18 := box108_seg18_im_integral_upper σ hσ0 hσ1
  have c18 : (∫ u in (1/1 : ℝ)..13/8, realThetaImIntegrandN 3 σ 15 u) ≤ (4008777516000350970605231632653659/9758158439339261952000000000000000000 : ℝ) := by
    rw [← im_join_17 σ]
    linarith [c17, s18]
  have s19 := box108_seg19_im_integral_upper σ hσ0 hσ1
  have c19 : (∫ u in (1/1 : ℝ)..27/16, realThetaImIntegrandN 3 σ 15 u) ≤ (7236702060280449069090620050187130583/17613475983007367823360000000000000000000 : ℝ) := by
    rw [← im_join_18 σ]
    linarith [c18, s19]
  have s20 := box108_seg20_im_integral_upper σ hσ0 hσ1
  have c20 : (∫ u in (1/1 : ℝ)..7/4, realThetaImIntegrandN 3 σ 15 u) ≤ (36187918344273164705918672474508429563/88067379915036839116800000000000000000000 : ℝ) := by
    rw [← im_join_19 σ]
    linarith [c19, s20]
  have s21 := box108_seg21_im_integral_upper σ hσ0 hσ1
  have c21 : (∫ u in (1/1 : ℝ)..29/16, realThetaImIntegrandN 3 σ 15 u) ≤ (23162883674633274038664411538998308496881/56363123145623577034752000000000000000000000 : ℝ) := by
    rw [← im_join_20 σ]
    linarith [c20, s21]
  have s22 := box108_seg22_im_integral_upper σ hσ0 hσ1
  have c22 : (∫ u in (1/1 : ℝ)..15/8, realThetaImIntegrandN 3 σ 15 u) ≤ (16546922818581889828331865641615531847523/40259373675445412167680000000000000000000000 : ℝ) := by
    rw [← im_join_21 σ]
    linarith [c21, s22]
  have s23 := box108_seg23_im_integral_upper σ hσ0 hσ1
  have c23 : (∫ u in (1/1 : ℝ)..31/16, realThetaImIntegrandN 3 σ 15 u) ≤ (16548837234250884306376365667034467197667/40259373675445412167680000000000000000000000 : ℝ) := by
    rw [← im_join_22 σ]
    linarith [c22, s23]
  have s24 := box108_seg24_im_integral_upper σ hσ0 hσ1
  have c24 : (∫ u in (1/1 : ℝ)..2/1, realThetaImIntegrandN 3 σ 15 u) ≤ (16550685850240234836232154500742240756659/40259373675445412167680000000000000000000000 : ℝ) := by
    rw [← im_join_23 σ]
    linarith [c23, s24]
  have s25 := box108_seg25_im_integral_upper σ hσ0 hσ1
  have c25 : (∫ u in (1/1 : ℝ)..17/8, realThetaImIntegrandN 3 σ 15 u) ≤ (82763148989511327983235268412948774938559/201296868377227060838400000000000000000000000 : ℝ) := by
    rw [← im_join_24 σ]
    linarith [c24, s25]
  have s26 := box108_seg26_im_integral_upper σ hσ0 hσ1
  have c26 : (∫ u in (1/1 : ℝ)..9/4, realThetaImIntegrandN 3 σ 15 u) ≤ (413866937388772690948491282713170818082543/1006484341886135304192000000000000000000000000 : ℝ) := by
    rw [← im_join_25 σ]
    linarith [c25, s26]
  have s27 := box108_seg27_im_integral_upper σ hσ0 hσ1
  have c27 : (∫ u in (1/1 : ℝ)..19/8, realThetaImIntegrandN 3 σ 15 u) ≤ (259128178049965515685564672982039666728520959/629052713678834565120000000000000000000000000000 : ℝ) := by
    rw [← im_join_26 σ]
    linarith [c26, s27]
  have s28 := box108_seg28_im_integral_upper σ hσ0 hσ1
  have c28 : (∫ u in (1/1 : ℝ)..5/2, realThetaImIntegrandN 3 σ 15 u) ≤ (1307846840326839019659271051646707452989036507/3145263568394172825600000000000000000000000000000 : ℝ) := by
    rw [← im_join_27 σ]
    linarith [c27, s28]
  have s29 := box108_seg29_im_integral_upper σ hσ0 hσ1
  have c29 : (∫ u in (1/1 : ℝ)..21/8, realThetaImIntegrandN 3 σ 15 u) ≤ (46311155060057780699552204436359625754478024833/110084224893796048896000000000000000000000000000000 : ℝ) := by
    rw [← im_join_28 σ]
    linarith [c28, s29]
  have s30 := box108_seg30_im_integral_upper σ hσ0 hσ1
  have c30 : (∫ u in (1/1 : ℝ)..11/4, realThetaImIntegrandN 3 σ 15 u) ≤ (584897583229696937424257768361010000094166971609/1376052811172450611200000000000000000000000000000000 : ℝ) := by
    rw [← im_join_29 σ]
    linarith [c29, s30]
  have s31 := box108_seg31_im_integral_upper σ hσ0 hσ1
  have c31 : (∫ u in (1/1 : ℝ)..23/8, realThetaImIntegrandN 3 σ 15 u) ≤ (589451177075252526337943380467112765117980573659/1376052811172450611200000000000000000000000000000000 : ℝ) := by
    rw [← im_join_30 σ]
    linarith [c30, s31]
  have s32 := box108_seg32_im_integral_upper σ hσ0 hσ1
  have c32 : (∫ u in (1/1 : ℝ)..3/1, realThetaImIntegrandN 3 σ 15 u) ≤ (18960469872510596897816044766009415467239829240113/44033689957518419558400000000000000000000000000000000 : ℝ) := by
    rw [← im_join_31 σ]
    linarith [c31, s32]
  have s33 := box108_seg33_im_integral_upper σ hσ0 hσ1
  have c33 : (∫ u in (1/1 : ℝ)..13/4, realThetaImIntegrandN 3 σ 15 u) ≤ (19051385058840199361393314513155512428763899771313/44033689957518419558400000000000000000000000000000000 : ℝ) := by
    rw [← im_join_32 σ]
    linarith [c32, s33]
  have s34 := box108_seg34_im_integral_upper σ hσ0 hσ1
  have c34 : (∫ u in (1/1 : ℝ)..7/2, realThetaImIntegrandN 3 σ 15 u) ≤ (19071088892826290207501503569079450592193058466513/44033689957518419558400000000000000000000000000000000 : ℝ) := by
    rw [← im_join_33 σ]
    linarith [c33, s34]
  have s35 := box108_seg35_im_integral_upper σ hσ0 hσ1
  have c35 : (∫ u in (1/1 : ℝ)..15/4, realThetaImIntegrandN 3 σ 15 u) ≤ (19073238975343747193563981016252538399908665530713/44033689957518419558400000000000000000000000000000000 : ℝ) := by
    rw [← im_join_34 σ]
    linarith [c34, s35]
  have s36 := box108_seg36_im_integral_upper σ hσ0 hσ1
  have c36 : (∫ u in (1/1 : ℝ)..4/1, realThetaImIntegrandN 3 σ 15 u) ≤ (19074990894432045454896667739871693485625300311513/44033689957518419558400000000000000000000000000000000 : ℝ) := by
    rw [← im_join_35 σ]
    linarith [c35, s36]
  have s37 := box108_seg37_im_integral_upper σ hσ0 hσ1
  have c37 : (∫ u in (1/1 : ℝ)..17/4, realThetaImIntegrandN 3 σ 15 u) ≤ (19076775462921534727021726899312998859367728568313/44033689957518419558400000000000000000000000000000000 : ℝ) := by
    rw [← im_join_36 σ]
    linarith [c36, s37]
  have s38 := box108_seg38_im_integral_upper σ hσ0 hσ1
  have c38 : (∫ u in (1/1 : ℝ)..9/2, realThetaImIntegrandN 3 σ 15 u) ≤ (19078221592496239108006474270135002149050267691513/44033689957518419558400000000000000000000000000000000 : ℝ) := by
    rw [← im_join_37 σ]
    linarith [c37, s38]
  have s39 := box108_seg39_im_integral_upper σ hσ0 hσ1
  have c39 : (∫ u in (1/1 : ℝ)..19/4, realThetaImIntegrandN 3 σ 15 u) ≤ (19079712316375009262837066005580550160899980718713/44033689957518419558400000000000000000000000000000000 : ℝ) := by
    rw [← im_join_38 σ]
    linarith [c38, s39]
  have s40 := box108_seg40_im_integral_upper σ hσ0 hσ1
  have c40 : (∫ u in (1/1 : ℝ)..5/1, realThetaImIntegrandN 3 σ 15 u) ≤ (19080388875673835717720982978549009003305757745913/44033689957518419558400000000000000000000000000000000 : ℝ) := by
    rw [← im_join_39 σ]
    linarith [c39, s40]
  exact c40

/-! ## Section B.5 -- section-8 envelope applied EXACTLY ONCE, T := 5

Section B.4 (intervalIntegral 1..5 = set integral over Ioc 1 5) is
sigma-universal and is imported from box 0 rather than re-proved. -/

theorem re_Lambda0_lower (σ : ℝ)
    (hσ0 : (55/64 : ℝ) ≤ σ) (hσ1 : σ ≤ 7/8) :
    (195302807046820212601488901565450990996694242254087/44033689957518419558400000000000000000000000000000000 : ℝ) ≤ (completedRiemannZeta₀ (⟨σ, 15⟩ : ℂ)).re := by
  have hσa : (0 : ℝ) ≤ σ := by linarith
  have hσb : σ ≤ 1 := by linarith
  have h8 := re_Lambda0_close_to_truncated_integral (N := 3) (σ := σ) (t := 15)
    (T := 5) hσa hσb (by norm_num)
  push_cast at h8
  have henv := PrincipiaTractalis.RiemannXiBox0Envelope.box0_envelope_le
  have habs := abs_le.mp (le_trans h8 henv)
  have hfin := finite_re_lower σ hσ0 hσ1
  rw [re_interval_eq_Ioc σ] at hfin
  linarith [habs.1, hfin]

theorem im_Lambda0_lower (σ : ℝ)
    (hσ0 : (55/64 : ℝ) ≤ σ) (hσ1 : σ ≤ 7/8) :
    (8828558070907834498930324925450990996694242254087/44033689957518419558400000000000000000000000000000000 : ℝ) ≤ (completedRiemannZeta₀ (⟨σ, 15⟩ : ℂ)).im := by
  have hσa : (0 : ℝ) ≤ σ := by linarith
  have hσb : σ ≤ 1 := by linarith
  have h8 := im_Lambda0_close_to_truncated_integral (N := 3) (σ := σ) (t := 15)
    (T := 5) hσa hσb (by norm_num)
  push_cast at h8
  have henv := PrincipiaTractalis.RiemannXiBox0Envelope.box0_envelope_le
  have habs := abs_le.mp (le_trans h8 henv)
  have hfin := finite_im_lower σ hσ0 hσ1
  rw [im_interval_eq_Ioc σ] at hfin
  linarith [habs.1, hfin]

theorem im_Lambda0_upper (σ : ℝ)
    (hσ0 : (55/64 : ℝ) ≤ σ) (hσ1 : σ ≤ 7/8) :
    (completedRiemannZeta₀ (⟨σ, 15⟩ : ℂ)).im ≤ (19089195613665339401632662978549009003305757745913/44033689957518419558400000000000000000000000000000000 : ℝ) := by
  have hσa : (0 : ℝ) ≤ σ := by linarith
  have hσb : σ ≤ 1 := by linarith
  have h8 := im_Lambda0_close_to_truncated_integral (N := 3) (σ := σ) (t := 15)
    (T := 5) hσa hσb (by norm_num)
  push_cast at h8
  have henv := PrincipiaTractalis.RiemannXiBox0Envelope.box0_envelope_le
  have habs := abs_le.mp (le_trans h8 henv)
  have hfin := finite_im_upper σ hσ0 hσ1
  rw [im_interval_eq_Ioc σ] at hfin
  linarith [habs.2, hfin]

theorem re_Lambda0_upper (σ : ℝ)
    (hσ0 : (55/64 : ℝ) ≤ σ) (hσ1 : σ ≤ 7/8) :
    (completedRiemannZeta₀ (⟨σ, 15⟩ : ℂ)).re ≤ (1 : ℝ) := by
  have hσa : (0 : ℝ) ≤ σ := by linarith
  have hσb : σ ≤ 1 := by linarith
  have h8 := re_Lambda0_close_to_truncated_integral (N := 3) (σ := σ) (t := 15)
    (T := 5) hσa hσb (by norm_num)
  push_cast at h8
  have henv := PrincipiaTractalis.RiemannXiBox0Envelope.box0_envelope_le
  have habs := abs_le.mp (le_trans h8 henv)
  have hfin := finite_re_upper σ hσ0 hσ1
  rw [re_interval_eq_Ioc σ] at hfin
  linarith [habs.2, hfin]

/-! ## Section B.6 -- exact rational margins -/

theorem RE_MARGIN_pos : (0 : ℝ) < (195302807046820212601488901565450990996694242254087/44033689957518419558400000000000000000000000000000000 : ℝ) - (1108826033/250000000000 : ℝ) := by norm_num

theorem IM_LO_MARGIN_pos : (0 : ℝ) < (8828558070907834498930324925450990996694242254087/44033689957518419558400000000000000000000000000000000 : ℝ) - (200495531/1000000000000 : ℝ) := by norm_num

theorem IM_HI_MARGIN_pos : (0 : ℝ) < (216756711/500000000000 : ℝ) - (19089195613665339401632662978549009003305757745913/44033689957518419558400000000000000000000000000000000 : ℝ) := by norm_num

/-! ## Section B.7 -- coefficient enclosures, r331a box enclosures, and the
unconditional box-108 top-edge bound -/

theorem box108_A_lo_bound :
    ∀ σ : ℝ, (55/64 : ℝ) ≤ σ → σ ≤ 7/8 → (-(922095/4096) : ℝ) ≤ σ * (σ - 1) - (15 : ℝ) ^ 2 := by
  intro σ h0 h1
  nlinarith [mul_nonneg (by linarith : (0 : ℝ) ≤ σ - (55/64 : ℝ))
    (by linarith : (0 : ℝ) ≤ σ + (55/64 : ℝ) - 1)]

theorem box108_A_hi_bound :
    ∀ σ : ℝ, (55/64 : ℝ) ≤ σ → σ ≤ 7/8 → σ * (σ - 1) - (15 : ℝ) ^ 2 ≤ (-(14407/64) : ℝ) := by
  intro σ h0 h1
  nlinarith [mul_nonneg (by linarith : (0 : ℝ) ≤ (7/8 : ℝ) - σ)
    (by linarith : (0 : ℝ) ≤ σ + (7/8 : ℝ) - 1)]

theorem box108_B_lo_bound :
    ∀ σ : ℝ, (55/64 : ℝ) ≤ σ → σ ≤ 7/8 → (345/32 : ℝ) ≤ (15 : ℝ) * (2 * σ - 1) := by
  intro σ h0 h1; linarith

theorem box108_B_hi_bound :
    ∀ σ : ℝ, (55/64 : ℝ) ≤ σ → σ ≤ 7/8 → (15 : ℝ) * (2 * σ - 1) ≤ (45/4 : ℝ) := by
  intro σ h0 h1; linarith

theorem box108_re_enclosure :
    PrincipiaTractalis.RiemannXiThetaBoxEnclosure.BoxReEnclosure
      (55/64 : ℝ) (7/8) 15 (1108826033/250000000000) (1) := by
  constructor
  intro σ h0 h1
  refine ⟨?_, ?_⟩
  · have := re_Lambda0_lower σ h0 h1
    linarith
  · have := re_Lambda0_upper σ h0 h1
    linarith

theorem box108_im_enclosure :
    PrincipiaTractalis.RiemannXiThetaBoxEnclosure.BoxImEnclosure
      (55/64 : ℝ) (7/8) 15 (200495531/1000000000000) (216756711/500000000000) := by
  constructor
  intro σ h0 h1
  refine ⟨?_, ?_⟩
  · have := im_Lambda0_lower σ h0 h1
    linarith
  · have := im_Lambda0_upper σ h0 h1
    linarith

/-- Worst-case arithmetic over the box rectangle.  p1*p2 is maximised at
(Ahi, RE_LO) because Ahi < 0 <= RE_LO; q1*q2 is minimised at (Blo, IM_LO)
because IM_LO >= 0.  Selecting the wrong B endpoint here is the known
soundness trap; it is resolved at generation time from the sign of the
DECLARED IM_LO, never assumed. -/
theorem box108_re_xi_le :
    ∀ σ : ℝ, (55/64 : ℝ) ≤ σ → σ ≤ 7/8 →
      (riemannXiEntire (⟨σ, 15⟩ : ℂ)).re ≤ (-(18884273057/64000000000000) : ℝ) :=
  PrincipiaTractalis.RiemannXiThetaBoxEnclosure.re_xi_upper_bound_from_enclosures
    box108_re_enclosure box108_im_enclosure
    box108_A_lo_bound box108_A_hi_bound
    box108_B_lo_bound box108_B_hi_bound
    (-(18884273057/64000000000000) : ℝ)
    (by
      intro p1 p2 q1 q2 hp1lo hp1hi hp2lo hp2hi hq1lo hq1hi hq2lo hq2hi
      have hp2nn : (0 : ℝ) ≤ p2 := le_trans (by norm_num) hp2lo
      have hq1nn : (0 : ℝ) ≤ q1 := le_trans (by norm_num) hq1lo
      have hA1 : p1 * p2 ≤ (-(14407/64) : ℝ) * p2 :=
        mul_le_mul_of_nonneg_right hp1hi hp2nn
      have hA2 : (-(14407/64) : ℝ) * p2 ≤ (-(14407/64) : ℝ) * (1108826033/250000000000 : ℝ) :=
        mul_le_mul_of_nonpos_left hp2lo (by norm_num)
      have hQ1 : q1 * (200495531/1000000000000 : ℝ) ≤ q1 * q2 :=
        mul_le_mul_of_nonneg_left hq2lo hq1nn
      have hq1bnd : (0 : ℝ) ≤ q1 - (345/32 : ℝ) := by linarith
      have himsgn : (0 : ℝ) ≤ (200495531/1000000000000 : ℝ) := by norm_num
      have hQ2 : (345/32 : ℝ) * (200495531/1000000000000 : ℝ) ≤ q1 * (200495531/1000000000000 : ℝ) := by
        nlinarith [mul_nonneg hq1bnd himsgn]
      have hAval : (-(14407/64) : ℝ) * (1108826033/250000000000 : ℝ) = (-(15974856657431/16000000000000) : ℝ) := by norm_num
      have hBval : (345/32 : ℝ) * (200495531/1000000000000 : ℝ) = (13834191639/6400000000000 : ℝ) := by norm_num
      linarith [hA1, hA2, hQ1, hQ2, hAval, hBval])

/-- **BOX 108 CLOSED** -- unconditional top-edge negativity at t = 15
for sigma in [55/64, 7/8]. -/
theorem top15_box108_re_lt_neg_1e4 {σ : ℝ}
    (h0 : (55/64 : ℝ) ≤ σ) (h1 : σ ≤ 7/8) :
    (riemannXiEntire (⟨σ, 15⟩ : ℂ)).re < -(1/10000 : ℝ) :=
  lt_of_le_of_lt (box108_re_xi_le σ h0 h1) (by norm_num)

end PrincipiaTractalis.RiemannXiBox108Bridge
