/-
# PF.Analytic.RiemannXiBox0Panels.Seg29P1

Panel 1 of Segment 29: nodes [0, 1, 2].
Auto-generated by scripts/emit_stage2_segment.py.
-/

import PF.Analytic.RiemannXiThetaRealFormAndBoxes_r331b
import Interval.Interval.Conversion
import Interval.Interval.Exp
import Interval.Interval.Log
import Interval.Interval.Sincos
import Interval.Interval.Pi
import Interval.Interval.Order
import Interval.Interval.Mul
import Interval.Tactic.Approx

namespace PrincipiaTractalis.RiemannXiBox0Panels.Seg29P1

open scoped Real
open PrincipiaTractalis.RiemannXiThetaRealFormAndBoxes
open PrincipiaTractalis.XiQuadrature

private theorem rpow_neg_eq_exp {x a : ℝ} (hx : 0 < x) :
    x ^ (-a) = Real.exp (-(Real.log x * a)) := by
  rw [Real.rpow_def_of_pos hx]; ring_nf

private theorem omegaPartial_3_closed {u : ℝ} :
    omegaPartial 3 u = Real.exp (-(π * u)) + Real.exp (-(π * 4 * u))
      + Real.exp (-(π * 9 * u)) := by
  unfold omegaPartial
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, zero_add,
             Nat.cast_zero, Nat.cast_one, Nat.cast_ofNat, one_pow]
  ring_nf

/-! ## Node 0 at u = 561/224 — cos nn, sin nn -/

private theorem u0_cos_nn : (0 : ℝ) ≤ Real.cos ((15/2 : ℝ) * Real.log (561/224 : ℝ)) := by
  refine _root_.Interval.approx_le
    ((0 : _root_.Interval))
    (_root_.Interval.cos ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((561 : ℚ)/224))))
    (0 : ℝ)
    (Real.cos ((15/2 : ℝ) * Real.log (561/224 : ℝ)))
    (by approx)
    (_root_.Interval.mem_approx_cos (by approx))
    ?_
  decide +kernel


private theorem u0_sin_nn : (0 : ℝ) ≤ Real.sin ((15/2 : ℝ) * Real.log (561/224 : ℝ)) := by
  refine _root_.Interval.approx_le
    ((0 : _root_.Interval))
    (_root_.Interval.sin ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((561 : ℚ)/224))))
    (0 : ℝ)
    (Real.sin ((15/2 : ℝ) * Real.log (561/224 : ℝ)))
    (by approx)
    (_root_.Interval.mem_approx_sin (by approx))
    ?_
  decide +kernel


private theorem u0_re_adverse_le :
    ((561/224 : ℝ) ^ (-(23/32 : ℝ)) + (561/224 : ℝ) ^ (-(25/32 : ℝ)))
        * Real.cos ((15/2 : ℝ) * Real.log (561/224 : ℝ))
        * omegaPartial 3 (561/224 : ℝ)
      ≤ (1/3125 : ℝ) := by
  have hu0 : (0 : ℝ) < (561/224 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine le_of_lt <| _root_.Interval.approx_lt
    ((_root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((561 : ℚ)/224)) * _root_.Interval.ofRat (23/32)))
      + _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((561 : ℚ)/224)) * _root_.Interval.ofRat (25/32))))
     * _root_.Interval.cos ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((561 : ℚ)/224)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((561 : ℚ)/224)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((561 : ℚ)/224)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((561 : ℚ)/224)))))
    (1/3125 : _root_.Interval)
    _
    (1/3125 : ℝ)
    ?_
    (by approx)
    ?_
  · approx
  · decide +kernel

private theorem u0_re_tight_ge :
    (1584363/5000000000 : ℝ)
      ≤ (2 * (561/224 : ℝ) ^ (-(3/4 : ℝ)))
        * Real.cos ((15/2 : ℝ) * Real.log (561/224 : ℝ))
        * omegaPartial 3 (561/224 : ℝ) := by
  have hu0 : (0 : ℝ) < (561/224 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine _root_.Interval.approx_le
    (1584363/5000000000 : _root_.Interval)
    ((2 : _root_.Interval) * _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((561 : ℚ)/224)) * _root_.Interval.ofRat (3/4)))
     * _root_.Interval.cos ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((561 : ℚ)/224)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((561 : ℚ)/224)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((561 : ℚ)/224)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((561 : ℚ)/224)))))
    (1584363/5000000000 : ℝ)
    _
    (by approx)
    ?_
    ?_
  · approx
  · decide +kernel


private theorem u0_im_adverse_le :
    ((561/224 : ℝ) ^ (-(23/32 : ℝ)) - (561/224 : ℝ) ^ (-(25/32 : ℝ)))
      * Real.sin ((15/2 : ℝ) * Real.log (561/224 : ℝ))
      * omegaPartial 3 (561/224 : ℝ)
      ≤ (63/10000000 : ℝ) := by
  have hu0 : (0 : ℝ) < (561/224 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine le_of_lt <| _root_.Interval.approx_lt
    ((_root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((561 : ℚ)/224)) * _root_.Interval.ofRat (23/32)))
      - _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((561 : ℚ)/224)) * _root_.Interval.ofRat (25/32))))
     * _root_.Interval.sin ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((561 : ℚ)/224)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((561 : ℚ)/224)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((561 : ℚ)/224)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((561 : ℚ)/224)))))
    (63/10000000 : _root_.Interval)
    _
    (63/10000000 : ℝ)
    ?_
    (by approx)
    ?_
  · approx
  · decide +kernel


theorem node_0_bounds (σ : ℝ)
    (hσ0 : (1 : ℝ)/2 ≤ σ) (hσ1 : σ ≤ 9/16) :
    ((1584363/5000000000 : ℝ)) ≤ realThetaReIntegrandN 3 σ 15 (561/224 : ℝ)
    ∧ realThetaReIntegrandN 3 σ 15 (561/224 : ℝ) ≤ ((1/3125 : ℝ))
    ∧ ((0 : ℝ)) ≤ realThetaImIntegrandN 3 σ 15 (561/224 : ℝ)
    ∧ realThetaImIntegrandN 3 σ 15 (561/224 : ℝ) ≤ ((63/10000000 : ℝ)) := by
  have hu1 : (1 : ℝ) ≤ (561/224 : ℝ) := by norm_num
  have hA_nn : (0 : ℝ) ≤ (561/224 : ℝ)^(σ/2 - 1) + (561/224 : ℝ)^((1-σ)/2 - 1) :=
    box0_pow_sum_nonneg σ hu1
  have hA_hi : (561/224 : ℝ)^(σ/2 - 1) + (561/224 : ℝ)^((1-σ)/2 - 1)
      ≤ (561/224 : ℝ)^(-(23/32 : ℝ)) + (561/224 : ℝ)^(-(25/32 : ℝ)) :=
    box0_pow_sum_tight_ub hu1 hσ0 hσ1
  have hD_nn : (0 : ℝ) ≤ (561/224 : ℝ)^(σ/2 - 1) - (561/224 : ℝ)^((1-σ)/2 - 1) :=
    box0_pow_diff_nonneg hσ0 hu1
  have hD_hi : (561/224 : ℝ)^(σ/2 - 1) - (561/224 : ℝ)^((1-σ)/2 - 1)
      ≤ (561/224 : ℝ)^(-(23/32 : ℝ)) - (561/224 : ℝ)^(-(25/32 : ℝ)) :=
    box0_pow_diff_ub hσ0 hσ1 hu1
  have hW_nn : (0 : ℝ) ≤ omegaPartial 3 (561/224 : ℝ) := omegaPartial_nonneg_here 3 _
  have hAstar_nn : (0 : ℝ) ≤ (561/224 : ℝ)^(-(23/32 : ℝ)) + (561/224 : ℝ)^(-(25/32 : ℝ)) := by
    have h := box0_pow_sum_nonneg (9/16 : ℝ) hu1
    have eq1 : ((9 : ℝ)/16)/2 - 1 = -(23/32 : ℝ) := by norm_num
    have eq2 : (1 - (9 : ℝ)/16)/2 - 1 = -(25/32 : ℝ) := by norm_num
    rw [eq1, eq2] at h; exact h
  have hDstar_nn : (0 : ℝ) ≤ (561/224 : ℝ)^(-(23/32 : ℝ)) - (561/224 : ℝ)^(-(25/32 : ℝ)) := by
    have h := box0_pow_diff_nonneg (σ := 9/16) (by norm_num) hu1
    have eq1 : ((9 : ℝ)/16)/2 - 1 = -(23/32 : ℝ) := by norm_num
    have eq2 : (1 - (9 : ℝ)/16)/2 - 1 = -(25/32 : ℝ) := by norm_num
    rw [eq1, eq2] at h; exact h
  have hC : Real.cos ((15/2 : ℝ) * Real.log (561/224 : ℝ)) ≥ 0 := u0_cos_nn
  have hS : Real.sin ((15/2 : ℝ) * Real.log (561/224 : ℝ)) ≥ 0 := u0_sin_nn
  have hRe := re_scalar_bounds_cos_nonneg
    (A_lo := 0)
    (A_hi := (561/224 : ℝ)^(-(23/32 : ℝ)) + (561/224 : ℝ)^(-(25/32 : ℝ)))
    (C_lo := 0)
    (C_hi := Real.cos ((15/2 : ℝ) * Real.log (561/224 : ℝ)))
    (W_lo := 0) (W_hi := omegaPartial 3 (561/224 : ℝ))
    (le_refl 0) hAstar_nn (le_refl 0) hC
    (le_refl 0) hW_nn
    hA_nn hA_hi hC (le_refl _) hW_nn (le_refl _)
  have hIm := im_scalar_bounds_sin_nonneg
    (D_lo := 0)
    (D_hi := (561/224 : ℝ)^(-(23/32 : ℝ)) - (561/224 : ℝ)^(-(25/32 : ℝ)))
    (S_lo := 0)
    (S_hi := Real.sin ((15/2 : ℝ) * Real.log (561/224 : ℝ)))
    (W_lo := 0) (W_hi := omegaPartial 3 (561/224 : ℝ))
    (le_refl 0) hDstar_nn (le_refl 0) hS
    (le_refl 0) hW_nn
    hD_nn hD_hi hS (le_refl _) hW_nn (le_refl _)
  refine ⟨?_, ?_, ?_, ?_⟩
  · unfold realThetaReIntegrandN
    have hAlo : 2 * (561/224 : ℝ)^(-(3/4 : ℝ))
        ≤ (561/224 : ℝ)^(σ/2 - 1) + (561/224 : ℝ)^((1-σ)/2 - 1) :=
      box0_pow_sum_tight_lb hu1 hσ0 hσ1
    have hCW : (0 : ℝ) ≤ Real.cos ((15/2 : ℝ) * Real.log (561/224 : ℝ))
        * omegaPartial 3 (561/224 : ℝ) := mul_nonneg hC hW_nn
    have hchain : 2 * (561/224 : ℝ)^(-(3/4 : ℝ))
          * Real.cos ((15/2 : ℝ) * Real.log (561/224 : ℝ))
          * omegaPartial 3 (561/224 : ℝ)
        ≤ ((561/224 : ℝ)^(σ/2 - 1) + (561/224 : ℝ)^((1-σ)/2 - 1))
          * Real.cos ((15/2 : ℝ) * Real.log (561/224 : ℝ))
          * omegaPartial 3 (561/224 : ℝ) := by
      calc 2 * (561/224 : ℝ)^(-(3/4 : ℝ))
            * Real.cos ((15/2 : ℝ) * Real.log (561/224 : ℝ))
            * omegaPartial 3 (561/224 : ℝ)
          = 2 * (561/224 : ℝ)^(-(3/4 : ℝ))
            * (Real.cos ((15/2 : ℝ) * Real.log (561/224 : ℝ))
              * omegaPartial 3 (561/224 : ℝ)) := by ring
        _ ≤ ((561/224 : ℝ)^(σ/2 - 1) + (561/224 : ℝ)^((1-σ)/2 - 1))
            * (Real.cos ((15/2 : ℝ) * Real.log (561/224 : ℝ))
              * omegaPartial 3 (561/224 : ℝ)) :=
          mul_le_mul_of_nonneg_right hAlo hCW
        _ = ((561/224 : ℝ)^(σ/2 - 1) + (561/224 : ℝ)^((1-σ)/2 - 1))
            * Real.cos ((15/2 : ℝ) * Real.log (561/224 : ℝ))
            * omegaPartial 3 (561/224 : ℝ) := by ring
    linarith [u0_re_tight_ge, hchain]
  · unfold realThetaReIntegrandN
    linarith [hRe.2, u0_re_adverse_le]
  · unfold realThetaImIntegrandN
    have h2 : (0 : ℝ) * 0 * 0 = 0 := by norm_num
    linarith [hIm.1]
  · unfold realThetaImIntegrandN
    linarith [hIm.2, u0_im_adverse_le]
/-! ## Node 1 at u = 563/224 — cos nn, sin nn -/

private theorem u1_cos_nn : (0 : ℝ) ≤ Real.cos ((15/2 : ℝ) * Real.log (563/224 : ℝ)) := by
  refine _root_.Interval.approx_le
    ((0 : _root_.Interval))
    (_root_.Interval.cos ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((563 : ℚ)/224))))
    (0 : ℝ)
    (Real.cos ((15/2 : ℝ) * Real.log (563/224 : ℝ)))
    (by approx)
    (_root_.Interval.mem_approx_cos (by approx))
    ?_
  decide +kernel


private theorem u1_sin_nn : (0 : ℝ) ≤ Real.sin ((15/2 : ℝ) * Real.log (563/224 : ℝ)) := by
  refine _root_.Interval.approx_le
    ((0 : _root_.Interval))
    (_root_.Interval.sin ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((563 : ℚ)/224))))
    (0 : ℝ)
    (Real.sin ((15/2 : ℝ) * Real.log (563/224 : ℝ)))
    (by approx)
    (_root_.Interval.mem_approx_sin (by approx))
    ?_
  decide +kernel


private theorem u1_re_adverse_le :
    ((563/224 : ℝ) ^ (-(23/32 : ℝ)) + (563/224 : ℝ) ^ (-(25/32 : ℝ)))
        * Real.cos ((15/2 : ℝ) * Real.log (563/224 : ℝ))
        * omegaPartial 3 (563/224 : ℝ)
      ≤ (31/100000 : ℝ) := by
  have hu0 : (0 : ℝ) < (563/224 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine le_of_lt <| _root_.Interval.approx_lt
    ((_root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((563 : ℚ)/224)) * _root_.Interval.ofRat (23/32)))
      + _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((563 : ℚ)/224)) * _root_.Interval.ofRat (25/32))))
     * _root_.Interval.cos ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((563 : ℚ)/224)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((563 : ℚ)/224)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((563 : ℚ)/224)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((563 : ℚ)/224)))))
    (31/100000 : _root_.Interval)
    _
    (31/100000 : ℝ)
    ?_
    (by approx)
    ?_
  · approx
  · decide +kernel

private theorem u1_re_tight_ge :
    (1507691/5000000000 : ℝ)
      ≤ (2 * (563/224 : ℝ) ^ (-(3/4 : ℝ)))
        * Real.cos ((15/2 : ℝ) * Real.log (563/224 : ℝ))
        * omegaPartial 3 (563/224 : ℝ) := by
  have hu0 : (0 : ℝ) < (563/224 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine _root_.Interval.approx_le
    (1507691/5000000000 : _root_.Interval)
    ((2 : _root_.Interval) * _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((563 : ℚ)/224)) * _root_.Interval.ofRat (3/4)))
     * _root_.Interval.cos ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((563 : ℚ)/224)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((563 : ℚ)/224)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((563 : ℚ)/224)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((563 : ℚ)/224)))))
    (1507691/5000000000 : ℝ)
    _
    (by approx)
    ?_
    ?_
  · approx
  · decide +kernel


private theorem u1_im_adverse_le :
    ((563/224 : ℝ) ^ (-(23/32 : ℝ)) - (563/224 : ℝ) ^ (-(25/32 : ℝ)))
      * Real.sin ((15/2 : ℝ) * Real.log (563/224 : ℝ))
      * omegaPartial 3 (563/224 : ℝ)
      ≤ (1/156250 : ℝ) := by
  have hu0 : (0 : ℝ) < (563/224 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine le_of_lt <| _root_.Interval.approx_lt
    ((_root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((563 : ℚ)/224)) * _root_.Interval.ofRat (23/32)))
      - _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((563 : ℚ)/224)) * _root_.Interval.ofRat (25/32))))
     * _root_.Interval.sin ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((563 : ℚ)/224)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((563 : ℚ)/224)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((563 : ℚ)/224)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((563 : ℚ)/224)))))
    (1/156250 : _root_.Interval)
    _
    (1/156250 : ℝ)
    ?_
    (by approx)
    ?_
  · approx
  · decide +kernel


theorem node_1_bounds (σ : ℝ)
    (hσ0 : (1 : ℝ)/2 ≤ σ) (hσ1 : σ ≤ 9/16) :
    ((1507691/5000000000 : ℝ)) ≤ realThetaReIntegrandN 3 σ 15 (563/224 : ℝ)
    ∧ realThetaReIntegrandN 3 σ 15 (563/224 : ℝ) ≤ ((31/100000 : ℝ))
    ∧ ((0 : ℝ)) ≤ realThetaImIntegrandN 3 σ 15 (563/224 : ℝ)
    ∧ realThetaImIntegrandN 3 σ 15 (563/224 : ℝ) ≤ ((1/156250 : ℝ)) := by
  have hu1 : (1 : ℝ) ≤ (563/224 : ℝ) := by norm_num
  have hA_nn : (0 : ℝ) ≤ (563/224 : ℝ)^(σ/2 - 1) + (563/224 : ℝ)^((1-σ)/2 - 1) :=
    box0_pow_sum_nonneg σ hu1
  have hA_hi : (563/224 : ℝ)^(σ/2 - 1) + (563/224 : ℝ)^((1-σ)/2 - 1)
      ≤ (563/224 : ℝ)^(-(23/32 : ℝ)) + (563/224 : ℝ)^(-(25/32 : ℝ)) :=
    box0_pow_sum_tight_ub hu1 hσ0 hσ1
  have hD_nn : (0 : ℝ) ≤ (563/224 : ℝ)^(σ/2 - 1) - (563/224 : ℝ)^((1-σ)/2 - 1) :=
    box0_pow_diff_nonneg hσ0 hu1
  have hD_hi : (563/224 : ℝ)^(σ/2 - 1) - (563/224 : ℝ)^((1-σ)/2 - 1)
      ≤ (563/224 : ℝ)^(-(23/32 : ℝ)) - (563/224 : ℝ)^(-(25/32 : ℝ)) :=
    box0_pow_diff_ub hσ0 hσ1 hu1
  have hW_nn : (0 : ℝ) ≤ omegaPartial 3 (563/224 : ℝ) := omegaPartial_nonneg_here 3 _
  have hAstar_nn : (0 : ℝ) ≤ (563/224 : ℝ)^(-(23/32 : ℝ)) + (563/224 : ℝ)^(-(25/32 : ℝ)) := by
    have h := box0_pow_sum_nonneg (9/16 : ℝ) hu1
    have eq1 : ((9 : ℝ)/16)/2 - 1 = -(23/32 : ℝ) := by norm_num
    have eq2 : (1 - (9 : ℝ)/16)/2 - 1 = -(25/32 : ℝ) := by norm_num
    rw [eq1, eq2] at h; exact h
  have hDstar_nn : (0 : ℝ) ≤ (563/224 : ℝ)^(-(23/32 : ℝ)) - (563/224 : ℝ)^(-(25/32 : ℝ)) := by
    have h := box0_pow_diff_nonneg (σ := 9/16) (by norm_num) hu1
    have eq1 : ((9 : ℝ)/16)/2 - 1 = -(23/32 : ℝ) := by norm_num
    have eq2 : (1 - (9 : ℝ)/16)/2 - 1 = -(25/32 : ℝ) := by norm_num
    rw [eq1, eq2] at h; exact h
  have hC : Real.cos ((15/2 : ℝ) * Real.log (563/224 : ℝ)) ≥ 0 := u1_cos_nn
  have hS : Real.sin ((15/2 : ℝ) * Real.log (563/224 : ℝ)) ≥ 0 := u1_sin_nn
  have hRe := re_scalar_bounds_cos_nonneg
    (A_lo := 0)
    (A_hi := (563/224 : ℝ)^(-(23/32 : ℝ)) + (563/224 : ℝ)^(-(25/32 : ℝ)))
    (C_lo := 0)
    (C_hi := Real.cos ((15/2 : ℝ) * Real.log (563/224 : ℝ)))
    (W_lo := 0) (W_hi := omegaPartial 3 (563/224 : ℝ))
    (le_refl 0) hAstar_nn (le_refl 0) hC
    (le_refl 0) hW_nn
    hA_nn hA_hi hC (le_refl _) hW_nn (le_refl _)
  have hIm := im_scalar_bounds_sin_nonneg
    (D_lo := 0)
    (D_hi := (563/224 : ℝ)^(-(23/32 : ℝ)) - (563/224 : ℝ)^(-(25/32 : ℝ)))
    (S_lo := 0)
    (S_hi := Real.sin ((15/2 : ℝ) * Real.log (563/224 : ℝ)))
    (W_lo := 0) (W_hi := omegaPartial 3 (563/224 : ℝ))
    (le_refl 0) hDstar_nn (le_refl 0) hS
    (le_refl 0) hW_nn
    hD_nn hD_hi hS (le_refl _) hW_nn (le_refl _)
  refine ⟨?_, ?_, ?_, ?_⟩
  · unfold realThetaReIntegrandN
    have hAlo : 2 * (563/224 : ℝ)^(-(3/4 : ℝ))
        ≤ (563/224 : ℝ)^(σ/2 - 1) + (563/224 : ℝ)^((1-σ)/2 - 1) :=
      box0_pow_sum_tight_lb hu1 hσ0 hσ1
    have hCW : (0 : ℝ) ≤ Real.cos ((15/2 : ℝ) * Real.log (563/224 : ℝ))
        * omegaPartial 3 (563/224 : ℝ) := mul_nonneg hC hW_nn
    have hchain : 2 * (563/224 : ℝ)^(-(3/4 : ℝ))
          * Real.cos ((15/2 : ℝ) * Real.log (563/224 : ℝ))
          * omegaPartial 3 (563/224 : ℝ)
        ≤ ((563/224 : ℝ)^(σ/2 - 1) + (563/224 : ℝ)^((1-σ)/2 - 1))
          * Real.cos ((15/2 : ℝ) * Real.log (563/224 : ℝ))
          * omegaPartial 3 (563/224 : ℝ) := by
      calc 2 * (563/224 : ℝ)^(-(3/4 : ℝ))
            * Real.cos ((15/2 : ℝ) * Real.log (563/224 : ℝ))
            * omegaPartial 3 (563/224 : ℝ)
          = 2 * (563/224 : ℝ)^(-(3/4 : ℝ))
            * (Real.cos ((15/2 : ℝ) * Real.log (563/224 : ℝ))
              * omegaPartial 3 (563/224 : ℝ)) := by ring
        _ ≤ ((563/224 : ℝ)^(σ/2 - 1) + (563/224 : ℝ)^((1-σ)/2 - 1))
            * (Real.cos ((15/2 : ℝ) * Real.log (563/224 : ℝ))
              * omegaPartial 3 (563/224 : ℝ)) :=
          mul_le_mul_of_nonneg_right hAlo hCW
        _ = ((563/224 : ℝ)^(σ/2 - 1) + (563/224 : ℝ)^((1-σ)/2 - 1))
            * Real.cos ((15/2 : ℝ) * Real.log (563/224 : ℝ))
            * omegaPartial 3 (563/224 : ℝ) := by ring
    linarith [u1_re_tight_ge, hchain]
  · unfold realThetaReIntegrandN
    linarith [hRe.2, u1_re_adverse_le]
  · unfold realThetaImIntegrandN
    have h2 : (0 : ℝ) * 0 * 0 = 0 := by norm_num
    linarith [hIm.1]
  · unfold realThetaImIntegrandN
    linarith [hIm.2, u1_im_adverse_le]
/-! ## Node 2 at u = 565/224 — cos nn, sin nn -/

private theorem u2_cos_nn : (0 : ℝ) ≤ Real.cos ((15/2 : ℝ) * Real.log (565/224 : ℝ)) := by
  refine _root_.Interval.approx_le
    ((0 : _root_.Interval))
    (_root_.Interval.cos ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((565 : ℚ)/224))))
    (0 : ℝ)
    (Real.cos ((15/2 : ℝ) * Real.log (565/224 : ℝ)))
    (by approx)
    (_root_.Interval.mem_approx_cos (by approx))
    ?_
  decide +kernel


private theorem u2_sin_nn : (0 : ℝ) ≤ Real.sin ((15/2 : ℝ) * Real.log (565/224 : ℝ)) := by
  refine _root_.Interval.approx_le
    ((0 : _root_.Interval))
    (_root_.Interval.sin ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((565 : ℚ)/224))))
    (0 : ℝ)
    (Real.sin ((15/2 : ℝ) * Real.log (565/224 : ℝ)))
    (by approx)
    (_root_.Interval.mem_approx_sin (by approx))
    ?_
  decide +kernel


private theorem u2_re_adverse_le :
    ((565/224 : ℝ) ^ (-(23/32 : ℝ)) + (565/224 : ℝ) ^ (-(25/32 : ℝ)))
        * Real.cos ((15/2 : ℝ) * Real.log (565/224 : ℝ))
        * omegaPartial 3 (565/224 : ℝ)
      ≤ (29/100000 : ℝ) := by
  have hu0 : (0 : ℝ) < (565/224 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine le_of_lt <| _root_.Interval.approx_lt
    ((_root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((565 : ℚ)/224)) * _root_.Interval.ofRat (23/32)))
      + _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((565 : ℚ)/224)) * _root_.Interval.ofRat (25/32))))
     * _root_.Interval.cos ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((565 : ℚ)/224)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((565 : ℚ)/224)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((565 : ℚ)/224)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((565 : ℚ)/224)))))
    (29/100000 : _root_.Interval)
    _
    (29/100000 : ℝ)
    ?_
    (by approx)
    ?_
  · approx
  · decide +kernel

private theorem u2_re_tight_ge :
    (358321/1250000000 : ℝ)
      ≤ (2 * (565/224 : ℝ) ^ (-(3/4 : ℝ)))
        * Real.cos ((15/2 : ℝ) * Real.log (565/224 : ℝ))
        * omegaPartial 3 (565/224 : ℝ) := by
  have hu0 : (0 : ℝ) < (565/224 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine _root_.Interval.approx_le
    (358321/1250000000 : _root_.Interval)
    ((2 : _root_.Interval) * _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((565 : ℚ)/224)) * _root_.Interval.ofRat (3/4)))
     * _root_.Interval.cos ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((565 : ℚ)/224)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((565 : ℚ)/224)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((565 : ℚ)/224)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((565 : ℚ)/224)))))
    (358321/1250000000 : ℝ)
    _
    (by approx)
    ?_
    ?_
  · approx
  · decide +kernel


private theorem u2_im_adverse_le :
    ((565/224 : ℝ) ^ (-(23/32 : ℝ)) - (565/224 : ℝ) ^ (-(25/32 : ℝ)))
      * Real.sin ((15/2 : ℝ) * Real.log (565/224 : ℝ))
      * omegaPartial 3 (565/224 : ℝ)
      ≤ (1/156250 : ℝ) := by
  have hu0 : (0 : ℝ) < (565/224 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine le_of_lt <| _root_.Interval.approx_lt
    ((_root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((565 : ℚ)/224)) * _root_.Interval.ofRat (23/32)))
      - _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((565 : ℚ)/224)) * _root_.Interval.ofRat (25/32))))
     * _root_.Interval.sin ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((565 : ℚ)/224)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((565 : ℚ)/224)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((565 : ℚ)/224)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((565 : ℚ)/224)))))
    (1/156250 : _root_.Interval)
    _
    (1/156250 : ℝ)
    ?_
    (by approx)
    ?_
  · approx
  · decide +kernel


theorem node_2_bounds (σ : ℝ)
    (hσ0 : (1 : ℝ)/2 ≤ σ) (hσ1 : σ ≤ 9/16) :
    ((358321/1250000000 : ℝ)) ≤ realThetaReIntegrandN 3 σ 15 (565/224 : ℝ)
    ∧ realThetaReIntegrandN 3 σ 15 (565/224 : ℝ) ≤ ((29/100000 : ℝ))
    ∧ ((0 : ℝ)) ≤ realThetaImIntegrandN 3 σ 15 (565/224 : ℝ)
    ∧ realThetaImIntegrandN 3 σ 15 (565/224 : ℝ) ≤ ((1/156250 : ℝ)) := by
  have hu1 : (1 : ℝ) ≤ (565/224 : ℝ) := by norm_num
  have hA_nn : (0 : ℝ) ≤ (565/224 : ℝ)^(σ/2 - 1) + (565/224 : ℝ)^((1-σ)/2 - 1) :=
    box0_pow_sum_nonneg σ hu1
  have hA_hi : (565/224 : ℝ)^(σ/2 - 1) + (565/224 : ℝ)^((1-σ)/2 - 1)
      ≤ (565/224 : ℝ)^(-(23/32 : ℝ)) + (565/224 : ℝ)^(-(25/32 : ℝ)) :=
    box0_pow_sum_tight_ub hu1 hσ0 hσ1
  have hD_nn : (0 : ℝ) ≤ (565/224 : ℝ)^(σ/2 - 1) - (565/224 : ℝ)^((1-σ)/2 - 1) :=
    box0_pow_diff_nonneg hσ0 hu1
  have hD_hi : (565/224 : ℝ)^(σ/2 - 1) - (565/224 : ℝ)^((1-σ)/2 - 1)
      ≤ (565/224 : ℝ)^(-(23/32 : ℝ)) - (565/224 : ℝ)^(-(25/32 : ℝ)) :=
    box0_pow_diff_ub hσ0 hσ1 hu1
  have hW_nn : (0 : ℝ) ≤ omegaPartial 3 (565/224 : ℝ) := omegaPartial_nonneg_here 3 _
  have hAstar_nn : (0 : ℝ) ≤ (565/224 : ℝ)^(-(23/32 : ℝ)) + (565/224 : ℝ)^(-(25/32 : ℝ)) := by
    have h := box0_pow_sum_nonneg (9/16 : ℝ) hu1
    have eq1 : ((9 : ℝ)/16)/2 - 1 = -(23/32 : ℝ) := by norm_num
    have eq2 : (1 - (9 : ℝ)/16)/2 - 1 = -(25/32 : ℝ) := by norm_num
    rw [eq1, eq2] at h; exact h
  have hDstar_nn : (0 : ℝ) ≤ (565/224 : ℝ)^(-(23/32 : ℝ)) - (565/224 : ℝ)^(-(25/32 : ℝ)) := by
    have h := box0_pow_diff_nonneg (σ := 9/16) (by norm_num) hu1
    have eq1 : ((9 : ℝ)/16)/2 - 1 = -(23/32 : ℝ) := by norm_num
    have eq2 : (1 - (9 : ℝ)/16)/2 - 1 = -(25/32 : ℝ) := by norm_num
    rw [eq1, eq2] at h; exact h
  have hC : Real.cos ((15/2 : ℝ) * Real.log (565/224 : ℝ)) ≥ 0 := u2_cos_nn
  have hS : Real.sin ((15/2 : ℝ) * Real.log (565/224 : ℝ)) ≥ 0 := u2_sin_nn
  have hRe := re_scalar_bounds_cos_nonneg
    (A_lo := 0)
    (A_hi := (565/224 : ℝ)^(-(23/32 : ℝ)) + (565/224 : ℝ)^(-(25/32 : ℝ)))
    (C_lo := 0)
    (C_hi := Real.cos ((15/2 : ℝ) * Real.log (565/224 : ℝ)))
    (W_lo := 0) (W_hi := omegaPartial 3 (565/224 : ℝ))
    (le_refl 0) hAstar_nn (le_refl 0) hC
    (le_refl 0) hW_nn
    hA_nn hA_hi hC (le_refl _) hW_nn (le_refl _)
  have hIm := im_scalar_bounds_sin_nonneg
    (D_lo := 0)
    (D_hi := (565/224 : ℝ)^(-(23/32 : ℝ)) - (565/224 : ℝ)^(-(25/32 : ℝ)))
    (S_lo := 0)
    (S_hi := Real.sin ((15/2 : ℝ) * Real.log (565/224 : ℝ)))
    (W_lo := 0) (W_hi := omegaPartial 3 (565/224 : ℝ))
    (le_refl 0) hDstar_nn (le_refl 0) hS
    (le_refl 0) hW_nn
    hD_nn hD_hi hS (le_refl _) hW_nn (le_refl _)
  refine ⟨?_, ?_, ?_, ?_⟩
  · unfold realThetaReIntegrandN
    have hAlo : 2 * (565/224 : ℝ)^(-(3/4 : ℝ))
        ≤ (565/224 : ℝ)^(σ/2 - 1) + (565/224 : ℝ)^((1-σ)/2 - 1) :=
      box0_pow_sum_tight_lb hu1 hσ0 hσ1
    have hCW : (0 : ℝ) ≤ Real.cos ((15/2 : ℝ) * Real.log (565/224 : ℝ))
        * omegaPartial 3 (565/224 : ℝ) := mul_nonneg hC hW_nn
    have hchain : 2 * (565/224 : ℝ)^(-(3/4 : ℝ))
          * Real.cos ((15/2 : ℝ) * Real.log (565/224 : ℝ))
          * omegaPartial 3 (565/224 : ℝ)
        ≤ ((565/224 : ℝ)^(σ/2 - 1) + (565/224 : ℝ)^((1-σ)/2 - 1))
          * Real.cos ((15/2 : ℝ) * Real.log (565/224 : ℝ))
          * omegaPartial 3 (565/224 : ℝ) := by
      calc 2 * (565/224 : ℝ)^(-(3/4 : ℝ))
            * Real.cos ((15/2 : ℝ) * Real.log (565/224 : ℝ))
            * omegaPartial 3 (565/224 : ℝ)
          = 2 * (565/224 : ℝ)^(-(3/4 : ℝ))
            * (Real.cos ((15/2 : ℝ) * Real.log (565/224 : ℝ))
              * omegaPartial 3 (565/224 : ℝ)) := by ring
        _ ≤ ((565/224 : ℝ)^(σ/2 - 1) + (565/224 : ℝ)^((1-σ)/2 - 1))
            * (Real.cos ((15/2 : ℝ) * Real.log (565/224 : ℝ))
              * omegaPartial 3 (565/224 : ℝ)) :=
          mul_le_mul_of_nonneg_right hAlo hCW
        _ = ((565/224 : ℝ)^(σ/2 - 1) + (565/224 : ℝ)^((1-σ)/2 - 1))
            * Real.cos ((15/2 : ℝ) * Real.log (565/224 : ℝ))
            * omegaPartial 3 (565/224 : ℝ) := by ring
    linarith [u2_re_tight_ge, hchain]
  · unfold realThetaReIntegrandN
    linarith [hRe.2, u2_re_adverse_le]
  · unfold realThetaImIntegrandN
    have h2 : (0 : ℝ) * 0 * 0 = 0 := by norm_num
    linarith [hIm.1]
  · unfold realThetaImIntegrandN
    linarith [hIm.2, u2_im_adverse_le]


/-! ## Panel 1 chunk sum -/

theorem seg29_p1_chunk_bounds (σ : ℝ)
    (hσ0 : (1 : ℝ)/2 ≤ σ) (hσ1 : σ ≤ 9/16) :
    ((2262669/2500000000 : ℝ)) ≤ realThetaReIntegrandN 3 σ 15 (561/224 : ℝ) + realThetaReIntegrandN 3 σ 15 (563/224 : ℝ) + realThetaReIntegrandN 3 σ 15 (565/224 : ℝ)
    ∧ realThetaReIntegrandN 3 σ 15 (561/224 : ℝ) + realThetaReIntegrandN 3 σ 15 (563/224 : ℝ) + realThetaReIntegrandN 3 σ 15 (565/224 : ℝ) ≤ ((23/25000 : ℝ))
    ∧ ((0/1 : ℝ)) ≤ realThetaImIntegrandN 3 σ 15 (561/224 : ℝ) + realThetaImIntegrandN 3 σ 15 (563/224 : ℝ) + realThetaImIntegrandN 3 σ 15 (565/224 : ℝ)
    ∧ realThetaImIntegrandN 3 σ 15 (561/224 : ℝ) + realThetaImIntegrandN 3 σ 15 (563/224 : ℝ) + realThetaImIntegrandN 3 σ 15 (565/224 : ℝ) ≤ ((191/10000000 : ℝ)) := by
  have h0 := node_0_bounds σ hσ0 hσ1
  have h1 := node_1_bounds σ hσ0 hσ1
  have h2 := node_2_bounds σ hσ0 hσ1
  refine ⟨?_, ?_, ?_, ?_⟩
  · linarith [h0.1, h1.1, h2.1]
  · linarith [h0.2.1, h1.2.1, h2.2.1]
  · linarith [h0.2.2.1, h1.2.2.1, h2.2.2.1]
  · linarith [h0.2.2.2, h1.2.2.2, h2.2.2.2]

end PrincipiaTractalis.RiemannXiBox0Panels.Seg29P1
