/-
# PF.Analytic.RiemannXiBox0Panels.Seg31P3

Panel 3 of Segment 31: nodes [6, 7, 8].
Auto-generated by scripts/emit_stage2_segment.py.
-/

import PF.Analytic.RiemannXiThetaRealFormAndBoxes_r331b
import Interval.Interval.Conversion
import Interval.Interval.Exp
import Interval.Interval.Log
import Interval.Interval.Sincos
import Interval.Interval.Pi
import Interval.Interval.Order
import Interval.Interval.Mul
import Interval.Tactic.Approx

namespace PrincipiaTractalis.RiemannXiBox0Panels.Seg31P3

open scoped Real
open PrincipiaTractalis.RiemannXiThetaRealFormAndBoxes
open PrincipiaTractalis.XiQuadrature

private theorem rpow_neg_eq_exp {x a : ℝ} (hx : 0 < x) :
    x ^ (-a) = Real.exp (-(Real.log x * a)) := by
  rw [Real.rpow_def_of_pos hx]; ring_nf

private theorem omegaPartial_3_closed {u : ℝ} :
    omegaPartial 3 u = Real.exp (-(π * u)) + Real.exp (-(π * 4 * u))
      + Real.exp (-(π * 9 * u)) := by
  unfold omegaPartial
  simp only [Finset.sum_range_succ, Finset.sum_range_zero, zero_add,
             Nat.cast_zero, Nat.cast_one, Nat.cast_ofNat, one_pow]
  ring_nf

/-! ## Node 6 at u = 409/144 — cos nn, sin nn -/

private theorem u6_cos_nn : (0 : ℝ) ≤ Real.cos ((15/2 : ℝ) * Real.log (409/144 : ℝ)) := by
  refine _root_.Interval.approx_le
    ((0 : _root_.Interval))
    (_root_.Interval.cos ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((409 : ℚ)/144))))
    (0 : ℝ)
    (Real.cos ((15/2 : ℝ) * Real.log (409/144 : ℝ)))
    (by approx)
    (_root_.Interval.mem_approx_cos (by approx))
    ?_
  decide +kernel


private theorem u6_sin_nn : (0 : ℝ) ≤ Real.sin ((15/2 : ℝ) * Real.log (409/144 : ℝ)) := by
  refine _root_.Interval.approx_le
    ((0 : _root_.Interval))
    (_root_.Interval.sin ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((409 : ℚ)/144))))
    (0 : ℝ)
    (Real.sin ((15/2 : ℝ) * Real.log (409/144 : ℝ)))
    (by approx)
    (_root_.Interval.mem_approx_sin (by approx))
    ?_
  decide +kernel


private theorem u6_re_adverse_le :
    ((409/144 : ℝ) ^ (-(23/32 : ℝ)) + (409/144 : ℝ) ^ (-(25/32 : ℝ)))
        * Real.cos ((15/2 : ℝ) * Real.log (409/144 : ℝ))
        * omegaPartial 3 (409/144 : ℝ)
      ≤ (1/100000 : ℝ) := by
  have hu0 : (0 : ℝ) < (409/144 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine le_of_lt <| _root_.Interval.approx_lt
    ((_root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((409 : ℚ)/144)) * _root_.Interval.ofRat (23/32)))
      + _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((409 : ℚ)/144)) * _root_.Interval.ofRat (25/32))))
     * _root_.Interval.cos ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((409 : ℚ)/144)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((409 : ℚ)/144)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((409 : ℚ)/144)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((409 : ℚ)/144)))))
    (1/100000 : _root_.Interval)
    _
    (1/100000 : ℝ)
    ?_
    (by approx)
    ?_
  · approx
  · decide +kernel

private theorem u6_re_tight_ge :
    (30113/10000000000 : ℝ)
      ≤ (2 * (409/144 : ℝ) ^ (-(3/4 : ℝ)))
        * Real.cos ((15/2 : ℝ) * Real.log (409/144 : ℝ))
        * omegaPartial 3 (409/144 : ℝ) := by
  have hu0 : (0 : ℝ) < (409/144 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine _root_.Interval.approx_le
    (30113/10000000000 : _root_.Interval)
    ((2 : _root_.Interval) * _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((409 : ℚ)/144)) * _root_.Interval.ofRat (3/4)))
     * _root_.Interval.cos ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((409 : ℚ)/144)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((409 : ℚ)/144)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((409 : ℚ)/144)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((409 : ℚ)/144)))))
    (30113/10000000000 : ℝ)
    _
    (by approx)
    ?_
    ?_
  · approx
  · decide +kernel


private theorem u6_im_adverse_le :
    ((409/144 : ℝ) ^ (-(23/32 : ℝ)) - (409/144 : ℝ) ^ (-(25/32 : ℝ)))
      * Real.sin ((15/2 : ℝ) * Real.log (409/144 : ℝ))
      * omegaPartial 3 (409/144 : ℝ)
      ≤ (1/250000 : ℝ) := by
  have hu0 : (0 : ℝ) < (409/144 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine le_of_lt <| _root_.Interval.approx_lt
    ((_root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((409 : ℚ)/144)) * _root_.Interval.ofRat (23/32)))
      - _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((409 : ℚ)/144)) * _root_.Interval.ofRat (25/32))))
     * _root_.Interval.sin ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((409 : ℚ)/144)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((409 : ℚ)/144)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((409 : ℚ)/144)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((409 : ℚ)/144)))))
    (1/250000 : _root_.Interval)
    _
    (1/250000 : ℝ)
    ?_
    (by approx)
    ?_
  · approx
  · decide +kernel


theorem node_6_bounds (σ : ℝ)
    (hσ0 : (1 : ℝ)/2 ≤ σ) (hσ1 : σ ≤ 9/16) :
    ((30113/10000000000 : ℝ)) ≤ realThetaReIntegrandN 3 σ 15 (409/144 : ℝ)
    ∧ realThetaReIntegrandN 3 σ 15 (409/144 : ℝ) ≤ ((1/100000 : ℝ))
    ∧ ((0 : ℝ)) ≤ realThetaImIntegrandN 3 σ 15 (409/144 : ℝ)
    ∧ realThetaImIntegrandN 3 σ 15 (409/144 : ℝ) ≤ ((1/250000 : ℝ)) := by
  have hu1 : (1 : ℝ) ≤ (409/144 : ℝ) := by norm_num
  have hA_nn : (0 : ℝ) ≤ (409/144 : ℝ)^(σ/2 - 1) + (409/144 : ℝ)^((1-σ)/2 - 1) :=
    box0_pow_sum_nonneg σ hu1
  have hA_hi : (409/144 : ℝ)^(σ/2 - 1) + (409/144 : ℝ)^((1-σ)/2 - 1)
      ≤ (409/144 : ℝ)^(-(23/32 : ℝ)) + (409/144 : ℝ)^(-(25/32 : ℝ)) :=
    box0_pow_sum_tight_ub hu1 hσ0 hσ1
  have hD_nn : (0 : ℝ) ≤ (409/144 : ℝ)^(σ/2 - 1) - (409/144 : ℝ)^((1-σ)/2 - 1) :=
    box0_pow_diff_nonneg hσ0 hu1
  have hD_hi : (409/144 : ℝ)^(σ/2 - 1) - (409/144 : ℝ)^((1-σ)/2 - 1)
      ≤ (409/144 : ℝ)^(-(23/32 : ℝ)) - (409/144 : ℝ)^(-(25/32 : ℝ)) :=
    box0_pow_diff_ub hσ0 hσ1 hu1
  have hW_nn : (0 : ℝ) ≤ omegaPartial 3 (409/144 : ℝ) := omegaPartial_nonneg_here 3 _
  have hAstar_nn : (0 : ℝ) ≤ (409/144 : ℝ)^(-(23/32 : ℝ)) + (409/144 : ℝ)^(-(25/32 : ℝ)) := by
    have h := box0_pow_sum_nonneg (9/16 : ℝ) hu1
    have eq1 : ((9 : ℝ)/16)/2 - 1 = -(23/32 : ℝ) := by norm_num
    have eq2 : (1 - (9 : ℝ)/16)/2 - 1 = -(25/32 : ℝ) := by norm_num
    rw [eq1, eq2] at h; exact h
  have hDstar_nn : (0 : ℝ) ≤ (409/144 : ℝ)^(-(23/32 : ℝ)) - (409/144 : ℝ)^(-(25/32 : ℝ)) := by
    have h := box0_pow_diff_nonneg (σ := 9/16) (by norm_num) hu1
    have eq1 : ((9 : ℝ)/16)/2 - 1 = -(23/32 : ℝ) := by norm_num
    have eq2 : (1 - (9 : ℝ)/16)/2 - 1 = -(25/32 : ℝ) := by norm_num
    rw [eq1, eq2] at h; exact h
  have hC : Real.cos ((15/2 : ℝ) * Real.log (409/144 : ℝ)) ≥ 0 := u6_cos_nn
  have hS : Real.sin ((15/2 : ℝ) * Real.log (409/144 : ℝ)) ≥ 0 := u6_sin_nn
  have hRe := re_scalar_bounds_cos_nonneg
    (A_lo := 0)
    (A_hi := (409/144 : ℝ)^(-(23/32 : ℝ)) + (409/144 : ℝ)^(-(25/32 : ℝ)))
    (C_lo := 0)
    (C_hi := Real.cos ((15/2 : ℝ) * Real.log (409/144 : ℝ)))
    (W_lo := 0) (W_hi := omegaPartial 3 (409/144 : ℝ))
    (le_refl 0) hAstar_nn (le_refl 0) hC
    (le_refl 0) hW_nn
    hA_nn hA_hi hC (le_refl _) hW_nn (le_refl _)
  have hIm := im_scalar_bounds_sin_nonneg
    (D_lo := 0)
    (D_hi := (409/144 : ℝ)^(-(23/32 : ℝ)) - (409/144 : ℝ)^(-(25/32 : ℝ)))
    (S_lo := 0)
    (S_hi := Real.sin ((15/2 : ℝ) * Real.log (409/144 : ℝ)))
    (W_lo := 0) (W_hi := omegaPartial 3 (409/144 : ℝ))
    (le_refl 0) hDstar_nn (le_refl 0) hS
    (le_refl 0) hW_nn
    hD_nn hD_hi hS (le_refl _) hW_nn (le_refl _)
  refine ⟨?_, ?_, ?_, ?_⟩
  · unfold realThetaReIntegrandN
    have hAlo : 2 * (409/144 : ℝ)^(-(3/4 : ℝ))
        ≤ (409/144 : ℝ)^(σ/2 - 1) + (409/144 : ℝ)^((1-σ)/2 - 1) :=
      box0_pow_sum_tight_lb hu1 hσ0 hσ1
    have hCW : (0 : ℝ) ≤ Real.cos ((15/2 : ℝ) * Real.log (409/144 : ℝ))
        * omegaPartial 3 (409/144 : ℝ) := mul_nonneg hC hW_nn
    have hchain : 2 * (409/144 : ℝ)^(-(3/4 : ℝ))
          * Real.cos ((15/2 : ℝ) * Real.log (409/144 : ℝ))
          * omegaPartial 3 (409/144 : ℝ)
        ≤ ((409/144 : ℝ)^(σ/2 - 1) + (409/144 : ℝ)^((1-σ)/2 - 1))
          * Real.cos ((15/2 : ℝ) * Real.log (409/144 : ℝ))
          * omegaPartial 3 (409/144 : ℝ) := by
      calc 2 * (409/144 : ℝ)^(-(3/4 : ℝ))
            * Real.cos ((15/2 : ℝ) * Real.log (409/144 : ℝ))
            * omegaPartial 3 (409/144 : ℝ)
          = 2 * (409/144 : ℝ)^(-(3/4 : ℝ))
            * (Real.cos ((15/2 : ℝ) * Real.log (409/144 : ℝ))
              * omegaPartial 3 (409/144 : ℝ)) := by ring
        _ ≤ ((409/144 : ℝ)^(σ/2 - 1) + (409/144 : ℝ)^((1-σ)/2 - 1))
            * (Real.cos ((15/2 : ℝ) * Real.log (409/144 : ℝ))
              * omegaPartial 3 (409/144 : ℝ)) :=
          mul_le_mul_of_nonneg_right hAlo hCW
        _ = ((409/144 : ℝ)^(σ/2 - 1) + (409/144 : ℝ)^((1-σ)/2 - 1))
            * Real.cos ((15/2 : ℝ) * Real.log (409/144 : ℝ))
            * omegaPartial 3 (409/144 : ℝ) := by ring
    linarith [u6_re_tight_ge, hchain]
  · unfold realThetaReIntegrandN
    linarith [hRe.2, u6_re_adverse_le]
  · unfold realThetaImIntegrandN
    have h2 : (0 : ℝ) * 0 * 0 = 0 := by norm_num
    linarith [hIm.1]
  · unfold realThetaImIntegrandN
    linarith [hIm.2, u6_im_adverse_le]
/-! ## Node 7 at u = 137/48 — cos np, sin nn -/

private theorem u7_cos_np : Real.cos ((15/2 : ℝ) * Real.log (137/48 : ℝ)) ≤ 0 := by
  have hlt : Real.cos ((15/2 : ℝ) * Real.log (137/48 : ℝ)) < (0 : ℝ) := by
    refine _root_.Interval.approx_lt
      (_root_.Interval.cos ((15/2 : _root_.Interval) * _root_.Interval.log
          (_root_.Interval.ofRat ((137 : ℚ)/48))))
      ((0 : _root_.Interval))
      (Real.cos ((15/2 : ℝ) * Real.log (137/48 : ℝ)))
      (0 : ℝ)
      (_root_.Interval.mem_approx_cos (by approx))
      (by approx)
      ?_
    decide +kernel
  linarith


private theorem u7_sin_nn : (0 : ℝ) ≤ Real.sin ((15/2 : ℝ) * Real.log (137/48 : ℝ)) := by
  refine _root_.Interval.approx_le
    ((0 : _root_.Interval))
    (_root_.Interval.sin ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((137 : ℚ)/48))))
    (0 : ℝ)
    (Real.sin ((15/2 : ℝ) * Real.log (137/48 : ℝ)))
    (by approx)
    (_root_.Interval.mem_approx_sin (by approx))
    ?_
  decide +kernel


private theorem u7_re_adverse_ge :
    (-69/50000000 : ℝ)
      ≤ ((137/48 : ℝ) ^ (-(23/32 : ℝ)) + (137/48 : ℝ) ^ (-(25/32 : ℝ)))
        * Real.cos ((15/2 : ℝ) * Real.log (137/48 : ℝ))
        * omegaPartial 3 (137/48 : ℝ) := by
  have hu0 : (0 : ℝ) < (137/48 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine _root_.Interval.approx_le
    (-69/50000000 : _root_.Interval)
    ((_root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((137 : ℚ)/48)) * _root_.Interval.ofRat (23/32)))
      + _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((137 : ℚ)/48)) * _root_.Interval.ofRat (25/32))))
     * _root_.Interval.cos ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((137 : ℚ)/48)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((137 : ℚ)/48)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((137 : ℚ)/48)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((137 : ℚ)/48)))))
    (-69/50000000 : ℝ)
    _
    (by approx)
    ?_
    ?_
  · approx
  · decide +kernel


private theorem u7_im_adverse_le :
    ((137/48 : ℝ) ^ (-(23/32 : ℝ)) - (137/48 : ℝ) ^ (-(25/32 : ℝ)))
      * Real.sin ((15/2 : ℝ) * Real.log (137/48 : ℝ))
      * omegaPartial 3 (137/48 : ℝ)
      ≤ (39/10000000 : ℝ) := by
  have hu0 : (0 : ℝ) < (137/48 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine le_of_lt <| _root_.Interval.approx_lt
    ((_root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((137 : ℚ)/48)) * _root_.Interval.ofRat (23/32)))
      - _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((137 : ℚ)/48)) * _root_.Interval.ofRat (25/32))))
     * _root_.Interval.sin ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((137 : ℚ)/48)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((137 : ℚ)/48)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((137 : ℚ)/48)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((137 : ℚ)/48)))))
    (39/10000000 : _root_.Interval)
    _
    (39/10000000 : ℝ)
    ?_
    (by approx)
    ?_
  · approx
  · decide +kernel


theorem node_7_bounds (σ : ℝ)
    (hσ0 : (1 : ℝ)/2 ≤ σ) (hσ1 : σ ≤ 9/16) :
    ((-69/50000000 : ℝ)) ≤ realThetaReIntegrandN 3 σ 15 (137/48 : ℝ)
    ∧ realThetaReIntegrandN 3 σ 15 (137/48 : ℝ) ≤ (0)
    ∧ ((0 : ℝ)) ≤ realThetaImIntegrandN 3 σ 15 (137/48 : ℝ)
    ∧ realThetaImIntegrandN 3 σ 15 (137/48 : ℝ) ≤ ((39/10000000 : ℝ)) := by
  have hu1 : (1 : ℝ) ≤ (137/48 : ℝ) := by norm_num
  have hA_nn : (0 : ℝ) ≤ (137/48 : ℝ)^(σ/2 - 1) + (137/48 : ℝ)^((1-σ)/2 - 1) :=
    box0_pow_sum_nonneg σ hu1
  have hA_hi : (137/48 : ℝ)^(σ/2 - 1) + (137/48 : ℝ)^((1-σ)/2 - 1)
      ≤ (137/48 : ℝ)^(-(23/32 : ℝ)) + (137/48 : ℝ)^(-(25/32 : ℝ)) :=
    box0_pow_sum_tight_ub hu1 hσ0 hσ1
  have hD_nn : (0 : ℝ) ≤ (137/48 : ℝ)^(σ/2 - 1) - (137/48 : ℝ)^((1-σ)/2 - 1) :=
    box0_pow_diff_nonneg hσ0 hu1
  have hD_hi : (137/48 : ℝ)^(σ/2 - 1) - (137/48 : ℝ)^((1-σ)/2 - 1)
      ≤ (137/48 : ℝ)^(-(23/32 : ℝ)) - (137/48 : ℝ)^(-(25/32 : ℝ)) :=
    box0_pow_diff_ub hσ0 hσ1 hu1
  have hW_nn : (0 : ℝ) ≤ omegaPartial 3 (137/48 : ℝ) := omegaPartial_nonneg_here 3 _
  have hAstar_nn : (0 : ℝ) ≤ (137/48 : ℝ)^(-(23/32 : ℝ)) + (137/48 : ℝ)^(-(25/32 : ℝ)) := by
    have h := box0_pow_sum_nonneg (9/16 : ℝ) hu1
    have eq1 : ((9 : ℝ)/16)/2 - 1 = -(23/32 : ℝ) := by norm_num
    have eq2 : (1 - (9 : ℝ)/16)/2 - 1 = -(25/32 : ℝ) := by norm_num
    rw [eq1, eq2] at h; exact h
  have hDstar_nn : (0 : ℝ) ≤ (137/48 : ℝ)^(-(23/32 : ℝ)) - (137/48 : ℝ)^(-(25/32 : ℝ)) := by
    have h := box0_pow_diff_nonneg (σ := 9/16) (by norm_num) hu1
    have eq1 : ((9 : ℝ)/16)/2 - 1 = -(23/32 : ℝ) := by norm_num
    have eq2 : (1 - (9 : ℝ)/16)/2 - 1 = -(25/32 : ℝ) := by norm_num
    rw [eq1, eq2] at h; exact h
  have hC : Real.cos ((15/2 : ℝ) * Real.log (137/48 : ℝ)) ≤ 0 := u7_cos_np
  have hS : Real.sin ((15/2 : ℝ) * Real.log (137/48 : ℝ)) ≥ 0 := u7_sin_nn
  have hRe := re_scalar_bounds_cos_neg
    (A_lo := 0)
    (A_hi := (137/48 : ℝ)^(-(23/32 : ℝ)) + (137/48 : ℝ)^(-(25/32 : ℝ)))
    (C_lo := Real.cos ((15/2 : ℝ) * Real.log (137/48 : ℝ)))
    (C_hi := 0) (W_lo := 0) (W_hi := omegaPartial 3 (137/48 : ℝ))
    (le_refl 0) hAstar_nn hC hC (le_refl 0)
    (le_refl 0) hW_nn
    hA_nn hA_hi (le_refl _) hC hW_nn (le_refl _)
  have hIm := im_scalar_bounds_sin_nonneg
    (D_lo := 0)
    (D_hi := (137/48 : ℝ)^(-(23/32 : ℝ)) - (137/48 : ℝ)^(-(25/32 : ℝ)))
    (S_lo := 0)
    (S_hi := Real.sin ((15/2 : ℝ) * Real.log (137/48 : ℝ)))
    (W_lo := 0) (W_hi := omegaPartial 3 (137/48 : ℝ))
    (le_refl 0) hDstar_nn (le_refl 0) hS
    (le_refl 0) hW_nn
    hD_nn hD_hi hS (le_refl _) hW_nn (le_refl _)
  refine ⟨?_, ?_, ?_, ?_⟩
  · unfold realThetaReIntegrandN
    linarith [hRe.1, u7_re_adverse_ge]
  · unfold realThetaReIntegrandN
    have h2 : (0 : ℝ) * 0 * 0 = 0 := by norm_num
    linarith [hRe.2]
  · unfold realThetaImIntegrandN
    have h2 : (0 : ℝ) * 0 * 0 = 0 := by norm_num
    linarith [hIm.1]
  · unfold realThetaImIntegrandN
    linarith [hIm.2, u7_im_adverse_le]
/-! ## Node 8 at u = 413/144 — cos np, sin nn -/

private theorem u8_cos_np : Real.cos ((15/2 : ℝ) * Real.log (413/144 : ℝ)) ≤ 0 := by
  have hlt : Real.cos ((15/2 : ℝ) * Real.log (413/144 : ℝ)) < (0 : ℝ) := by
    refine _root_.Interval.approx_lt
      (_root_.Interval.cos ((15/2 : _root_.Interval) * _root_.Interval.log
          (_root_.Interval.ofRat ((413 : ℚ)/144))))
      ((0 : _root_.Interval))
      (Real.cos ((15/2 : ℝ) * Real.log (413/144 : ℝ)))
      (0 : ℝ)
      (_root_.Interval.mem_approx_cos (by approx))
      (by approx)
      ?_
    decide +kernel
  linarith


private theorem u8_sin_nn : (0 : ℝ) ≤ Real.sin ((15/2 : ℝ) * Real.log (413/144 : ℝ)) := by
  refine _root_.Interval.approx_le
    ((0 : _root_.Interval))
    (_root_.Interval.sin ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((413 : ℚ)/144))))
    (0 : ℝ)
    (Real.sin ((15/2 : ℝ) * Real.log (413/144 : ℝ)))
    (by approx)
    (_root_.Interval.mem_approx_sin (by approx))
    ?_
  decide +kernel


private theorem u8_re_adverse_ge :
    (-26761/5000000000 : ℝ)
      ≤ ((413/144 : ℝ) ^ (-(23/32 : ℝ)) + (413/144 : ℝ) ^ (-(25/32 : ℝ)))
        * Real.cos ((15/2 : ℝ) * Real.log (413/144 : ℝ))
        * omegaPartial 3 (413/144 : ℝ) := by
  have hu0 : (0 : ℝ) < (413/144 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine _root_.Interval.approx_le
    (-26761/5000000000 : _root_.Interval)
    ((_root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((413 : ℚ)/144)) * _root_.Interval.ofRat (23/32)))
      + _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((413 : ℚ)/144)) * _root_.Interval.ofRat (25/32))))
     * _root_.Interval.cos ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((413 : ℚ)/144)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((413 : ℚ)/144)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((413 : ℚ)/144)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((413 : ℚ)/144)))))
    (-26761/5000000000 : ℝ)
    _
    (by approx)
    ?_
    ?_
  · approx
  · decide +kernel


private theorem u8_im_adverse_le :
    ((413/144 : ℝ) ^ (-(23/32 : ℝ)) - (413/144 : ℝ) ^ (-(25/32 : ℝ)))
      * Real.sin ((15/2 : ℝ) * Real.log (413/144 : ℝ))
      * omegaPartial 3 (413/144 : ℝ)
      ≤ (37/10000000 : ℝ) := by
  have hu0 : (0 : ℝ) < (413/144 : ℝ) := by norm_num
  rw [rpow_neg_eq_exp hu0, rpow_neg_eq_exp hu0, omegaPartial_3_closed]
  refine le_of_lt <| _root_.Interval.approx_lt
    ((_root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((413 : ℚ)/144)) * _root_.Interval.ofRat (23/32)))
      - _root_.Interval.exp (-(_root_.Interval.log
        (_root_.Interval.ofRat ((413 : ℚ)/144)) * _root_.Interval.ofRat (25/32))))
     * _root_.Interval.sin ((15/2 : _root_.Interval) * _root_.Interval.log
        (_root_.Interval.ofRat ((413 : ℚ)/144)))
     * (_root_.Interval.exp (-(_root_.Interval.pi *
          _root_.Interval.ofRat ((413 : ℚ)/144)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (4 : _root_.Interval) *
          _root_.Interval.ofRat ((413 : ℚ)/144)))
        + _root_.Interval.exp (-(_root_.Interval.pi * (9 : _root_.Interval) *
          _root_.Interval.ofRat ((413 : ℚ)/144)))))
    (37/10000000 : _root_.Interval)
    _
    (37/10000000 : ℝ)
    ?_
    (by approx)
    ?_
  · approx
  · decide +kernel


theorem node_8_bounds (σ : ℝ)
    (hσ0 : (1 : ℝ)/2 ≤ σ) (hσ1 : σ ≤ 9/16) :
    ((-26761/5000000000 : ℝ)) ≤ realThetaReIntegrandN 3 σ 15 (413/144 : ℝ)
    ∧ realThetaReIntegrandN 3 σ 15 (413/144 : ℝ) ≤ (0)
    ∧ ((0 : ℝ)) ≤ realThetaImIntegrandN 3 σ 15 (413/144 : ℝ)
    ∧ realThetaImIntegrandN 3 σ 15 (413/144 : ℝ) ≤ ((37/10000000 : ℝ)) := by
  have hu1 : (1 : ℝ) ≤ (413/144 : ℝ) := by norm_num
  have hA_nn : (0 : ℝ) ≤ (413/144 : ℝ)^(σ/2 - 1) + (413/144 : ℝ)^((1-σ)/2 - 1) :=
    box0_pow_sum_nonneg σ hu1
  have hA_hi : (413/144 : ℝ)^(σ/2 - 1) + (413/144 : ℝ)^((1-σ)/2 - 1)
      ≤ (413/144 : ℝ)^(-(23/32 : ℝ)) + (413/144 : ℝ)^(-(25/32 : ℝ)) :=
    box0_pow_sum_tight_ub hu1 hσ0 hσ1
  have hD_nn : (0 : ℝ) ≤ (413/144 : ℝ)^(σ/2 - 1) - (413/144 : ℝ)^((1-σ)/2 - 1) :=
    box0_pow_diff_nonneg hσ0 hu1
  have hD_hi : (413/144 : ℝ)^(σ/2 - 1) - (413/144 : ℝ)^((1-σ)/2 - 1)
      ≤ (413/144 : ℝ)^(-(23/32 : ℝ)) - (413/144 : ℝ)^(-(25/32 : ℝ)) :=
    box0_pow_diff_ub hσ0 hσ1 hu1
  have hW_nn : (0 : ℝ) ≤ omegaPartial 3 (413/144 : ℝ) := omegaPartial_nonneg_here 3 _
  have hAstar_nn : (0 : ℝ) ≤ (413/144 : ℝ)^(-(23/32 : ℝ)) + (413/144 : ℝ)^(-(25/32 : ℝ)) := by
    have h := box0_pow_sum_nonneg (9/16 : ℝ) hu1
    have eq1 : ((9 : ℝ)/16)/2 - 1 = -(23/32 : ℝ) := by norm_num
    have eq2 : (1 - (9 : ℝ)/16)/2 - 1 = -(25/32 : ℝ) := by norm_num
    rw [eq1, eq2] at h; exact h
  have hDstar_nn : (0 : ℝ) ≤ (413/144 : ℝ)^(-(23/32 : ℝ)) - (413/144 : ℝ)^(-(25/32 : ℝ)) := by
    have h := box0_pow_diff_nonneg (σ := 9/16) (by norm_num) hu1
    have eq1 : ((9 : ℝ)/16)/2 - 1 = -(23/32 : ℝ) := by norm_num
    have eq2 : (1 - (9 : ℝ)/16)/2 - 1 = -(25/32 : ℝ) := by norm_num
    rw [eq1, eq2] at h; exact h
  have hC : Real.cos ((15/2 : ℝ) * Real.log (413/144 : ℝ)) ≤ 0 := u8_cos_np
  have hS : Real.sin ((15/2 : ℝ) * Real.log (413/144 : ℝ)) ≥ 0 := u8_sin_nn
  have hRe := re_scalar_bounds_cos_neg
    (A_lo := 0)
    (A_hi := (413/144 : ℝ)^(-(23/32 : ℝ)) + (413/144 : ℝ)^(-(25/32 : ℝ)))
    (C_lo := Real.cos ((15/2 : ℝ) * Real.log (413/144 : ℝ)))
    (C_hi := 0) (W_lo := 0) (W_hi := omegaPartial 3 (413/144 : ℝ))
    (le_refl 0) hAstar_nn hC hC (le_refl 0)
    (le_refl 0) hW_nn
    hA_nn hA_hi (le_refl _) hC hW_nn (le_refl _)
  have hIm := im_scalar_bounds_sin_nonneg
    (D_lo := 0)
    (D_hi := (413/144 : ℝ)^(-(23/32 : ℝ)) - (413/144 : ℝ)^(-(25/32 : ℝ)))
    (S_lo := 0)
    (S_hi := Real.sin ((15/2 : ℝ) * Real.log (413/144 : ℝ)))
    (W_lo := 0) (W_hi := omegaPartial 3 (413/144 : ℝ))
    (le_refl 0) hDstar_nn (le_refl 0) hS
    (le_refl 0) hW_nn
    hD_nn hD_hi hS (le_refl _) hW_nn (le_refl _)
  refine ⟨?_, ?_, ?_, ?_⟩
  · unfold realThetaReIntegrandN
    linarith [hRe.1, u8_re_adverse_ge]
  · unfold realThetaReIntegrandN
    have h2 : (0 : ℝ) * 0 * 0 = 0 := by norm_num
    linarith [hRe.2]
  · unfold realThetaImIntegrandN
    have h2 : (0 : ℝ) * 0 * 0 = 0 := by norm_num
    linarith [hIm.1]
  · unfold realThetaImIntegrandN
    linarith [hIm.2, u8_im_adverse_le]


/-! ## Panel 3 chunk sum -/

theorem seg31_p3_chunk_bounds (σ : ℝ)
    (hσ0 : (1 : ℝ)/2 ≤ σ) (hσ1 : σ ≤ 9/16) :
    ((-37209/10000000000 : ℝ)) ≤ realThetaReIntegrandN 3 σ 15 (409/144 : ℝ) + realThetaReIntegrandN 3 σ 15 (137/48 : ℝ) + realThetaReIntegrandN 3 σ 15 (413/144 : ℝ)
    ∧ realThetaReIntegrandN 3 σ 15 (409/144 : ℝ) + realThetaReIntegrandN 3 σ 15 (137/48 : ℝ) + realThetaReIntegrandN 3 σ 15 (413/144 : ℝ) ≤ ((1/100000 : ℝ))
    ∧ ((0/1 : ℝ)) ≤ realThetaImIntegrandN 3 σ 15 (409/144 : ℝ) + realThetaImIntegrandN 3 σ 15 (137/48 : ℝ) + realThetaImIntegrandN 3 σ 15 (413/144 : ℝ)
    ∧ realThetaImIntegrandN 3 σ 15 (409/144 : ℝ) + realThetaImIntegrandN 3 σ 15 (137/48 : ℝ) + realThetaImIntegrandN 3 σ 15 (413/144 : ℝ) ≤ ((29/2500000 : ℝ)) := by
  have h6 := node_6_bounds σ hσ0 hσ1
  have h7 := node_7_bounds σ hσ0 hσ1
  have h8 := node_8_bounds σ hσ0 hσ1
  refine ⟨?_, ?_, ?_, ?_⟩
  · linarith [h6.1, h7.1, h8.1]
  · linarith [h6.2.1, h7.2.1, h8.2.1]
  · linarith [h6.2.2.1, h7.2.2.1, h8.2.2.1]
  · linarith [h6.2.2.2, h7.2.2.2, h8.2.2.2]

end PrincipiaTractalis.RiemannXiBox0Panels.Seg31P3
